"""Add comprehensive IX Legislature models and enhanced committee activities

Revision ID: 01894e9a83df
Revises: 022c327a51b3
Create Date: 2025-07-31 07:16:13.822006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01894e9a83df'
down_revision: Union[str, Sequence[str], None] = '022c327a51b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividades_parlamentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delegacoes_eventuais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delegacoes_permanentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_parlamentares_amizade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatores_peticoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requerimentos_ativ_dep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcomissoes_grupos_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividades_parlamentares_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividades_parlamentares_id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('act_nr', sa.String(length=50), nullable=True),
    sa.Column('act_tp', sa.String(length=10), nullable=True),
    sa.Column('act_tpdesc', sa.String(length=200), nullable=True),
    sa.Column('act_sel_lg', sa.String(length=20), nullable=True),
    sa.Column('act_sel_nr', sa.String(length=20), nullable=True),
    sa.Column('act_dtent', sa.String(length=50), nullable=True),
    sa.Column('act_dtdeb', sa.DateTime(), nullable=True),
    sa.Column('act_as', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividades_parlamentares_id'], ['atividades_parlamentares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delegacoes_eventuais_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegacoes_eventuais_id', sa.Integer(), nullable=False),
    sa.Column('dev_dtini', sa.String(length=50), nullable=True),
    sa.Column('dev_loc', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegacoes_eventuais_id'], ['delegacoes_eventuais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delegacoes_permanentes_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegacoes_permanentes_id', sa.Integer(), nullable=False),
    sa.Column('dep_id', sa.Integer(), nullable=True),
    sa.Column('dep_no', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegacoes_permanentes_id'], ['delegacoes_permanentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_parlamentares_amizade_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupos_parlamentares_amizade_id', sa.Integer(), nullable=False),
    sa.Column('cga_crg', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grupos_parlamentares_amizade_id'], ['grupos_parlamentares_amizade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatores_peticoes_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatores_peticoes_id', sa.Integer(), nullable=False),
    sa.Column('pec_dtrelf', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatores_peticoes_id'], ['relatores_peticoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requerimentos_ativ_dep_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requerimentos_ativ_dep_id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.Column('req_nr', sa.String(length=50), nullable=True),
    sa.Column('req_tp', sa.String(length=10), nullable=True),
    sa.Column('req_lg', sa.String(length=20), nullable=True),
    sa.Column('req_sl', sa.String(length=20), nullable=True),
    sa.Column('req_as', sa.Text(), nullable=True),
    sa.Column('req_dt', sa.DateTime(), nullable=True),
    sa.Column('req_per_tp', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requerimentos_ativ_dep_id'], ['requerimentos_ativ_dep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcomissoes_grupos_trabalho_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcomissoes_grupos_trabalho_id', sa.Integer(), nullable=False),
    sa.Column('scm_cd', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subcomissoes_grupos_trabalho_id'], ['subcomissoes_grupos_trabalho.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('actividades_comissao_outs', sa.Column('act_id', sa.Integer(), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('act_as', sa.Text(), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('act_dtent', sa.String(length=50), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('acc_dtaud', sa.String(length=50), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('act_tp', sa.String(length=10), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('act_tpdesc', sa.String(length=200), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('act_nr', sa.String(length=50), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('act_lg', sa.String(length=20), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('nome_entidade_externa', sa.Text(), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('cms_no', sa.String(length=500), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('cms_ab', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actividades_comissao_outs', 'cms_ab')
    op.drop_column('actividades_comissao_outs', 'cms_no')
    op.drop_column('actividades_comissao_outs', 'nome_entidade_externa')
    op.drop_column('actividades_comissao_outs', 'act_lg')
    op.drop_column('actividades_comissao_outs', 'act_nr')
    op.drop_column('actividades_comissao_outs', 'act_tpdesc')
    op.drop_column('actividades_comissao_outs', 'act_tp')
    op.drop_column('actividades_comissao_outs', 'acc_dtaud')
    op.drop_column('actividades_comissao_outs', 'act_dtent')
    op.drop_column('actividades_comissao_outs', 'act_as')
    op.drop_column('actividades_comissao_outs', 'act_id')
    op.drop_table('subcomissoes_grupos_trabalho_out')
    op.drop_table('requerimentos_ativ_dep_out')
    op.drop_table('relatores_peticoes_out')
    op.drop_table('grupos_parlamentares_amizade_out')
    op.drop_table('delegacoes_permanentes_out')
    op.drop_table('delegacoes_eventuais_out')
    op.drop_table('atividades_parlamentares_out')
    op.drop_table('subcomissoes_grupos_trabalho')
    op.drop_table('requerimentos_ativ_dep')
    op.drop_table('relatores_peticoes')
    op.drop_table('grupos_parlamentares_amizade')
    op.drop_table('delegacoes_permanentes')
    op.drop_table('delegacoes_eventuais')
    op.drop_table('atividades_parlamentares')
    # ### end Alembic commands ###
