"""Add missing PubSl field to ActividadeIntervencaoOut model

Revision ID: 022c327a51b3
Revises: 1f6efe0729a2
Create Date: 2025-07-31 07:06:02.633730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022c327a51b3'
down_revision: Union[str, Sequence[str], None] = '1f6efe0729a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividade_intervencoes_out', sa.Column('pub_sl', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actividade_intervencoes_out', 'pub_sl')
    # ### end Alembic commands ###
