"""Change atividade_parlamentar unique constraint to composite

Revision ID: 071faf27c613
Revises: 2af80e87132d
Create Date: 2025-12-31 08:04:11.612447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071faf27c613'
down_revision: Union[str, Sequence[str], None] = '2af80e87132d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atividade_parlamentar', 'atividade_id',
               existing_type=sa.INTEGER(),
               comment='Activity identifier (IDAtividade) - unique per legislature',
               existing_comment='Activity identifier (IDAtividade) - unique registry ID',
               existing_nullable=True)
    op.drop_constraint(op.f('atividade_parlamentar_atividade_id_key'), 'atividade_parlamentar', type_='unique')
    op.create_unique_constraint('uq_atividade_legislatura', 'atividade_parlamentar', ['atividade_id', 'legislatura_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_atividade_legislatura', 'atividade_parlamentar', type_='unique')
    op.create_unique_constraint(op.f('atividade_parlamentar_atividade_id_key'), 'atividade_parlamentar', ['atividade_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('atividade_parlamentar', 'atividade_id',
               existing_type=sa.INTEGER(),
               comment='Activity identifier (IDAtividade) - unique registry ID',
               existing_comment='Activity identifier (IDAtividade) - unique per legislature',
               existing_nullable=True)
    # ### end Alembic commands ###
