"""Add dep_nome_completo to permanent_committee_historical_compositions for VI Legislature

Revision ID: 13e0c5a63ee9
Revises: 48ee63157549
Create Date: 2025-07-31 15:46:51.130257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e0c5a63ee9'
down_revision: Union[str, Sequence[str], None] = '48ee63157549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanent_committee_historical_compositions', sa.Column('dep_nome_completo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permanent_committee_historical_compositions', 'dep_nome_completo')
    # ### end Alembic commands ###
