"""Add XIII Legislature diploma fields (anexos, OrcamContasGerencia model)

Revision ID: 1783bd7a403c
Revises: e40c39d3bac1
Create Date: 2025-08-04 06:33:09.800038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1783bd7a403c'
down_revision: Union[str, Sequence[str], None] = 'e40c39d3bac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diploma_orcam_contas_gerencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diploma_id', sa.Integer(), nullable=False),
    sa.Column('orcam_id', sa.Integer(), nullable=True),
    sa.Column('leg', sa.String(length=50), nullable=True),
    sa.Column('tp', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['diploma_id'], ['diplomas_aprovados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('diplomas_aprovados', sa.Column('anexos', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diplomas_aprovados', 'anexos')
    op.drop_table('diploma_orcam_contas_gerencia')
    # ### end Alembic commands ###
