"""Fix DeputyInitiative foreign key to reference atividade_deputados instead of deputy_activities

Revision ID: 18521b6937e0
Revises: dcf2f3ad6b7b
Create Date: 2025-07-31 21:57:15.177082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18521b6937e0'
down_revision: Union[str, Sequence[str], None] = 'dcf2f3ad6b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commission_president_conferences', 'nome_sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint(op.f('deputy_initiatives_ibfk_1'), 'deputy_initiatives', type_='foreignkey')
    op.create_foreign_key(None, 'deputy_initiatives', 'atividade_deputados', ['deputy_activity_id'], ['id'])
    op.drop_constraint(op.f('deputy_interventions_ibfk_1'), 'deputy_interventions', type_='foreignkey')
    op.create_foreign_key(None, 'deputy_interventions', 'atividade_deputados', ['deputy_activity_id'], ['id'])
    op.drop_constraint(op.f('deputy_legislative_data_ibfk_1'), 'deputy_legislative_data', type_='foreignkey')
    op.create_foreign_key(None, 'deputy_legislative_data', 'atividade_deputados', ['deputy_activity_id'], ['id'])
    op.drop_constraint(op.f('deputy_parliamentary_activities_ibfk_1'), 'deputy_parliamentary_activities', type_='foreignkey')
    op.create_foreign_key(None, 'deputy_parliamentary_activities', 'atividade_deputados', ['deputy_activity_id'], ['id'])
    op.drop_constraint(op.f('deputy_reports_ibfk_1'), 'deputy_reports', type_='foreignkey')
    op.create_foreign_key(None, 'deputy_reports', 'atividade_deputados', ['deputy_activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deputy_reports', type_='foreignkey')
    op.create_foreign_key(op.f('deputy_reports_ibfk_1'), 'deputy_reports', 'deputy_activities', ['deputy_activity_id'], ['id'])
    op.drop_constraint(None, 'deputy_parliamentary_activities', type_='foreignkey')
    op.create_foreign_key(op.f('deputy_parliamentary_activities_ibfk_1'), 'deputy_parliamentary_activities', 'deputy_activities', ['deputy_activity_id'], ['id'])
    op.drop_constraint(None, 'deputy_legislative_data', type_='foreignkey')
    op.create_foreign_key(op.f('deputy_legislative_data_ibfk_1'), 'deputy_legislative_data', 'deputy_activities', ['deputy_activity_id'], ['id'])
    op.drop_constraint(None, 'deputy_interventions', type_='foreignkey')
    op.create_foreign_key(op.f('deputy_interventions_ibfk_1'), 'deputy_interventions', 'deputy_activities', ['deputy_activity_id'], ['id'])
    op.drop_constraint(None, 'deputy_initiatives', type_='foreignkey')
    op.create_foreign_key(op.f('deputy_initiatives_ibfk_1'), 'deputy_initiatives', 'deputy_activities', ['deputy_activity_id'], ['id'])
    op.alter_column('commission_president_conferences', 'nome_sigla',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
