"""add_peticao_fields_to_eventos_peticoes_conjuntas

Revision ID: 1a8d029ebd54
Revises: c08492a8616f
Create Date: 2026-01-01 17:16:52.394366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8d029ebd54'
down_revision: Union[str, Sequence[str], None] = 'c08492a8616f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iniciativas_eventos_peticoes_conjuntas', sa.Column('peticao_id', sa.Integer(), nullable=True))
    op.add_column('iniciativas_eventos_peticoes_conjuntas', sa.Column('peticao_titulo', sa.Text(), nullable=True))
    op.add_column('iniciativas_eventos_peticoes_conjuntas', sa.Column('peticao_nr', sa.Text(), nullable=True))
    op.add_column('iniciativas_eventos_peticoes_conjuntas', sa.Column('peticao_tipo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iniciativas_eventos_peticoes_conjuntas', 'peticao_tipo')
    op.drop_column('iniciativas_eventos_peticoes_conjuntas', 'peticao_nr')
    op.drop_column('iniciativas_eventos_peticoes_conjuntas', 'peticao_titulo')
    op.drop_column('iniciativas_eventos_peticoes_conjuntas', 'peticao_id')
    # ### end Alembic commands ###
