"""Add nested orcamento estado models for diploma structure processing

Revision ID: 21cc9d653cb6
Revises: fcd8574010ee
Create Date: 2025-08-07 18:49:56.861500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cc9d653cb6'
down_revision: Union[str, Sequence[str], None] = 'fcd8574010ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento_estado_requerimentos_avocacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Request description (AvocacaoDescricao)'),
    sa.Column('data_avocacao', sa.Date(), nullable=True, comment='Request date (AvocacaoData)'),
    sa.Column('titulo', sa.Text(), nullable=True, comment='Request title (AvocacaoTitulo)'),
    sa.Column('estado', sa.String(length=100), nullable=True, comment='Request state (AvocacaoEstado)'),
    sa.Column('ficheiro_url', sa.String(length=500), nullable=True, comment='Request file URL (AvocacaoFicheiro)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['orcamento_estado_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_diploma_artigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diploma_id', sa.Integer(), nullable=False),
    sa.Column('artigo_id', sa.Integer(), nullable=True, comment='Article ID (ID_Art)'),
    sa.Column('numero', sa.String(length=100), nullable=True, comment='Article number (Numero)'),
    sa.Column('titulo', sa.Text(), nullable=True, comment='Article title (Titulo)'),
    sa.Column('texto', sa.Text(), nullable=True, comment='Article content (Texto)'),
    sa.Column('estado', sa.String(length=100), nullable=True, comment='Article state (Estado)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diploma_id'], ['orcamento_estado_diplomas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_diploma_numeros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diploma_artigo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=True, comment='Number title (DiplomaNumeroTitulo)'),
    sa.Column('estado', sa.String(length=100), nullable=True, comment='Number state (DiplomaNumeroEstado)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diploma_artigo_id'], ['orcamento_estado_diploma_artigos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_diploma_alineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diploma_numero_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=True, comment='Alinea title (DiplomaAlineaTitulo)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diploma_numero_id'], ['orcamento_estado_diploma_numeros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orcamento_estado_diploma_alineas')
    op.drop_table('orcamento_estado_diploma_numeros')
    op.drop_table('orcamento_estado_diploma_artigos')
    op.drop_table('orcamento_estado_requerimentos_avocacao')
    # ### end Alembic commands ###
