"""Add DelegacaoPermanenteComissao model for XIII Legislature commission data

Revision ID: 2513b754a993
Revises: 8d3896359c70
Create Date: 2025-08-04 06:44:52.348768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2513b754a993'
down_revision: Union[str, Sequence[str], None] = '8d3896359c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegacao_permanente_comissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegacao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('composicao', sa.Text(), nullable=True),
    sa.Column('subcomissoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegacao_id'], ['delegacao_permanente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delegacao_permanente_comissoes')
    # ### end Alembic commands ###
