"""Add IX Legislature participante_id field to DelegacaoEventualParticipante

Revision ID: 27f0b295c53c
Revises: 1783bd7a403c
Create Date: 2025-08-04 06:36:24.036195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f0b295c53c'
down_revision: Union[str, Sequence[str], None] = '1783bd7a403c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delegacao_eventual_participantes', sa.Column('participante_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delegacao_eventual_participantes', 'participante_id')
    # ### end Alembic commands ###
