"""Add petition audiencias, pedidos informacao and missing fields for IX Legislature

Revision ID: 28d338e90bab
Revises: e25cb9a54763
Create Date: 2025-08-04 05:49:26.495921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d338e90bab'
down_revision: Union[str, Sequence[str], None] = 'e25cb9a54763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peticoes_audiencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissao_peticao_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['comissao_peticao_id'], ['peticoes_comissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_pedidos_informacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissao_peticao_id', sa.Integer(), nullable=False),
    sa.Column('nr_oficio', sa.Text(), nullable=True),
    sa.Column('entidades', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_peticao_id'], ['peticoes_comissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('peticoes_oradores', sa.Column('governo', sa.Text(), nullable=True))
    op.add_column('peticoes_oradores', sa.Column('teor', sa.Text(), nullable=True))
    op.add_column('peticoes_oradores_publicacoes', sa.Column('id_pag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peticoes_oradores_publicacoes', 'id_pag')
    op.drop_column('peticoes_oradores', 'teor')
    op.drop_column('peticoes_oradores', 'governo')
    op.drop_table('peticoes_pedidos_informacao')
    op.drop_table('peticoes_audiencias')
    # ### end Alembic commands ###
