"""Check sync status

Revision ID: 29825b710250
Revises: c1e54d379d1f
Create Date: 2025-08-10 15:18:04.412806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29825b710250'
down_revision: Union[str, Sequence[str], None] = 'c1e54d379d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registo_interesses_unified', 'record_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registo_interesses_unified', sa.Column('record_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    # ### end Alembic commands ###
