"""Add xml_source_id to deputados

Revision ID: 2af80e87132d
Revises: 1aafdff28c90
Create Date: 2025-12-30 18:40:34.748474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af80e87132d'
down_revision: Union[str, Sequence[str], None] = '1aafdff28c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deputados', sa.Column('xml_source_id', sa.Integer(), nullable=True, comment='Original DepId from XML (unique per legislature, used for FK resolution during import)'))
    op.alter_column('deputados', 'id',
               existing_type=sa.UUID(),
               comment='UUID primary key',
               existing_comment='Legislature-specific deputy ID (XML: DepId)',
               existing_nullable=False)
    op.create_index(op.f('ix_deputados_xml_source_id'), 'deputados', ['xml_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deputados_xml_source_id'), table_name='deputados')
    op.alter_column('deputados', 'id',
               existing_type=sa.UUID(),
               comment='Legislature-specific deputy ID (XML: DepId)',
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.drop_column('deputados', 'xml_source_id')
    # ### end Alembic commands ###
