"""Add missing deputy fields: Dpl_lg, DepCargo, and DadosCargoDeputado models

Revision ID: 2dcb66294669
Revises: 5af86382bc79
Create Date: 2025-07-30 17:56:11.945751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dcb66294669'
down_revision: Union[str, Sequence[str], None] = '5af86382bc79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividade_parlamentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('desc_tipo', sa.String(length=200), nullable=True),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('data_atividade', sa.Date(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('data_agendamento_debate', sa.Date(), nullable=True),
    sa.Column('tipo_autor', sa.String(length=100), nullable=True),
    sa.Column('autores_gp', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atividade_id')
    )
    op.create_table('cooperacao_parlamentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('cooperacao_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('sessao', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('local', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cooperacao_id')
    )
    op.create_table('debate_parlamentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=True),
    sa.Column('tipo_debate_desig', sa.String(length=200), nullable=True),
    sa.Column('data_debate', sa.Date(), nullable=True),
    sa.Column('tipo_debate', sa.String(length=100), nullable=True),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('intervencoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('debate_id')
    )
    op.create_table('delegacao_eventual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('delegacao_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('local', sa.Text(), nullable=True),
    sa.Column('sessao', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delegacao_id')
    )
    op.create_table('delegacao_permanente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('delegacao_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('sessao', sa.String(length=50), nullable=True),
    sa.Column('data_eleicao', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delegacao_id')
    )
    op.create_table('dep_cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diplomas_aprovados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('diploma_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('sessao', sa.Integer(), nullable=True),
    sa.Column('ano_civil', sa.Integer(), nullable=True),
    sa.Column('link_texto', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tp', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diploma_id')
    )
    op.create_table('iniciativas_detalhadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ini_id', sa.Integer(), nullable=False),
    sa.Column('ini_nr', sa.Integer(), nullable=True),
    sa.Column('ini_tipo', sa.Text(), nullable=True),
    sa.Column('ini_desc_tipo', sa.Text(), nullable=True),
    sa.Column('ini_leg', sa.Text(), nullable=True),
    sa.Column('ini_sel', sa.Integer(), nullable=True),
    sa.Column('data_inicio_leg', sa.Date(), nullable=True),
    sa.Column('data_fim_leg', sa.Date(), nullable=True),
    sa.Column('ini_titulo', sa.Text(), nullable=True),
    sa.Column('ini_texto_subst', sa.Text(), nullable=True),
    sa.Column('ini_link_texto', sa.Text(), nullable=True),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ini_id')
    )
    op.create_table('intervencao_parlamentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('intervencao_id', sa.Integer(), nullable=True),
    sa.Column('legislatura_numero', sa.String(length=50), nullable=True),
    sa.Column('sessao_numero', sa.String(length=50), nullable=True),
    sa.Column('tipo_intervencao', sa.String(length=200), nullable=True),
    sa.Column('data_reuniao_plenaria', sa.Date(), nullable=True),
    sa.Column('qualidade', sa.String(length=100), nullable=True),
    sa.Column('fase_sessao', sa.String(length=100), nullable=True),
    sa.Column('sumario', sa.Text(), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('id_debate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intervencao_id')
    )
    op.create_table('perguntas_requerimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('requerimento_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('nr', sa.Integer(), nullable=True),
    sa.Column('req_tipo', sa.String(length=100), nullable=True),
    sa.Column('sessao', sa.Integer(), nullable=True),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('dt_entrada', sa.Date(), nullable=True),
    sa.Column('data_envio', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ficheiro', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requerimento_id')
    )
    op.create_table('peticoes_detalhadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('pet_nr', sa.Integer(), nullable=True),
    sa.Column('pet_leg', sa.Text(), nullable=True),
    sa.Column('pet_sel', sa.Integer(), nullable=True),
    sa.Column('pet_assunto', sa.Text(), nullable=True),
    sa.Column('pet_situacao', sa.Text(), nullable=True),
    sa.Column('pet_nr_assinaturas', sa.Integer(), nullable=True),
    sa.Column('pet_data_entrada', sa.Date(), nullable=True),
    sa.Column('pet_atividade_id', sa.Integer(), nullable=True),
    sa.Column('pet_autor', sa.Text(), nullable=True),
    sa.Column('data_debate', sa.Date(), nullable=True),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id')
    )
    op.create_table('registo_interesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('spouse_name', sa.String(length=200), nullable=True),
    sa.Column('matrimonial_regime', sa.String(length=100), nullable=True),
    sa.Column('exclusivity', sa.String(length=10), nullable=True),
    sa.Column('dgf_number', sa.String(length=50), nullable=True),
    sa.Column('cad_id', sa.Integer(), nullable=True),
    sa.Column('cad_nome_completo', sa.String(length=200), nullable=True),
    sa.Column('cad_actividade_profissional', sa.Text(), nullable=True),
    sa.Column('cad_estado_civil_cod', sa.String(length=10), nullable=True),
    sa.Column('cad_estado_civil_des', sa.String(length=50), nullable=True),
    sa.Column('cad_fam_id', sa.Integer(), nullable=True),
    sa.Column('cad_nome_conjuge', sa.String(length=200), nullable=True),
    sa.Column('cad_rgi', sa.String(length=100), nullable=True),
    sa.Column('schema_version', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_parlamentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('comissao', sa.String(length=200), nullable=True),
    sa.Column('entidades_externas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relatorio_id')
    )
    op.create_table('atividade_parlamentar_convidados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('honra', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade_parlamentar_eleitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade_parlamentar_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.String(length=100), nullable=True),
    sa.Column('pub_tp', sa.String(length=50), nullable=True),
    sa.Column('pub_leg', sa.String(length=50), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('id_deb', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade_parlamentar_votacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('votacao_id', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(length=100), nullable=True),
    sa.Column('reuniao', sa.String(length=100), nullable=True),
    sa.Column('publicacao', sa.String(length=200), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooperacao_atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cooperacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo_atividade', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cooperacao_id'], ['cooperacao_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooperacao_programas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cooperacao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cooperacao_id'], ['cooperacao_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dados_cargo_deputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dep_cargo_id', sa.Integer(), nullable=False),
    sa.Column('car_des', sa.String(length=200), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('car_dt_inicio', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dep_cargo_id'], ['dep_cargos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delegacao_eventual_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegacao_id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('gp', sa.String(length=50), nullable=True),
    sa.Column('tipo_participante', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegacao_id'], ['delegacao_eventual.id'], ),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delegacao_permanente_membros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegacao_id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=True),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('gp', sa.String(length=50), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegacao_id'], ['delegacao_permanente.id'], ),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diploma_iniciativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diploma_id', sa.Integer(), nullable=False),
    sa.Column('ini_nr', sa.Integer(), nullable=True),
    sa.Column('ini_tipo', sa.String(length=100), nullable=True),
    sa.Column('ini_link_texto', sa.Text(), nullable=True),
    sa.Column('ini_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diploma_id'], ['diplomas_aprovados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diploma_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diploma_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.String(length=50), nullable=True),
    sa.Column('pub_tp', sa.String(length=10), nullable=True),
    sa.Column('pub_leg', sa.String(length=20), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.Column('supl', sa.String(length=10), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('pag_final_diario_supl', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diploma_id'], ['diplomas_aprovados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_autores_deputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_id', sa.Integer(), nullable=False),
    sa.Column('id_cadastro', sa.Integer(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('gp', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_autores_grupos_parlamentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_id', sa.Integer(), nullable=False),
    sa.Column('gp', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_autores_outros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_id', sa.Integer(), nullable=False),
    sa.Column('oev_id', sa.Integer(), nullable=True),
    sa.Column('data_fase', sa.Date(), nullable=True),
    sa.Column('fase', sa.Text(), nullable=True),
    sa.Column('evt_id', sa.Integer(), nullable=True),
    sa.Column('codigo_fase', sa.Integer(), nullable=True),
    sa.Column('obs_fase', sa.Text(), nullable=True),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('oev_text_id', sa.Integer(), nullable=True),
    sa.Column('textos_aprovados', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_propostas_alteracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_id', sa.Integer(), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('autor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervencao_atividades_relacionadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervencao_id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intervencao_id'], ['intervencao_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervencao_audiovisuais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervencao_id', sa.Integer(), nullable=False),
    sa.Column('duracao', sa.String(length=50), nullable=True),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('tipo_intervencao', sa.String(length=200), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intervencao_id'], ['intervencao_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervencao_convidados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervencao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intervencao_id'], ['intervencao_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervencao_deputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervencao_id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=True),
    sa.Column('id_cadastro', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('gp', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.ForeignKeyConstraint(['intervencao_id'], ['intervencao_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervencao_iniciativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervencao_id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('fase', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intervencao_id'], ['intervencao_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervencao_membros_governo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervencao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('governo', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intervencao_id'], ['intervencao_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervencao_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervencao_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.String(length=100), nullable=True),
    sa.Column('pub_tp', sa.String(length=50), nullable=True),
    sa.Column('pub_leg', sa.String(length=50), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('id_int', sa.Integer(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intervencao_id'], ['intervencao_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta_requerimento_autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta_requerimento_id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=True),
    sa.Column('id_cadastro', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('gp', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.ForeignKeyConstraint(['pergunta_requerimento_id'], ['perguntas_requerimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta_requerimento_destinatarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta_requerimento_id', sa.Integer(), nullable=False),
    sa.Column('nome_entidade', sa.String(length=200), nullable=True),
    sa.Column('data_envio', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pergunta_requerimento_id'], ['perguntas_requerimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta_requerimento_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta_requerimento_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.String(length=50), nullable=True),
    sa.Column('pub_tp', sa.String(length=10), nullable=True),
    sa.Column('pub_leg', sa.String(length=20), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('supl', sa.String(length=10), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('pag_final_diario_supl', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pergunta_requerimento_id'], ['perguntas_requerimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_comissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peticao_id', sa.Integer(), nullable=False),
    sa.Column('legislatura', sa.Text(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('id_comissao', sa.Integer(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('admissibilidade', sa.Text(), nullable=True),
    sa.Column('data_admissibilidade', sa.Date(), nullable=True),
    sa.Column('data_envio_par', sa.Date(), nullable=True),
    sa.Column('data_arquivo', sa.Date(), nullable=True),
    sa.Column('situacao', sa.Text(), nullable=True),
    sa.Column('data_reaberta', sa.Date(), nullable=True),
    sa.Column('data_baixa_comissao', sa.Date(), nullable=True),
    sa.Column('transitada', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['peticao_id'], ['peticoes_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_intervencoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peticao_id', sa.Integer(), nullable=False),
    sa.Column('data_reuniao_plenaria', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['peticao_id'], ['peticoes_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peticao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.Text(), nullable=True),
    sa.Column('pub_tp', sa.Text(), nullable=True),
    sa.Column('pub_leg', sa.Text(), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['peticao_id'], ['peticoes_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooperacao_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('entidade', sa.String(length=200), nullable=True),
    sa.Column('tipo_participante', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['cooperacao_atividades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_conjuntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('nr', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('desc_tipo', sa.Text(), nullable=True),
    sa.Column('leg', sa.Text(), nullable=True),
    sa.Column('sel', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('ini_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['iniciativas_eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_eventos_comissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('acc_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('id_comissao', sa.Integer(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('competente', sa.Text(), nullable=True),
    sa.Column('data_distribuicao', sa.Date(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('data_agendamento_plenario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['iniciativas_eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_eventos_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.Text(), nullable=True),
    sa.Column('pub_tp', sa.Text(), nullable=True),
    sa.Column('pub_leg', sa.Text(), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['iniciativas_eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_eventos_recursos_gp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('grupo_parlamentar', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['iniciativas_eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_eventos_votacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('id_votacao', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('reuniao', sa.Integer(), nullable=True),
    sa.Column('tipo_reuniao', sa.Text(), nullable=True),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('unanime', sa.Text(), nullable=True),
    sa.Column('data_votacao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['iniciativas_eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_intervencoes_debates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('data_reuniao_plenaria', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['iniciativas_eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_propostas_alteracao_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.Text(), nullable=True),
    sa.Column('pub_tp', sa.Text(), nullable=True),
    sa.Column('pub_leg', sa.Text(), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proposta_id'], ['iniciativas_propostas_alteracao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta_requerimento_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('entidade', sa.String(length=200), nullable=True),
    sa.Column('data_resposta', sa.Date(), nullable=True),
    sa.Column('ficheiro', sa.Text(), nullable=True),
    sa.Column('doc_remetida', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['pergunta_requerimento_destinatarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peticao_id', sa.Integer(), nullable=True),
    sa.Column('comissao_peticao_id', sa.Integer(), nullable=True),
    sa.Column('tipo_documento_categoria', sa.Text(), nullable=True),
    sa.Column('titulo_documento', sa.Text(), nullable=True),
    sa.Column('data_documento', sa.Date(), nullable=True),
    sa.Column('tipo_documento', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_peticao_id'], ['peticoes_comissoes.id'], ),
    sa.ForeignKeyConstraint(['peticao_id'], ['peticoes_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_oradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervencao_id', sa.Integer(), nullable=False),
    sa.Column('fase_sessao', sa.Text(), nullable=True),
    sa.Column('sumario', sa.Text(), nullable=True),
    sa.Column('convidados', sa.Text(), nullable=True),
    sa.Column('membros_governo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['intervencao_id'], ['peticoes_intervencoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_relatores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissao_peticao_id', sa.Integer(), nullable=False),
    sa.Column('relator_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('gp', sa.Text(), nullable=True),
    sa.Column('data_nomeacao', sa.Date(), nullable=True),
    sa.Column('data_cessacao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_peticao_id'], ['peticoes_comissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_relatorios_finais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissao_peticao_id', sa.Integer(), nullable=False),
    sa.Column('data_relatorio', sa.Date(), nullable=True),
    sa.Column('votacao', sa.Text(), nullable=True),
    sa.Column('relatorio_final_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_peticao_id'], ['peticoes_comissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_comissoes_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.Text(), nullable=True),
    sa.Column('pub_tp', sa.Text(), nullable=True),
    sa.Column('pub_leg', sa.Text(), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_id'], ['iniciativas_eventos_comissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_votacoes_ausencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votacao_id', sa.Integer(), nullable=False),
    sa.Column('grupo_parlamentar', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['votacao_id'], ['iniciativas_eventos_votacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_oradores_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orador_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.Text(), nullable=True),
    sa.Column('pub_tp', sa.Text(), nullable=True),
    sa.Column('pub_leg', sa.Text(), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('id_int', sa.Integer(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orador_id'], ['peticoes_oradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dados_legis_deputados', sa.Column('dpl_lg', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados_legis_deputados', 'dpl_lg')
    op.drop_table('peticoes_oradores_publicacoes')
    op.drop_table('iniciativas_votacoes_ausencias')
    op.drop_table('iniciativas_comissoes_publicacoes')
    op.drop_table('peticoes_relatorios_finais')
    op.drop_table('peticoes_relatores')
    op.drop_table('peticoes_oradores')
    op.drop_table('peticoes_documentos')
    op.drop_table('pergunta_requerimento_respostas')
    op.drop_table('iniciativas_propostas_alteracao_publicacoes')
    op.drop_table('iniciativas_intervencoes_debates')
    op.drop_table('iniciativas_eventos_votacoes')
    op.drop_table('iniciativas_eventos_recursos_gp')
    op.drop_table('iniciativas_eventos_publicacoes')
    op.drop_table('iniciativas_eventos_comissoes')
    op.drop_table('iniciativas_conjuntas')
    op.drop_table('cooperacao_participantes')
    op.drop_table('peticoes_publicacoes')
    op.drop_table('peticoes_intervencoes')
    op.drop_table('peticoes_comissoes')
    op.drop_table('pergunta_requerimento_publicacoes')
    op.drop_table('pergunta_requerimento_destinatarios')
    op.drop_table('pergunta_requerimento_autores')
    op.drop_table('intervencao_publicacoes')
    op.drop_table('intervencao_membros_governo')
    op.drop_table('intervencao_iniciativas')
    op.drop_table('intervencao_deputados')
    op.drop_table('intervencao_convidados')
    op.drop_table('intervencao_audiovisuais')
    op.drop_table('intervencao_atividades_relacionadas')
    op.drop_table('iniciativas_propostas_alteracao')
    op.drop_table('iniciativas_eventos')
    op.drop_table('iniciativas_autores_outros')
    op.drop_table('iniciativas_autores_grupos_parlamentares')
    op.drop_table('iniciativas_autores_deputados')
    op.drop_table('diploma_publicacoes')
    op.drop_table('diploma_iniciativas')
    op.drop_table('delegacao_permanente_membros')
    op.drop_table('delegacao_eventual_participantes')
    op.drop_table('dados_cargo_deputados')
    op.drop_table('cooperacao_programas')
    op.drop_table('cooperacao_atividades')
    op.drop_table('atividade_parlamentar_votacoes')
    op.drop_table('atividade_parlamentar_publicacoes')
    op.drop_table('atividade_parlamentar_eleitos')
    op.drop_table('atividade_parlamentar_convidados')
    op.drop_table('relatorio_parlamentar')
    op.drop_table('registo_interesses')
    op.drop_table('peticoes_detalhadas')
    op.drop_table('perguntas_requerimentos')
    op.drop_table('intervencao_parlamentar')
    op.drop_table('iniciativas_detalhadas')
    op.drop_table('diplomas_aprovados')
    op.drop_table('dep_cargos')
    op.drop_table('delegacao_permanente')
    op.drop_table('delegacao_eventual')
    op.drop_table('debate_parlamentar')
    op.drop_table('cooperacao_parlamentar')
    op.drop_table('atividade_parlamentar')
    # ### end Alembic commands ###
