"""Add ReunioesNacionais models for meetings and visits data

Revision ID: 2e58cc32ab2e
Revises: e713c0e844e1
Create Date: 2025-08-06 15:31:29.823709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e58cc32ab2e'
down_revision: Union[str, Sequence[str], None] = 'e713c0e844e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reunioes_nacionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reuniao_id', sa.Integer(), nullable=False, comment='Meeting registry identifier (XML: Id)'),
    sa.Column('nome', sa.Text(), nullable=True, comment='Meeting title (XML: Nome)'),
    sa.Column('tipo', sa.String(length=10), nullable=True, comment='Meeting type: RNI/RNN/VEE (XML: Tipo)'),
    sa.Column('local', sa.Text(), nullable=True, comment='Meeting location (XML: Local)'),
    sa.Column('legislatura_id', sa.Integer(), nullable=False, comment='Legislature identifier (XML: Legislatura)'),
    sa.Column('sessao', sa.Integer(), nullable=True, comment='Legislative session number (XML: Sessão)'),
    sa.Column('data_inicio', sa.Date(), nullable=True, comment='Meeting start date (XML: DataInicio)'),
    sa.Column('data_fim', sa.Date(), nullable=True, comment='Meeting end date (XML: DataFim)'),
    sa.Column('promotor', sa.Text(), nullable=True, comment='Meeting organizer/promoter (XML: Promotor)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reuniao_id')
    )
    op.create_index('idx_reuniao_nacional_data', 'reunioes_nacionais', ['data_inicio'], unique=False)
    op.create_index('idx_reuniao_nacional_legislatura', 'reunioes_nacionais', ['legislatura_id'], unique=False)
    op.create_index('idx_reuniao_nacional_reuniao_id', 'reunioes_nacionais', ['reuniao_id'], unique=False)
    op.create_index('idx_reuniao_nacional_tipo', 'reunioes_nacionais', ['tipo'], unique=False)
    op.create_table('participantes_reunioes_nacionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reuniao_id', sa.Integer(), nullable=False, comment='Meeting foreign key reference'),
    sa.Column('tipo', sa.String(length=10), nullable=True, comment='Participant type: D=Deputado (XML: Tipo)'),
    sa.Column('nome', sa.String(length=200), nullable=True, comment='Deputy participant name (XML: Nome)'),
    sa.Column('grupo_parlamentar', sa.String(length=50), nullable=True, comment='Parliamentary group affiliation (XML: Gp)'),
    sa.Column('legislatura', sa.String(length=20), nullable=True, comment='Legislature identifier for deputy context (XML: Leg)'),
    sa.Column('deputado_id', sa.Integer(), nullable=True, comment='Deputy identifier (XML: Id)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reuniao_id'], ['reunioes_nacionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_participante_reuniao_nacional_deputado', 'participantes_reunioes_nacionais', ['deputado_id'], unique=False)
    op.create_index('idx_participante_reuniao_nacional_gp', 'participantes_reunioes_nacionais', ['grupo_parlamentar'], unique=False)
    op.create_index('idx_participante_reuniao_nacional_reuniao', 'participantes_reunioes_nacionais', ['reuniao_id'], unique=False)
    op.alter_column('deputado_atividades_orgaos', 'tipo_atividade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Activity type: actividadeCom (committee) or actividadeGT (working group)',
               existing_nullable=False)
    op.alter_column('deputado_atividades_orgaos', 'org_id',
               existing_type=mysql.INTEGER(),
               comment='Organ unique identifier (XML: orgId)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'org_sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Official organ acronym (XML: orgSigla)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'org_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Full organ name/description (XML: orgDes)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'leg_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Legislature designation: IA, IB, II, III, etc. (XML: legDes)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'tim_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Mandate period description (XML: timDes)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'tia_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Position type: Presidente, Vice-Presidente, Relator, Vogal, etc. (XML: tiaDes)',
               existing_nullable=True)
    op.drop_column('deputado_atividades_orgaos', 'cargo_des')
    op.alter_column('deputado_cargos_funcoes', 'fun_id',
               existing_type=mysql.INTEGER(),
               comment='Function unique identifier (XML: funId)',
               existing_nullable=True)
    op.alter_column('deputado_cargos_funcoes', 'fun_des',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Complete function/position description (XML: funDes)',
               existing_nullable=True)
    op.alter_column('deputado_cargos_funcoes', 'fun_ordem',
               existing_type=mysql.INTEGER(),
               comment='Display order for biographical presentation (XML: funOrdem)',
               existing_nullable=True)
    op.alter_column('deputado_cargos_funcoes', 'fun_antiga',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1),
               comment='S/N flag indicating if position is historical (XML: funAntiga)',
               existing_nullable=True)
    op.alter_column('deputado_condecoracoes', 'cod_id',
               existing_type=mysql.INTEGER(),
               comment='Decoration unique identifier (XML: codId)',
               existing_nullable=True)
    op.alter_column('deputado_condecoracoes', 'cod_des',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Complete decoration description (XML: codDes)',
               existing_nullable=True)
    op.alter_column('deputado_condecoracoes', 'cod_ordem',
               existing_type=mysql.INTEGER(),
               comment='Display order for biographical presentation (XML: codOrdem)',
               existing_nullable=True)
    op.alter_column('deputado_habilitacoes', 'hab_id',
               existing_type=mysql.INTEGER(),
               comment='Qualification unique identifier (XML: habId)',
               existing_nullable=True)
    op.alter_column('deputado_habilitacoes', 'hab_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='Complete qualification description (XML: habDes)',
               existing_nullable=True)
    op.alter_column('deputado_habilitacoes', 'hab_tipo_id',
               existing_type=mysql.INTEGER(),
               comment='Qualification type classification ID (XML: habTipoId)',
               existing_nullable=True)
    op.alter_column('deputado_habilitacoes', 'hab_estado',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Current status: completed/in progress/suspended (XML: habEstado)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'dep_nome_parlamentar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Parliamentary name used during mandate (XML: depNomeParlamentar)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'leg_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Legislature designation: IA, IB, II, III, etc. (XML: legDes)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'ce_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Electoral circle: Aveiro, Braga, Lisboa, Porto, etc. (XML: ceDes)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'par_sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='Political party acronym: PS, PSD, CDS, BE, etc. (XML: parSigla)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'par_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Full political party name (XML: parDes)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'gp_sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='Parliamentary group acronym - may differ from party (XML: gpSigla)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'gp_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Parliamentary group full name (XML: gpDes)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'ind_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Indication/appointment description for special cases (XML: indDes)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'url_video_biografia',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='Biography video URL if available (XML: urlVideoBiografia)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'ind_data',
               existing_type=sa.DATE(),
               comment='Indication/appointment date for special appointments (XML: indData)',
               existing_nullable=True)
    op.alter_column('deputado_obras_publicadas', 'pub_id',
               existing_type=mysql.INTEGER(),
               comment='Publication unique identifier (XML: pubId)',
               existing_nullable=True)
    op.alter_column('deputado_obras_publicadas', 'pub_des',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Complete publication description with bibliographic details (XML: pubDes)',
               existing_nullable=True)
    op.alter_column('deputado_obras_publicadas', 'pub_ordem',
               existing_type=mysql.INTEGER(),
               comment='Display order for biographical presentation (XML: pubOrdem)',
               existing_nullable=True)
    op.alter_column('deputado_titulos', 'tit_id',
               existing_type=mysql.INTEGER(),
               comment='Title unique identifier (XML: titId)',
               existing_nullable=True)
    op.alter_column('deputado_titulos', 'tit_des',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Complete title description (XML: titDes)',
               existing_nullable=True)
    op.alter_column('deputado_titulos', 'tit_ordem',
               existing_type=mysql.INTEGER(),
               comment='Display order for biographical presentation (XML: titOrdem)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'peticao_id',
               existing_type=mysql.INTEGER(),
               comment='Petition foreign key reference',
               existing_nullable=False)
    op.alter_column('peticoes_comissoes', 'legislatura',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Committee legislature (XML: legislatura)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'numero',
               existing_type=mysql.INTEGER(),
               comment='Committee number (XML: numero)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'id_comissao',
               existing_type=mysql.INTEGER(),
               comment='Committee identifier (XML: idComissao)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'nome',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Committee name (XML: nome)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'admissibilidade',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Admissibility status (XML: admissibilidade)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'data_admissibilidade',
               existing_type=sa.DATE(),
               comment='Admissibility decision date (XML: dataAdmissibilidade)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'data_envio_par',
               existing_type=sa.DATE(),
               comment='Date sent to Parliament (XML: dataEnvioPar)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'data_arquivo',
               existing_type=sa.DATE(),
               comment='Archive date (XML: dataArquivo)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'situacao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Current processing status (XML: situacao)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'data_reaberta',
               existing_type=sa.DATE(),
               comment='Reopening date (XML: dataReaberta)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'data_baixa_comissao',
               existing_type=sa.DATE(),
               comment='Committee discharge date (XML: dataBaixaComissao)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'transitada',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Transfer status (XML: transitada)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_id',
               existing_type=mysql.INTEGER(),
               comment='Petition identifier (XML: petId)',
               existing_nullable=False)
    op.alter_column('peticoes_detalhadas', 'pet_nr',
               existing_type=mysql.INTEGER(),
               comment='Petition number (XML: petNr)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_leg',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Legislature designation (XML: petLeg)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_sel',
               existing_type=mysql.INTEGER(),
               comment='Legislative session (XML: petSel)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_assunto',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Petition subject/topic (XML: petAssunto)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_situacao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Current status of petition (XML: petSituacao)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_nr_assinaturas',
               existing_type=mysql.INTEGER(),
               comment='Number of signatures (XML: petNrAssinaturas)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_data_entrada',
               existing_type=sa.DATE(),
               comment='Entry date (XML: petDataEntrada)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_atividade_id',
               existing_type=mysql.INTEGER(),
               comment='Associated activity identifier (XML: petActividadeId)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_autor',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Petition author/submitter (XML: petAutor)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'data_debate',
               existing_type=sa.DATE(),
               comment='Debate date (XML: dataDebate)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_obs',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Observations - IX Legislature (XML: petObs)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'iniciativas_conjuntas',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Joint initiatives - XIII Legislature (XML: iniciativasConjuntas)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'peticoes_associadas',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Associated petitions - XIII Legislature (XML: peticoesAssociadas)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_nr_assinaturas_inicial',
               existing_type=mysql.INTEGER(),
               comment='Initial signature count - XIII Legislature (XML: petNrAssinaturasInicial)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'iniciativas_originadas',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Originated initiatives - XIII Legislature (XML: iniciativasOriginadas)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'legislatura_id',
               existing_type=mysql.INTEGER(),
               comment='Legislature foreign key reference',
               existing_nullable=False)
    op.alter_column('peticoes_publicacoes', 'peticao_id',
               existing_type=mysql.INTEGER(),
               comment='Petition foreign key reference',
               existing_nullable=False)
    op.alter_column('peticoes_publicacoes', 'tipo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Publication category (PublicacaoPeticao or PublicacaoDebate)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_nr',
               existing_type=mysql.INTEGER(),
               comment='Publication number (XML: pubNr)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_tipo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Publication type description using TipodePublicacao (XML: pubTipo)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_tp',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Publication type code using TipodePublicacao enum (XML: pubTp)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_leg',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Publication legislature (XML: pubLeg)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_sl',
               existing_type=mysql.INTEGER(),
               comment='Publication legislative session (XML: pubSL)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_dt',
               existing_type=sa.DATE(),
               comment='Publication date (XML: pubdt)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pag',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Page numbers (XML: pag)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'id_pag',
               existing_type=mysql.INTEGER(),
               comment='Page identifier (XML: idPag)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'url_diario',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Parliamentary diary URL (XML: URLDiario)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'supl',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Supplement designation - IX Legislature (XML: supl)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pag_final_diario_supl',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Final supplement page - IX Legislature (XML: pagFinalDiarioSupl)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'obs',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Observations - XIV Legislature (XML: obs)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peticoes_publicacoes', 'obs',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Observations - XIV Legislature (XML: obs)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pag_final_diario_supl',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Final supplement page - IX Legislature (XML: pagFinalDiarioSupl)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'supl',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Supplement designation - IX Legislature (XML: supl)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'url_diario',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Parliamentary diary URL (XML: URLDiario)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'id_pag',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Page identifier (XML: idPag)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pag',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Page numbers (XML: pag)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_dt',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Publication date (XML: pubdt)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_sl',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Publication legislative session (XML: pubSL)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_leg',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Publication legislature (XML: pubLeg)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_tp',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Publication type code using TipodePublicacao enum (XML: pubTp)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_tipo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Publication type description using TipodePublicacao (XML: pubTipo)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'pub_nr',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Publication number (XML: pubNr)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'tipo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Publication category (PublicacaoPeticao or PublicacaoDebate)',
               existing_nullable=True)
    op.alter_column('peticoes_publicacoes', 'peticao_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Petition foreign key reference',
               existing_nullable=False)
    op.alter_column('peticoes_detalhadas', 'legislatura_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Legislature foreign key reference',
               existing_nullable=False)
    op.alter_column('peticoes_detalhadas', 'iniciativas_originadas',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Originated initiatives - XIII Legislature (XML: iniciativasOriginadas)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_nr_assinaturas_inicial',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Initial signature count - XIII Legislature (XML: petNrAssinaturasInicial)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'peticoes_associadas',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Associated petitions - XIII Legislature (XML: peticoesAssociadas)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'iniciativas_conjuntas',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Joint initiatives - XIII Legislature (XML: iniciativasConjuntas)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_obs',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Observations - IX Legislature (XML: petObs)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'data_debate',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Debate date (XML: dataDebate)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_autor',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Petition author/submitter (XML: petAutor)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_atividade_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Associated activity identifier (XML: petActividadeId)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_data_entrada',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Entry date (XML: petDataEntrada)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_nr_assinaturas',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Number of signatures (XML: petNrAssinaturas)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_situacao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Current status of petition (XML: petSituacao)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_assunto',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Petition subject/topic (XML: petAssunto)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_sel',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Legislative session (XML: petSel)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_leg',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Legislature designation (XML: petLeg)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_nr',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Petition number (XML: petNr)',
               existing_nullable=True)
    op.alter_column('peticoes_detalhadas', 'pet_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Petition identifier (XML: petId)',
               existing_nullable=False)
    op.alter_column('peticoes_comissoes', 'transitada',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Transfer status (XML: transitada)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'data_baixa_comissao',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Committee discharge date (XML: dataBaixaComissao)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'data_reaberta',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Reopening date (XML: dataReaberta)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'situacao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Current processing status (XML: situacao)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'data_arquivo',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Archive date (XML: dataArquivo)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'data_envio_par',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date sent to Parliament (XML: dataEnvioPar)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'data_admissibilidade',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Admissibility decision date (XML: dataAdmissibilidade)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'admissibilidade',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Admissibility status (XML: admissibilidade)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'nome',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Committee name (XML: nome)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'id_comissao',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Committee identifier (XML: idComissao)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'numero',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Committee number (XML: numero)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'legislatura',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Committee legislature (XML: legislatura)',
               existing_nullable=True)
    op.alter_column('peticoes_comissoes', 'peticao_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Petition foreign key reference',
               existing_nullable=False)
    op.alter_column('deputado_titulos', 'tit_ordem',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Display order for biographical presentation (XML: titOrdem)',
               existing_nullable=True)
    op.alter_column('deputado_titulos', 'tit_des',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Complete title description (XML: titDes)',
               existing_nullable=True)
    op.alter_column('deputado_titulos', 'tit_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Title unique identifier (XML: titId)',
               existing_nullable=True)
    op.alter_column('deputado_obras_publicadas', 'pub_ordem',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Display order for biographical presentation (XML: pubOrdem)',
               existing_nullable=True)
    op.alter_column('deputado_obras_publicadas', 'pub_des',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Complete publication description with bibliographic details (XML: pubDes)',
               existing_nullable=True)
    op.alter_column('deputado_obras_publicadas', 'pub_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Publication unique identifier (XML: pubId)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'ind_data',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Indication/appointment date for special appointments (XML: indData)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'url_video_biografia',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='Biography video URL if available (XML: urlVideoBiografia)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'ind_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Indication/appointment description for special cases (XML: indDes)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'gp_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Parliamentary group full name (XML: gpDes)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'gp_sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='Parliamentary group acronym - may differ from party (XML: gpSigla)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'par_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Full political party name (XML: parDes)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'par_sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='Political party acronym: PS, PSD, CDS, BE, etc. (XML: parSigla)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'ce_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Electoral circle: Aveiro, Braga, Lisboa, Porto, etc. (XML: ceDes)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'leg_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Legislature designation: IA, IB, II, III, etc. (XML: legDes)',
               existing_nullable=True)
    op.alter_column('deputado_mandatos_legislativos', 'dep_nome_parlamentar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Parliamentary name used during mandate (XML: depNomeParlamentar)',
               existing_nullable=True)
    op.alter_column('deputado_habilitacoes', 'hab_estado',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Current status: completed/in progress/suspended (XML: habEstado)',
               existing_nullable=True)
    op.alter_column('deputado_habilitacoes', 'hab_tipo_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Qualification type classification ID (XML: habTipoId)',
               existing_nullable=True)
    op.alter_column('deputado_habilitacoes', 'hab_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='Complete qualification description (XML: habDes)',
               existing_nullable=True)
    op.alter_column('deputado_habilitacoes', 'hab_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Qualification unique identifier (XML: habId)',
               existing_nullable=True)
    op.alter_column('deputado_condecoracoes', 'cod_ordem',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Display order for biographical presentation (XML: codOrdem)',
               existing_nullable=True)
    op.alter_column('deputado_condecoracoes', 'cod_des',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Complete decoration description (XML: codDes)',
               existing_nullable=True)
    op.alter_column('deputado_condecoracoes', 'cod_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Decoration unique identifier (XML: codId)',
               existing_nullable=True)
    op.alter_column('deputado_cargos_funcoes', 'fun_antiga',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1),
               comment=None,
               existing_comment='S/N flag indicating if position is historical (XML: funAntiga)',
               existing_nullable=True)
    op.alter_column('deputado_cargos_funcoes', 'fun_ordem',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Display order for biographical presentation (XML: funOrdem)',
               existing_nullable=True)
    op.alter_column('deputado_cargos_funcoes', 'fun_des',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Complete function/position description (XML: funDes)',
               existing_nullable=True)
    op.alter_column('deputado_cargos_funcoes', 'fun_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Function unique identifier (XML: funId)',
               existing_nullable=True)
    op.add_column('deputado_atividades_orgaos', sa.Column('cargo_des', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.alter_column('deputado_atividades_orgaos', 'tia_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Position type: Presidente, Vice-Presidente, Relator, Vogal, etc. (XML: tiaDes)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'tim_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Mandate period description (XML: timDes)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'leg_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Legislature designation: IA, IB, II, III, etc. (XML: legDes)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'org_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Full organ name/description (XML: orgDes)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'org_sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Official organ acronym (XML: orgSigla)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'org_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Organ unique identifier (XML: orgId)',
               existing_nullable=True)
    op.alter_column('deputado_atividades_orgaos', 'tipo_atividade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Activity type: actividadeCom (committee) or actividadeGT (working group)',
               existing_nullable=False)
    op.drop_index('idx_participante_reuniao_nacional_reuniao', table_name='participantes_reunioes_nacionais')
    op.drop_index('idx_participante_reuniao_nacional_gp', table_name='participantes_reunioes_nacionais')
    op.drop_index('idx_participante_reuniao_nacional_deputado', table_name='participantes_reunioes_nacionais')
    op.drop_table('participantes_reunioes_nacionais')
    op.drop_index('idx_reuniao_nacional_tipo', table_name='reunioes_nacionais')
    op.drop_index('idx_reuniao_nacional_reuniao_id', table_name='reunioes_nacionais')
    op.drop_index('idx_reuniao_nacional_legislatura', table_name='reunioes_nacionais')
    op.drop_index('idx_reuniao_nacional_data', table_name='reunioes_nacionais')
    op.drop_table('reunioes_nacionais')
    # ### end Alembic commands ###
