"""add_navigation_context_field_to_import_status

Revision ID: 36c3f1a90419
Revises: e70c0600aa57
Create Date: 2025-08-12 17:39:21.542422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c3f1a90419'
down_revision: Union[str, Sequence[str], None] = 'e70c0600aa57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add navigation_context field to import_status table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_status', sa.Column('navigation_context', sa.String(length=1000), nullable=True, comment="Navigation hierarchy path for debugging (e.g., 'section > subsection > item')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove navigation_context field from import_status table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_status', 'navigation_context')
    # ### end Alembic commands ###
