"""Add final Atividades fields: autores_deputados, textos_aprovados, unanime, sessao

Revision ID: 3d5b16eac377
Revises: 8a58d041cc1c
Create Date: 2025-07-30 18:16:35.824121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5b16eac377'
down_revision: Union[str, Sequence[str], None] = '8a58d041cc1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividade_parlamentar', sa.Column('textos_aprovados', sa.Text(), nullable=True))
    op.add_column('atividade_parlamentar_votacoes', sa.Column('unanime', sa.Boolean(), nullable=True))
    op.add_column('debate_parlamentar', sa.Column('autores_deputados', sa.Text(), nullable=True))
    op.add_column('relatorio_parlamentar', sa.Column('sessao', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relatorio_parlamentar', 'sessao')
    op.drop_column('debate_parlamentar', 'autores_deputados')
    op.drop_column('atividade_parlamentar_votacoes', 'unanime')
    op.drop_column('atividade_parlamentar', 'textos_aprovados')
    # ### end Alembic commands ###
