"""Add event_source field to grupos_amizade_reunioes

Revision ID: 3e06c9ad4d9a
Revises: 76b92ab687cc
Create Date: 2025-08-13 11:02:47.542418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e06c9ad4d9a'
down_revision: Union[str, Sequence[str], None] = '76b92ab687cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupos_amizade_reunioes', sa.Column('event_source', sa.String(length=20), nullable=False, comment="Source XML structure: 'Reunioes' for meetings, 'Visitas' for visits"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grupos_amizade_reunioes', 'event_source')
    # ### end Alembic commands ###
