"""Add voting count fields to IniciativaEventoVotacao

Revision ID: 3ec4be30216e
Revises: 071faf27c613
Create Date: 2025-12-31 10:19:11.129093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec4be30216e'
down_revision: Union[str, Sequence[str], None] = '071faf27c613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iniciativas_eventos_votacoes', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column('iniciativas_eventos_votacoes', sa.Column('a_favor', sa.Integer(), nullable=True))
    op.add_column('iniciativas_eventos_votacoes', sa.Column('contra', sa.Integer(), nullable=True))
    op.add_column('iniciativas_eventos_votacoes', sa.Column('abstencao', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iniciativas_eventos_votacoes', 'abstencao')
    op.drop_column('iniciativas_eventos_votacoes', 'contra')
    op.drop_column('iniciativas_eventos_votacoes', 'a_favor')
    op.drop_column('iniciativas_eventos_votacoes', 'desc')
    # ### end Alembic commands ###
