"""Add final IX Legislature petition fields

Revision ID: 41c992b01b10
Revises: ee4b0dc73906
Create Date: 2025-08-04 06:00:14.964897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c992b01b10'
down_revision: Union[str, Sequence[str], None] = 'ee4b0dc73906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peticoes_pedidos_reiteracao', sa.Column('data_oficio', sa.Date(), nullable=True))
    op.add_column('peticoes_publicacoes', sa.Column('pag_final_diario_supl', sa.Text(), nullable=True))
    op.add_column('peticoes_relatores', sa.Column('motivo_cessacao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peticoes_relatores', 'motivo_cessacao')
    op.drop_column('peticoes_publicacoes', 'pag_final_diario_supl')
    op.drop_column('peticoes_pedidos_reiteracao', 'data_oficio')
    # ### end Alembic commands ###
