"""Add missing iniciativa models for annexes, video links, and subcommissions

Revision ID: 42c6c8d680f3
Revises: ba25e41bfa02
Create Date: 2025-08-01 07:23:54.760242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c6c8d680f3'
down_revision: Union[str, Sequence[str], None] = 'ba25e41bfa02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iniciativas_anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_id', sa.Integer(), nullable=False),
    sa.Column('anexo_id', sa.Integer(), nullable=True),
    sa.Column('anexo_nome', sa.Text(), nullable=True),
    sa.Column('anexo_fich', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_comissoes_distribuicao_subcomissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissao_id', sa.Integer(), nullable=False),
    sa.Column('subcomissao_id', sa.Integer(), nullable=True),
    sa.Column('sigla', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('data_distribuicao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_id'], ['iniciativas_eventos_comissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_eventos_comissoes_votacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissao_id', sa.Integer(), nullable=False),
    sa.Column('id_votacao', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('reuniao', sa.Integer(), nullable=True),
    sa.Column('tipo_reuniao', sa.Text(), nullable=True),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('unanime', sa.Text(), nullable=True),
    sa.Column('data_votacao', sa.Date(), nullable=True),
    sa.Column('ausencias', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_id'], ['iniciativas_eventos_comissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_oradores_video_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orador_id', sa.Integer(), nullable=False),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orador_id'], ['iniciativas_intervencoes_oradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iniciativas_oradores_video_links')
    op.drop_table('iniciativas_eventos_comissoes_votacoes')
    op.drop_table('iniciativas_comissoes_distribuicao_subcomissao')
    op.drop_table('iniciativas_anexos')
    # ### end Alembic commands ###
