"""Add org_id field to DeputadoAtividadeOrgao model

Revision ID: 438ea73cffb2
Revises: d25953578ab4
Create Date: 2025-07-31 16:11:26.804897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438ea73cffb2'
down_revision: Union[str, Sequence[str], None] = 'd25953578ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deputado_atividades_orgaos', sa.Column('org_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deputado_atividades_orgaos', 'org_id')
    # ### end Alembic commands ###
