"""Add XII Legislature voting fields to PeticaoRelatorioFinal

Revision ID: 45edfaf28e5c
Revises: 5416b0941906
Create Date: 2025-08-04 06:21:18.303082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45edfaf28e5c'
down_revision: Union[str, Sequence[str], None] = '5416b0941906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peticoes_relatorios_finais', sa.Column('votacao_id', sa.Integer(), nullable=True))
    op.add_column('peticoes_relatorios_finais', sa.Column('votacao_data', sa.Date(), nullable=True))
    op.add_column('peticoes_relatorios_finais', sa.Column('votacao_unanime', sa.Boolean(), nullable=True))
    op.add_column('peticoes_relatorios_finais', sa.Column('votacao_resultado', sa.Text(), nullable=True))
    op.add_column('peticoes_relatorios_finais', sa.Column('votacao_reuniao', sa.Integer(), nullable=True))
    op.add_column('peticoes_relatorios_finais', sa.Column('votacao_tipo_reuniao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peticoes_relatorios_finais', 'votacao_tipo_reuniao')
    op.drop_column('peticoes_relatorios_finais', 'votacao_reuniao')
    op.drop_column('peticoes_relatorios_finais', 'votacao_resultado')
    op.drop_column('peticoes_relatorios_finais', 'votacao_unanime')
    op.drop_column('peticoes_relatorios_finais', 'votacao_data')
    op.drop_column('peticoes_relatorios_finais', 'votacao_id')
    # ### end Alembic commands ###
