"""Add dep_nome_completo to work_group_historical_compositions for VIII Legislature

Revision ID: 48ee63157549
Revises: 8ab4a1649e90
Create Date: 2025-07-31 15:42:49.779817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ee63157549'
down_revision: Union[str, Sequence[str], None] = '8ab4a1649e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_group_historical_compositions', sa.Column('dep_nome_completo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_group_historical_compositions', 'dep_nome_completo')
    # ### end Alembic commands ###
