"""Increase act_tp field length in relatores_contas_publicas_out to 100 characters

Revision ID: 5370bbea5a62
Revises: 8f90430267a1
Create Date: 2025-07-31 22:08:12.069901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5370bbea5a62'
down_revision: Union[str, Sequence[str], None] = '8f90430267a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relatores_contas_publicas_out', 'act_tp',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relatores_contas_publicas_out', 'act_tp',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
