"""Add remaining XIII Legislature fields (PetNrAssinaturasInicial, Iniciativasoriginadas)

Revision ID: 5416b0941906
Revises: 9d859c3f07a7
Create Date: 2025-08-04 06:18:56.385243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5416b0941906'
down_revision: Union[str, Sequence[str], None] = '9d859c3f07a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peticoes_detalhadas', sa.Column('pet_nr_assinaturas_inicial', sa.Integer(), nullable=True))
    op.add_column('peticoes_detalhadas', sa.Column('iniciativas_originadas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peticoes_detalhadas', 'iniciativas_originadas')
    op.drop_column('peticoes_detalhadas', 'pet_nr_assinaturas_inicial')
    # ### end Alembic commands ###
