"""Add AtividadeDeputado models for deputy activity data

Revision ID: 5af86382bc79
Revises: 727985e4e93d
Create Date: 2025-07-30 16:06:49.879804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af86382bc79'
down_revision: Union[str, Sequence[str], None] = '727985e4e93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividade_deputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('dep_cad_id', sa.Integer(), nullable=True),
    sa.Column('leg_des', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade_deputado_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_deputado_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_deputado_id'], ['atividade_deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deputado_situacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_deputado_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_deputado_id'], ['atividade_deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividade_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_list_id', sa.Integer(), nullable=False),
    sa.Column('rel', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_list_id'], ['atividade_deputado_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dados_situacao_deputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_situacao_id', sa.Integer(), nullable=False),
    sa.Column('sio_des', sa.String(length=100), nullable=True),
    sa.Column('sio_dt_inicio', sa.Date(), nullable=True),
    sa.Column('sio_dt_fim', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_situacao_id'], ['deputado_situacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividade_audicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividade_audiencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dados_legis_deputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('dpl_grpar', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividades_comissao_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audiencia_id', sa.Integer(), nullable=True),
    sa.Column('audicao_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audicao_id'], ['actividade_audicoes.id'], ),
    sa.ForeignKeyConstraint(['audiencia_id'], ['actividade_audiencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades_comissao_outs')
    op.drop_table('dados_legis_deputados')
    op.drop_table('actividade_audiencias')
    op.drop_table('actividade_audicoes')
    op.drop_table('dados_situacao_deputados')
    op.drop_table('actividade_outs')
    op.drop_table('deputado_situacoes')
    op.drop_table('atividade_deputado_lists')
    op.drop_table('atividade_deputados')
    # ### end Alembic commands ###
