"""Add remaining IX Legislature fields and Comissoes models

Revision ID: 5b2f56184f57
Revises: 01894e9a83df
Create Date: 2025-07-31 07:19:25.755771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2f56184f57'
down_revision: Union[str, Sequence[str], None] = '01894e9a83df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comissoes_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissoes_id', sa.Integer(), nullable=False),
    sa.Column('cms_no', sa.String(length=500), nullable=True),
    sa.Column('cms_cd', sa.String(length=20), nullable=True),
    sa.Column('cms_lg', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comissoes_id'], ['comissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('delegacoes_eventuais_out', sa.Column('dev_dtfim', sa.String(length=50), nullable=True))
    op.add_column('delegacoes_eventuais_out', sa.Column('dev_sel_nr', sa.String(length=20), nullable=True))
    op.add_column('delegacoes_permanentes_out', sa.Column('cde_crg', sa.String(length=200), nullable=True))
    op.add_column('relatores_peticoes_out', sa.Column('pet_sel_lg_pk', sa.String(length=20), nullable=True))
    op.add_column('subcomissoes_grupos_trabalho_out', sa.Column('cms_cargo', sa.String(length=200), nullable=True))
    op.add_column('subcomissoes_grupos_trabalho_out', sa.Column('scm_com_lg', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcomissoes_grupos_trabalho_out', 'scm_com_lg')
    op.drop_column('subcomissoes_grupos_trabalho_out', 'cms_cargo')
    op.drop_column('relatores_peticoes_out', 'pet_sel_lg_pk')
    op.drop_column('delegacoes_permanentes_out', 'cde_crg')
    op.drop_column('delegacoes_eventuais_out', 'dev_sel_nr')
    op.drop_column('delegacoes_eventuais_out', 'dev_dtfim')
    op.drop_table('comissoes_out')
    op.drop_table('comissoes')
    # ### end Alembic commands ###
