"""Remove unused Deputy model tables and clean up schema

Revision ID: 5f1535c04191
Revises: 9560e4c684b5
Create Date: 2025-08-10 11:53:25.113047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f1535c04191'
down_revision: Union[str, Sequence[str], None] = '9560e4c684b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop unused Deputy model tables
    # Note: Indexes are automatically dropped when tables are dropped
    
    # Drop child tables first to avoid foreign key constraint issues
    op.drop_table('deputy_initiative_votes')
    op.drop_table('deputy_initiative_author_groups')
    op.drop_table('deputy_initiative_author_elected')
    op.drop_table('deputy_initiative_guests')
    op.drop_table('deputy_initiative_publications')
    
    op.drop_table('deputy_report_votes')
    op.drop_table('deputy_report_author_groups')
    op.drop_table('deputy_report_author_elected')
    op.drop_table('deputy_report_guests')
    op.drop_table('deputy_report_publications')
    
    op.drop_table('deputy_parliamentary_activity_votes')
    op.drop_table('deputy_parliamentary_activity_author_groups')
    op.drop_table('deputy_parliamentary_activity_author_elected')
    op.drop_table('deputy_parliamentary_activity_guests')
    op.drop_table('deputy_parliamentary_activity_publications')
    
    op.drop_table('deputy_legislative_data_votes')
    op.drop_table('deputy_legislative_data_author_groups')
    op.drop_table('deputy_legislative_data_author_elected')
    op.drop_table('deputy_legislative_data_guests')
    op.drop_table('deputy_legislative_data_publications')
    
    # Drop main tables
    op.drop_table('deputy_interventions')
    op.drop_table('deputy_reports')
    op.drop_table('deputy_parliamentary_activities')
    op.drop_table('deputy_legislative_data')
    op.drop_table('deputy_activities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deputy_legislative_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deputy_activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_dados', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numero', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('desc_tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('assunto', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('legislatura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('sessao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('data_entrada', sa.DATE(), nullable=True),
    sa.Column('data_agendamento_debate', sa.DATE(), nullable=True),
    sa.Column('orgao_exterior', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('observacoes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('tipo_autor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deputy_activity_id'], ['atividade_deputados.id'], name='deputy_legislative_data_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_deputy_legislative_data_data_entrada'), 'deputy_legislative_data', ['data_entrada'], unique=False)
    op.create_index(op.f('idx_deputy_legislative_data_activity'), 'deputy_legislative_data', ['deputy_activity_id'], unique=False)
    op.create_table('deputy_report_publications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pub_nr', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pub_tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pub_data', sa.DATE(), nullable=True),
    sa.Column('url_diario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('legislatura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['deputy_reports.id'], name=op.f('deputy_report_publications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_parliamentary_activities',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deputy_activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_atividade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numero', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('desc_tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('assunto', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('legislatura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('sessao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('data_entrada', sa.DATE(), nullable=True),
    sa.Column('data_agendamento_debate', sa.DATE(), nullable=True),
    sa.Column('orgao_exterior', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('observacoes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('tipo_autor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deputy_activity_id'], ['atividade_deputados.id'], name='deputy_parliamentary_activities_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_deputy_parliamentary_activities_data_entrada'), 'deputy_parliamentary_activities', ['data_entrada'], unique=False)
    op.create_index(op.f('idx_deputy_parliamentary_activities_activity'), 'deputy_parliamentary_activities', ['deputy_activity_id'], unique=False)
    op.create_table('deputy_reports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deputy_activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_relatorio', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numero', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('desc_tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('assunto', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('legislatura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('sessao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('data_entrada', sa.DATE(), nullable=True),
    sa.Column('data_agendamento_debate', sa.DATE(), nullable=True),
    sa.Column('orgao_exterior', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('observacoes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('tipo_autor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deputy_activity_id'], ['atividade_deputados.id'], name='deputy_reports_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_deputy_reports_data_entrada'), 'deputy_reports', ['data_entrada'], unique=False)
    op.create_index(op.f('idx_deputy_reports_activity'), 'deputy_reports', ['deputy_activity_id'], unique=False)
    op.create_table('deputy_initiative_publications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('initiative_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pub_nr', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pub_tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pub_data', sa.DATE(), nullable=True),
    sa.Column('url_diario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('legislatura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['deputy_initiatives.id'], name=op.f('deputy_initiative_publications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_initiative_guests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('initiative_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['deputy_initiatives.id'], name=op.f('deputy_initiative_guests_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_report_author_elected',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['deputy_reports.id'], name=op.f('deputy_report_author_elected_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_initiative_author_elected',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('initiative_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['deputy_initiatives.id'], name=op.f('deputy_initiative_author_elected_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_parliamentary_activity_author_groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['deputy_parliamentary_activities.id'], name=op.f('deputy_parliamentary_activity_author_groups_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_parliamentary_activity_guests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['deputy_parliamentary_activities.id'], name=op.f('deputy_parliamentary_activity_guests_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_legislative_data_votes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('legislative_data_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_votacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('resultado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('reuniao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('unanime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('data_votacao', sa.DATE(), nullable=True),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['legislative_data_id'], ['deputy_legislative_data.id'], name=op.f('deputy_legislative_data_votes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_parliamentary_activity_author_elected',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['deputy_parliamentary_activities.id'], name=op.f('deputy_parliamentary_activity_author_elected_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_report_votes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_votacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('resultado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('reuniao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('unanime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('data_votacao', sa.DATE(), nullable=True),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['deputy_reports.id'], name=op.f('deputy_report_votes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_legislative_data_author_elected',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('legislative_data_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['legislative_data_id'], ['deputy_legislative_data.id'], name=op.f('deputy_legislative_data_author_elected_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_legislative_data_publications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('legislative_data_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pub_nr', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pub_tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pub_data', sa.DATE(), nullable=True),
    sa.Column('url_diario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('legislatura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['legislative_data_id'], ['deputy_legislative_data.id'], name=op.f('deputy_legislative_data_publications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_parliamentary_activity_publications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pub_nr', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pub_tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pub_data', sa.DATE(), nullable=True),
    sa.Column('url_diario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('legislatura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['deputy_parliamentary_activities.id'], name=op.f('deputy_parliamentary_activity_publications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_parliamentary_activity_votes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_votacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('resultado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('reuniao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('unanime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('data_votacao', sa.DATE(), nullable=True),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['deputy_parliamentary_activities.id'], name=op.f('deputy_parliamentary_activity_votes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_initiative_author_groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('initiative_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['deputy_initiatives.id'], name=op.f('deputy_initiative_author_groups_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_legislative_data_guests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('legislative_data_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['legislative_data_id'], ['deputy_legislative_data.id'], name=op.f('deputy_legislative_data_guests_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_legislative_data_author_groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('legislative_data_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['legislative_data_id'], ['deputy_legislative_data.id'], name=op.f('deputy_legislative_data_author_groups_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_report_guests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['deputy_reports.id'], name=op.f('deputy_report_guests_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_activities',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cadastro', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('legislatura_sigla', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('nome_deputado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('partido_gp', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('xml_file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_deputy_activities_cadastro_leg'), 'deputy_activities', ['id_cadastro', 'legislatura_sigla'], unique=False)
    op.create_table('deputy_report_author_groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cargo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('honra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['deputy_reports.id'], name=op.f('deputy_report_author_groups_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_initiative_votes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('initiative_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_votacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('resultado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('reuniao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('unanime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('data_votacao', sa.DATE(), nullable=True),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['deputy_initiatives.id'], name=op.f('deputy_initiative_votes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deputy_interventions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deputy_activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_intervencao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('data_intervencao', sa.DATE(), nullable=True),
    sa.Column('qualidade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('sumario', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('resumo', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('fase_sessao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deputy_activity_id'], ['atividade_deputados.id'], name=op.f('deputy_interventions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_deputy_interventions_data'), 'deputy_interventions', ['data_intervencao'], unique=False)
    op.create_index(op.f('idx_deputy_interventions_activity'), 'deputy_interventions', ['deputy_activity_id'], unique=False)
    # ### end Alembic commands ###
