"""Add motivo_falta to meeting attendance and create deputy_videos table

Revision ID: 6220583b3805
Revises: dbd6622bf569
Create Date: 2025-07-31 18:19:38.262297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6220583b3805'
down_revision: Union[str, Sequence[str], None] = 'dbd6622bf569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deputy_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dep_id', sa.Integer(), nullable=True),
    sa.Column('dep_cad_id', sa.Integer(), nullable=True),
    sa.Column('dep_nome_parlamentar', sa.String(length=200), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('organ_type', sa.String(length=50), nullable=True),
    sa.Column('organ_id', sa.Integer(), nullable=True),
    sa.Column('legislatura_numero', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meeting_attendances', sa.Column('motivo_falta', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_attendances', 'motivo_falta')
    op.drop_table('deputy_videos')
    # ### end Alembic commands ###
