"""Add final 11 Atividades fields: supl, desc_tipo, tipo_autor, data_entrada for complete coverage

Revision ID: 62ad19cdf4d5
Revises: 3d5b16eac377
Create Date: 2025-07-30 18:23:53.218180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ad19cdf4d5'
down_revision: Union[str, Sequence[str], None] = '3d5b16eac377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividade_parlamentar_publicacoes', sa.Column('supl', sa.String(length=100), nullable=True))
    op.add_column('debate_parlamentar', sa.Column('tipo_autor', sa.String(length=100), nullable=True))
    op.add_column('debate_parlamentar', sa.Column('data_entrada', sa.Date(), nullable=True))
    op.add_column('debate_parlamentar_publicacoes', sa.Column('supl', sa.String(length=100), nullable=True))
    op.add_column('relatorio_parlamentar', sa.Column('desc_tipo', sa.String(length=200), nullable=True))
    op.add_column('relatorio_parlamentar_publicacoes', sa.Column('supl', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relatorio_parlamentar_publicacoes', 'supl')
    op.drop_column('relatorio_parlamentar', 'desc_tipo')
    op.drop_column('debate_parlamentar_publicacoes', 'supl')
    op.drop_column('debate_parlamentar', 'data_entrada')
    op.drop_column('debate_parlamentar', 'tipo_autor')
    op.drop_column('atividade_parlamentar_publicacoes', 'supl')
    # ### end Alembic commands ###
