"""Remove ativo fields and add runtime calculation properties

Revision ID: 6447df62ed03
Revises: 2555414de1e6
Create Date: 2025-08-11 14:53:37.151687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6447df62ed03'
down_revision: Union[str, Sequence[str], None] = '2555414de1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove ativo fields that were manually deleted from models
    # These fields had poor data accuracy (2.5%) and are replaced by runtime calculation
    try:
        op.drop_column('deputados', 'ativo')
    except Exception:
        # Column may not exist if running on a fresh database
        pass
        
    try:
        op.drop_column('partidos', 'ativo')
    except Exception:
        # Column may not exist if running on a fresh database
        pass
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Re-add ativo fields if downgrading (though not recommended due to poor data accuracy)
    op.add_column('partidos', sa.Column('ativo', sa.Boolean(), nullable=True, default=True))
    op.add_column('deputados', sa.Column('ativo', sa.Boolean(), nullable=True, default=True))
    
    # ### end Alembic commands ###
