"""Add IniciativaEventoRecursoDeputado model

Revision ID: 664ba09dc0bd
Revises: 009360b81334
Create Date: 2025-08-01 08:23:20.623467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664ba09dc0bd'
down_revision: Union[str, Sequence[str], None] = '009360b81334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iniciativas_eventos_recursos_deputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('deputado_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['iniciativas_eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iniciativas_eventos_recursos_deputados')
    # ### end Alembic commands ###
