"""Add final diploma artigo fields for complete field coverage

Revision ID: 68c6c3d2f69e
Revises: c908dc1f7f15
Create Date: 2025-08-07 18:57:18.063934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c6c3d2f69e'
down_revision: Union[str, Sequence[str], None] = 'c908dc1f7f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamento_estado_diploma_artigos', sa.Column('diploma_artigo_subtitulo', sa.Text(), nullable=True, comment='Alternative Article subtitle (DiplomaArtigoSubTitulo)'))
    op.add_column('orcamento_estado_diploma_artigos', sa.Column('diploma_artigo_texto', sa.Text(), nullable=True, comment='Alternative Article text (DiplomaArtigoTexto)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamento_estado_diploma_artigos', 'diploma_artigo_texto')
    op.drop_column('orcamento_estado_diploma_artigos', 'diploma_artigo_subtitulo')
    # ### end Alembic commands ###
