"""Standardize text field types in new models

Revision ID: 6d4e12845f07
Revises: e356df8897b6
Create Date: 2025-08-04 07:04:26.989767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d4e12845f07'
down_revision: Union[str, Sequence[str], None] = 'e356df8897b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delegacao_permanente_comissao_membros', 'nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('delegacao_permanente_comissao_membros', 'cargo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('registo_interesses_atividades', 'rga_valor',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('registo_interesses_cargos', 'rgc_valor',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('registo_interesses_sociedades', 'rgs_valor',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registo_interesses_sociedades', 'rgs_valor',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.alter_column('registo_interesses_cargos', 'rgc_valor',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.alter_column('registo_interesses_atividades', 'rga_valor',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.alter_column('delegacao_permanente_comissao_membros', 'cargo',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.alter_column('delegacao_permanente_comissao_membros', 'nome',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
