"""Add nested OrcamentoEstado models for voting details, article structure, and diploma measures

Revision ID: 721a8d50a7e8
Revises: 68c6c3d2f69e
Create Date: 2025-08-08 08:26:06.145554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '721a8d50a7e8'
down_revision: Union[str, Sequence[str], None] = '68c6c3d2f69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento_estado_diploma_medidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=True, comment='Diploma measure title (Titulo)'),
    sa.Column('texto', sa.Text(), nullable=True, comment='Diploma measure text (Texto)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposta_id'], ['orcamento_estado_propostas_alteracao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_artigo_numeros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artigo_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True, comment='Number identifier (Numero)'),
    sa.Column('titulo', sa.Text(), nullable=True, comment='Number title (Titulo)'),
    sa.Column('texto', sa.Text(), nullable=True, comment='Number text content (Texto)'),
    sa.Column('estado', sa.String(length=100), nullable=True, comment='Number state (Estado)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artigo_id'], ['orcamento_estado_artigos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_diploma_medida_numeros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diploma_medida_id', sa.Integer(), nullable=False),
    sa.Column('designacao', sa.Text(), nullable=True, comment='Measure number designation (Designacao)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diploma_medida_id'], ['orcamento_estado_diploma_medidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_diplomas_terceiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votacao_id', sa.Integer(), nullable=False),
    sa.Column('diploma_referencia', sa.Text(), nullable=True, comment='Diploma reference (Diploma)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['votacao_id'], ['orcamento_estado_votacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_grupos_parlamentares_votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votacao_id', sa.Integer(), nullable=False),
    sa.Column('grupo_parlamentar', sa.String(length=200), nullable=True, comment='Parliamentary group name (GrupoParlamentar)'),
    sa.Column('voto', sa.String(length=50), nullable=True, comment='Vote result (Voto): Favor, Contra, Abstenção'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['votacao_id'], ['orcamento_estado_votacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_artigo_alineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_id', sa.Integer(), nullable=False),
    sa.Column('alinea', sa.String(length=50), nullable=True, comment='Alinea identifier (Alinea)'),
    sa.Column('titulo', sa.Text(), nullable=True, comment='Alinea title (Titulo)'),
    sa.Column('texto', sa.Text(), nullable=True, comment='Alinea text content (Texto)'),
    sa.Column('estado', sa.String(length=100), nullable=True, comment='Alinea state (Estado)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['numero_id'], ['orcamento_estado_artigo_numeros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orcamento_estado_votacoes', sa.Column('diplomas_terceiros_texto', sa.Text(), nullable=True))
    op.add_column('orcamento_estado_votacoes', sa.Column('grupos_parlamentares_texto', sa.Text(), nullable=True))
    op.drop_column('orcamento_estado_votacoes', 'grupos_parlamentares')
    op.drop_column('orcamento_estado_votacoes', 'diplomas_terceiros')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamento_estado_votacoes', sa.Column('diplomas_terceiros', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('orcamento_estado_votacoes', sa.Column('grupos_parlamentares', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_column('orcamento_estado_votacoes', 'grupos_parlamentares_texto')
    op.drop_column('orcamento_estado_votacoes', 'diplomas_terceiros_texto')
    op.drop_table('orcamento_estado_artigo_alineas')
    op.drop_table('orcamento_estado_grupos_parlamentares_votos')
    op.drop_table('orcamento_estado_diplomas_terceiros')
    op.drop_table('orcamento_estado_diploma_medida_numeros')
    op.drop_table('orcamento_estado_artigo_numeros')
    op.drop_table('orcamento_estado_diploma_medidas')
    # ### end Alembic commands ###
