"""Add remaining missing fields for IX Legislature coverage

Revision ID: 73b5ea4fe652
Revises: cd8901718c48
Create Date: 2025-07-31 07:29:12.585913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b5ea4fe652'
down_revision: Union[str, Sequence[str], None] = 'cd8901718c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delegacoes_eventuais_out', sa.Column('dev_id', sa.Integer(), nullable=True))
    op.add_column('delegacoes_eventuais_out', sa.Column('dev_no', sa.String(length=500), nullable=True))
    op.add_column('delegacoes_permanentes_out', sa.Column('dep_sel_lg', sa.String(length=20), nullable=True))
    op.add_column('grupos_parlamentares_amizade_out', sa.Column('gpl_id', sa.Integer(), nullable=True))
    op.add_column('grupos_parlamentares_amizade_out', sa.Column('gpl_no', sa.String(length=500), nullable=True))
    op.add_column('relatores_iniciativas_out', sa.Column('ini_id', sa.Integer(), nullable=True))
    op.add_column('relatores_peticoes_out', sa.Column('pet_aspet', sa.Text(), nullable=True))
    op.add_column('relatores_peticoes_out', sa.Column('pet_sel_nr_pk', sa.String(length=20), nullable=True))
    op.add_column('reunioes_delegacoes_permanentes', sa.Column('ren_ti', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reunioes_delegacoes_permanentes', 'ren_ti')
    op.drop_column('relatores_peticoes_out', 'pet_sel_nr_pk')
    op.drop_column('relatores_peticoes_out', 'pet_aspet')
    op.drop_column('relatores_iniciativas_out', 'ini_id')
    op.drop_column('grupos_parlamentares_amizade_out', 'gpl_no')
    op.drop_column('grupos_parlamentares_amizade_out', 'gpl_id')
    op.drop_column('delegacoes_permanentes_out', 'dep_sel_lg')
    op.drop_column('delegacoes_eventuais_out', 'dev_no')
    op.drop_column('delegacoes_eventuais_out', 'dev_id')
    # ### end Alembic commands ###
