"""Add comprehensive XIII Legislature models for reports, events, and commissions

Revision ID: 75a9d5ce7f64
Revises: 8cf3692eefa4
Create Date: 2025-07-30 21:52:19.033089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a9d5ce7f64'
down_revision: Union[str, Sequence[str], None] = '8cf3692eefa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deslocacoes_parlamentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('id_deslocacao', sa.Integer(), nullable=False),
    sa.Column('data_ini', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('designacao', sa.Text(), nullable=True),
    sa.Column('local_evento', sa.String(length=500), nullable=True),
    sa.Column('sessao_legislativa', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_deslocacao', 'legislatura_id', name='uq_deslocacao_parlamentar_id_leg')
    )
    op.create_index('idx_deslocacao_parlamentar_data_ini', 'deslocacoes_parlamentares', ['data_ini'], unique=False)
    op.create_index('idx_deslocacao_parlamentar_id_deslocacao', 'deslocacoes_parlamentares', ['id_deslocacao'], unique=False)
    op.create_index('idx_deslocacao_parlamentar_legislatura', 'deslocacoes_parlamentares', ['legislatura_id'], unique=False)
    op.create_table('eventos_parlamentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('designacao', sa.Text(), nullable=True),
    sa.Column('local_evento', sa.String(length=500), nullable=True),
    sa.Column('sessao_legislativa', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_evento', 'legislatura_id', name='uq_evento_parlamentar_id_leg')
    )
    op.create_index('idx_evento_parlamentar_data', 'eventos_parlamentares', ['data'], unique=False)
    op.create_index('idx_evento_parlamentar_id_evento', 'eventos_parlamentares', ['id_evento'], unique=False)
    op.create_index('idx_evento_parlamentar_legislatura', 'eventos_parlamentares', ['legislatura_id'], unique=False)
    op.create_table('relatorio_parlamentar_comissoes_opinioes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_parlamentar_id', sa.Integer(), nullable=False),
    sa.Column('comissao_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=500), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('sigla', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_parlamentar_id'], ['relatorio_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_parlamentar_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('data_documento', sa.Date(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=200), nullable=True),
    sa.Column('titulo_documento', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorio_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_parlamentar_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('data_documento', sa.Date(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=200), nullable=True),
    sa.Column('titulo_documento', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorio_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_parlamentar_comissao_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissao_opiniao_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('data_documento', sa.Date(), nullable=True),
    sa.Column('publicar_internet', sa.Boolean(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=200), nullable=True),
    sa.Column('titulo_documento', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_opiniao_id'], ['relatorio_parlamentar_comissoes_opinioes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_parlamentar_comissao_relatores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissao_opiniao_id', sa.Integer(), nullable=False),
    sa.Column('relator_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('gp', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_opiniao_id'], ['relatorio_parlamentar_comissoes_opinioes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('relatorio_parlamentar', sa.Column('data_parecer_utao', sa.Date(), nullable=True))
    op.add_column('relatorio_parlamentar', sa.Column('data_pedido_parecer', sa.Date(), nullable=True))
    op.add_column('relatorio_parlamentar', sa.Column('membros_governo', sa.Text(), nullable=True))
    op.add_column('relatorio_parlamentar', sa.Column('audicoes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relatorio_parlamentar', 'audicoes')
    op.drop_column('relatorio_parlamentar', 'membros_governo')
    op.drop_column('relatorio_parlamentar', 'data_pedido_parecer')
    op.drop_column('relatorio_parlamentar', 'data_parecer_utao')
    op.drop_table('relatorio_parlamentar_comissao_relatores')
    op.drop_table('relatorio_parlamentar_comissao_documentos')
    op.drop_table('relatorio_parlamentar_links')
    op.drop_table('relatorio_parlamentar_documentos')
    op.drop_table('relatorio_parlamentar_comissoes_opinioes')
    op.drop_index('idx_evento_parlamentar_legislatura', table_name='eventos_parlamentares')
    op.drop_index('idx_evento_parlamentar_id_evento', table_name='eventos_parlamentares')
    op.drop_index('idx_evento_parlamentar_data', table_name='eventos_parlamentares')
    op.drop_table('eventos_parlamentares')
    op.drop_index('idx_deslocacao_parlamentar_legislatura', table_name='deslocacoes_parlamentares')
    op.drop_index('idx_deslocacao_parlamentar_id_deslocacao', table_name='deslocacoes_parlamentares')
    op.drop_index('idx_deslocacao_parlamentar_data_ini', table_name='deslocacoes_parlamentares')
    op.drop_table('deslocacoes_parlamentares')
    # ### end Alembic commands ###
