"""Add numero2 field to diplomas_aprovados

Revision ID: 783a73825133
Revises: fb00d80a1596
Create Date: 2025-08-01 08:49:58.700174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783a73825133'
down_revision: Union[str, Sequence[str], None] = 'fb00d80a1596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diplomas_aprovados', sa.Column('numero2', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diplomas_aprovados', 'numero2')
    # ### end Alembic commands ###
