"""empty message

Revision ID: 790e508da3cf
Revises: b533b361f7cc
Create Date: 2025-12-30 14:23:24.086478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790e508da3cf'
down_revision: Union[str, Sequence[str], None] = 'b533b361f7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_atividade_dep_cad_id', 'atividade_deputados', ['dep_cad_id'], unique=False)
    op.create_index('idx_atividade_deputado_id', 'atividade_deputados', ['deputado_id'], unique=False)
    op.create_index('idx_atividade_deputado_leg_composite', 'atividade_deputados', ['deputado_id', 'leg_des'], unique=False)
    op.create_index('idx_atividade_leg_des', 'atividade_deputados', ['leg_des'], unique=False)
    op.create_index('idx_mandatos_deputado_id', 'deputado_mandatos_legislativos', ['deputado_id'], unique=False)
    op.create_index('idx_mandatos_leg_des', 'deputado_mandatos_legislativos', ['leg_des'], unique=False)
    op.create_index('idx_mandatos_legislatura_composite', 'deputado_mandatos_legislativos', ['deputado_id', 'leg_des'], unique=False)
    op.create_index('idx_mandatos_par_sigla', 'deputado_mandatos_legislativos', ['par_sigla'], unique=False)
    op.drop_index(op.f('idx_deputy_identity_name'), table_name='deputy_identity_mappings')
    op.drop_index(op.f('idx_new_cad_id'), table_name='deputy_identity_mappings')
    op.drop_index(op.f('idx_old_cad_id'), table_name='deputy_identity_mappings')
    op.create_index('idx_identity_mapping_deputy_name', 'deputy_identity_mappings', ['deputy_name'], unique=False)
    op.create_index('idx_identity_mapping_new_cad_id', 'deputy_identity_mappings', ['new_cad_id'], unique=False)
    op.create_index('idx_identity_mapping_old_cad_id', 'deputy_identity_mappings', ['old_cad_id'], unique=False)
    op.add_column('import_status', sa.Column('processing_duration_seconds', sa.Float(), nullable=True, comment='Time taken to process the file in seconds'))
    op.create_index('idx_eventos_codigo_fase', 'iniciativas_eventos', ['codigo_fase'], unique=False)
    op.create_index('idx_votacoes_data_votacao', 'iniciativas_eventos_votacoes', ['data_votacao'], unique=False)
    op.create_index('idx_votacoes_evento_id', 'iniciativas_eventos_votacoes', ['evento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_votacoes_evento_id', table_name='iniciativas_eventos_votacoes')
    op.drop_index('idx_votacoes_data_votacao', table_name='iniciativas_eventos_votacoes')
    op.drop_index('idx_eventos_codigo_fase', table_name='iniciativas_eventos')
    op.drop_column('import_status', 'processing_duration_seconds')
    op.drop_index('idx_identity_mapping_old_cad_id', table_name='deputy_identity_mappings')
    op.drop_index('idx_identity_mapping_new_cad_id', table_name='deputy_identity_mappings')
    op.drop_index('idx_identity_mapping_deputy_name', table_name='deputy_identity_mappings')
    op.create_index(op.f('idx_old_cad_id'), 'deputy_identity_mappings', ['old_cad_id'], unique=False)
    op.create_index(op.f('idx_new_cad_id'), 'deputy_identity_mappings', ['new_cad_id'], unique=False)
    op.create_index(op.f('idx_deputy_identity_name'), 'deputy_identity_mappings', ['deputy_name'], unique=False)
    op.drop_index('idx_mandatos_par_sigla', table_name='deputado_mandatos_legislativos')
    op.drop_index('idx_mandatos_legislatura_composite', table_name='deputado_mandatos_legislativos')
    op.drop_index('idx_mandatos_leg_des', table_name='deputado_mandatos_legislativos')
    op.drop_index('idx_mandatos_deputado_id', table_name='deputado_mandatos_legislativos')
    op.drop_index('idx_atividade_leg_des', table_name='atividade_deputados')
    op.drop_index('idx_atividade_deputado_leg_composite', table_name='atividade_deputados')
    op.drop_index('idx_atividade_deputado_id', table_name='atividade_deputados')
    op.drop_index('idx_atividade_dep_cad_id', table_name='atividade_deputados')
    # ### end Alembic commands ###
