"""add_descricao_to_audiencia

Revision ID: 7932db127bd9
Revises: d46268eb0d79
Create Date: 2026-01-02 09:16:04.802690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7932db127bd9'
down_revision: Union[str, Sequence[str], None] = 'd46268eb0d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iniciativas_comissoes_audiencias', sa.Column('descricao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iniciativas_comissoes_audiencias', 'descricao')
    # ### end Alembic commands ###
