"""Add missing I Legislature fields - mandate details and interest registry V2 fields

Revision ID: 7d401cd0f2da
Revises: d05d51845201
Create Date: 2025-07-31 11:49:07.630713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d401cd0f2da'
down_revision: Union[str, Sequence[str], None] = 'd05d51845201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deputado_mandatos_legislativos', sa.Column('ind_des', sa.String(length=200), nullable=True))
    op.add_column('deputado_mandatos_legislativos', sa.Column('url_video_biografia', sa.String(length=500), nullable=True))
    op.add_column('deputado_mandatos_legislativos', sa.Column('ind_data', sa.Date(), nullable=True))
    op.add_column('registo_interesses_v2', sa.Column('cad_nome_completo', sa.String(length=200), nullable=True))
    op.add_column('registo_interesses_v2', sa.Column('cad_actividade_profissional', sa.Text(), nullable=True))
    op.add_column('registo_interesses_v2', sa.Column('cad_estado_civil_des', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registo_interesses_v2', 'cad_estado_civil_des')
    op.drop_column('registo_interesses_v2', 'cad_actividade_profissional')
    op.drop_column('registo_interesses_v2', 'cad_nome_completo')
    op.drop_column('deputado_mandatos_legislativos', 'ind_data')
    op.drop_column('deputado_mandatos_legislativos', 'url_video_biografia')
    op.drop_column('deputado_mandatos_legislativos', 'ind_des')
    # ### end Alembic commands ###
