"""Add comprehensive OrcamentoEstado models for State Budget data processing

Revision ID: 87b9b0594fbd
Revises: 6b8b19a8fcf9
Create Date: 2025-08-06 13:07:04.927465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87b9b0594fbd'
down_revision: Union[str, Sequence[str], None] = '6b8b19a8fcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('grupos_amizade_standalone',  # Commented out - table already created by previous migration
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('group_id', sa.Integer(), nullable=False),
    # sa.Column('nome', sa.String(length=500), nullable=False),
    # sa.Column('legislatura', sa.String(length=10), nullable=False),
    # sa.Column('sessao', sa.Integer(), nullable=True),
    # sa.Column('data_criacao', sa.DateTime(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_grupos_amizade_standalone_group_id'), 'grupos_amizade_standalone', ['group_id'], unique=False)  # Commented out - index already created
    # op.create_index(op.f('ix_grupos_amizade_standalone_legislatura'), 'grupos_amizade_standalone', ['legislatura'], unique=False)  # Commented out - index already created
    # op.create_table('grupos_amizade_membros',  # Commented out - table already created by previous migration
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('grupo_amizade_id', sa.Integer(), nullable=False),
    # sa.Column('nome', sa.String(length=500), nullable=False),
    # sa.Column('grupo_parlamentar', sa.String(length=200), nullable=True),
    # sa.Column('cargo', sa.String(length=100), nullable=True),
    # sa.Column('data_inicio', sa.DateTime(), nullable=True),
    # sa.Column('data_fim', sa.DateTime(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['grupo_amizade_id'], ['grupos_amizade_standalone.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('grupos_amizade_reunioes',  # Commented out - table already created by previous migration
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('grupo_amizade_id', sa.Integer(), nullable=False),
    # sa.Column('meeting_id', sa.Integer(), nullable=False),
    # sa.Column('nome', sa.Text(), nullable=False),
    # sa.Column('tipo', sa.String(length=200), nullable=True),
    # sa.Column('local', sa.String(length=500), nullable=True),
    # sa.Column('data_inicio', sa.DateTime(), nullable=False),
    # sa.Column('data_fim', sa.DateTime(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['grupo_amizade_id'], ['grupos_amizade_standalone.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_grupos_amizade_reunioes_meeting_id'), 'grupos_amizade_reunioes', ['meeting_id'], unique=False)  # Commented out - index already created
    op.create_table('orcamento_estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('format_type', sa.String(length=10), nullable=False),
    sa.Column('numero_orcamento', sa.String(length=20), nullable=True),
    sa.Column('tipo_arquivo', sa.String(length=10), nullable=True),
    sa.Column('total_propostas', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('data_processamento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('grupos_amizade_participantes',  # Commented out - table already created by previous migration
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('reuniao_id', sa.Integer(), nullable=False),
    # sa.Column('participant_id', sa.Integer(), nullable=False),
    # sa.Column('nome', sa.String(length=500), nullable=False),
    # sa.Column('tipo', sa.String(length=10), nullable=False),
    # sa.Column('grupo_parlamentar', sa.String(length=200), nullable=True),
    # sa.Column('legislatura', sa.String(length=10), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['reuniao_id'], ['grupos_amizade_reunioes.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_grupos_amizade_participantes_participant_id'), 'grupos_amizade_participantes', ['participant_id'], unique=False)  # Commented out - index already created
    op.create_table('orcamento_estado_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('id_pai', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('tipo_desc', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('estado_desc', sa.String(length=200), nullable=True),
    sa.Column('format_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento_estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oe_item_id', 'orcamento_estado_items', ['item_id'], unique=False)
    op.create_index('idx_oe_item_legislatura', 'orcamento_estado_items', ['legislatura_id'], unique=False)
    op.create_index('idx_oe_item_pai', 'orcamento_estado_items', ['id_pai'], unique=False)
    op.create_index('idx_oe_item_tipo', 'orcamento_estado_items', ['tipo'], unique=False)
    op.create_index(op.f('ix_orcamento_estado_items_item_id'), 'orcamento_estado_items', ['item_id'], unique=False)
    op.create_table('orcamento_estado_propostas_alteracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('data_proposta', sa.Date(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('tema', sa.Text(), nullable=True),
    sa.Column('apresentada', sa.String(length=200), nullable=True),
    sa.Column('incide', sa.String(length=50), nullable=True),
    sa.Column('incide_desc', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('tipo_desc', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('estado_desc', sa.String(length=200), nullable=True),
    sa.Column('numero_artigo_novo', sa.String(length=50), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('ficheiro_url', sa.String(length=500), nullable=True),
    sa.Column('grupo_parlamentar', sa.String(length=200), nullable=True),
    sa.Column('id_pai', sa.Integer(), nullable=True),
    sa.Column('apresentado', sa.String(length=200), nullable=True),
    sa.Column('format_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento_estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oe_proposta_format', 'orcamento_estado_propostas_alteracao', ['format_type'], unique=False)
    op.create_index('idx_oe_proposta_id', 'orcamento_estado_propostas_alteracao', ['proposta_id'], unique=False)
    op.create_index('idx_oe_proposta_legislatura', 'orcamento_estado_propostas_alteracao', ['legislatura_id'], unique=False)
    op.create_index(op.f('ix_orcamento_estado_propostas_alteracao_proposta_id'), 'orcamento_estado_propostas_alteracao', ['proposta_id'], unique=False)
    op.create_table('orcamento_estado_artigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('artigo_id', sa.Integer(), nullable=True),
    sa.Column('id_pai', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('estado_desc', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['orcamento_estado_items.id'], ),
    sa.ForeignKeyConstraint(['proposta_id'], ['orcamento_estado_propostas_alteracao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_diplomas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('diploma_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('sub_titulo', sa.Text(), nullable=True),
    sa.Column('artigos_texto', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['orcamento_estado_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_iniciativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('estado_desc', sa.String(length=200), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['orcamento_estado_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_proponentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=False),
    sa.Column('grupo_parlamentar', sa.String(length=200), nullable=True),
    sa.Column('deputado_nome', sa.String(length=200), nullable=True),
    sa.Column('tipo_proponente', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposta_id'], ['orcamento_estado_propostas_alteracao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_estado_votacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('data_votacao', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sub_descricao', sa.Text(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('diplomas_terceiros', sa.Text(), nullable=True),
    sa.Column('grupos_parlamentares', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['orcamento_estado_items.id'], ),
    sa.ForeignKeyConstraint(['proposta_id'], ['orcamento_estado_propostas_alteracao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('registo_interesses_social_positions_unified',  # Commented out - table already created by previous migration
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('registo_id', sa.Integer(), nullable=False),
    # sa.Column('position', sa.String(length=500), nullable=True),
    # sa.Column('entity', sa.String(length=500), nullable=True),
    # sa.Column('activity_area', sa.String(length=500), nullable=True),
    # sa.Column('headquarters_location', sa.String(length=500), nullable=True),
    # sa.Column('type_classification', sa.Integer(), nullable=True),
    # sa.Column('social_participation', sa.Text(), nullable=True),
    # sa.Column('value', sa.String(length=200), nullable=True),
    # sa.Column('observations', sa.Text(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['registo_id'], ['registo_interesses_unified.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.alter_column('actividade_audicoes', 'actividade_out_id',
               existing_type=mysql.INTEGER(),
               comment='Reference to general activity record',
               existing_nullable=False)
    op.alter_column('actividade_audiencias', 'actividade_out_id',
               existing_type=mysql.INTEGER(),
               comment='Reference to general activity record',
               existing_nullable=False)
    # op.add_column('agenda_parlamentar', sa.Column('order_value', sa.Integer(), nullable=True, comment='Meeting/event order number (OrderValue) - sequence within agenda'))  # Commented out - column already added by previous migration
    # op.add_column('agenda_parlamentar', sa.Column('legislatura_designacao', sa.Text(), nullable=True, comment='Legislature reference (LegDes) - which legislature event belongs to'))  # Commented out - column already added by previous migration
    # op.add_column('agenda_parlamentar', sa.Column('orgao_designacao', sa.Text(), nullable=True, comment='Organ reference (OrgDes) - which organ event belongs to'))  # Commented out - column already added by previous migration
    # op.add_column('agenda_parlamentar', sa.Column('reuniao_numero', sa.Integer(), nullable=True, comment='Meeting number (ReuNumero) - sequential meeting identifier'))  # Commented out - column already added by previous migration
    # op.add_column('agenda_parlamentar', sa.Column('sessao_numero', sa.Integer(), nullable=True, comment='Legislative session number (SelNumero) - session reference'))  # Commented out - column already added by previous migration
    op.alter_column('agenda_parlamentar', 'id_externo',
               existing_type=mysql.INTEGER(),
               comment='Unique meeting/event identifier (Id) - external system ID',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'secao_id',
               existing_type=mysql.INTEGER(),
               comment='Section unique identifier (SectionId) - requires SectionType translator',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'secao_nome',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Section description (Section) - derived from SectionType enum',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'tema_id',
               existing_type=mysql.INTEGER(),
               comment='Theme unique identifier (ThemeId) - requires ThemeType translator',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'tema_nome',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Theme description (Theme) - derived from ThemeType enum',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'grupo_parlamentar',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Parliamentary group ID (ParlamentGroup) - when associated with event',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'data_evento',
               existing_type=sa.DATE(),
               comment='Event start date (EventStartDate) - when event occurs',
               existing_nullable=False)
    op.alter_column('agenda_parlamentar', 'hora_inicio',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Event start time (EventStartTime) - local time format',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'hora_fim',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Event end time (EventEndTime) - local time format',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'evento_dia_inteiro',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Full day event indicator (AllDayEvent) - true if all day',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'titulo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Event title (Title) - main event name',
               existing_nullable=False)
    op.alter_column('agenda_parlamentar', 'subtitulo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Event subtitle (Subtitle) - additional event description',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'descricao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='HTML encoded descriptive text (InternetText) - detailed event information',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'local_evento',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Event location (Local) - where the event takes place',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'link_externo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Parliament website link (Link) - URL to event page if exists',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'pos_plenario',
               existing_type=mysql.TINYINT(display_width=1),
               comment='After plenary session indicator (PostPlenary) - occurs after plenary',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar_anexos', 'id_field',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Document unique identifier (idField) - external document ID',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar_anexos', 'tipo_documento_field',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Document type (tipoDocumentoField) - classification of document',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar_anexos', 'titulo_field',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Document title (tituloField) - descriptive name of document',
               existing_nullable=False)
    op.alter_column('agenda_parlamentar_anexos', 'url_field',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Parliament website document link (uRLField) - URL to access document',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar_anexos', 'tipo_anexo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment="Attachment type - 'comissao_permanente' or 'plenario' based on parent structure",
               existing_nullable=True)
    # MySQL requires key length for TEXT columns in indexes
    # op.create_index('idx_agenda_anexo_tipo', 'agenda_parlamentar_anexos', ['tipo_anexo'], unique=False)
    op.alter_column('atividade_deputado_lists', 'atividade_deputado_id',
               existing_type=mysql.INTEGER(),
               comment='Reference to parent AtividadeDeputado record',
               existing_nullable=False)
    op.alter_column('atividade_deputado_lists', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Record creation timestamp',
               existing_nullable=True)
    op.alter_column('atividade_deputados', 'deputado_id',
               existing_type=mysql.INTEGER(),
               comment='Reference to the deputy this activity record belongs to',
               existing_nullable=False)
    op.alter_column('atividade_deputados', 'dep_cad_id',
               existing_type=mysql.INTEGER(),
               comment="Deputy's cadastral identifier (DepCadId) - unique registry ID",
               existing_nullable=True)
    op.alter_column('atividade_deputados', 'leg_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='Legislature designation (LegDes) - which legislature this activity pertains to',
               existing_nullable=True)
    op.alter_column('atividade_deputados', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Record creation timestamp',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'atividade_id',
               existing_type=mysql.INTEGER(),
               comment='Activity identifier (IDAtividade) - unique registry ID',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Activity type code (Tipo) - requires TipodeAtividade translator',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'desc_tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Activity type description (DescTipo) - official classification name',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'assunto',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Activity subject matter (Assunto) - descriptive text of activity topic',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'numero',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Activity number (Numero) - sequential or reference number',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'data_atividade',
               existing_type=sa.DATE(),
               comment='Activity date (Data) - when the activity took place',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'data_entrada',
               existing_type=sa.DATE(),
               comment='Entry date (DataEntrada) - when activity was registered in system',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'data_agendamento_debate',
               existing_type=sa.DATE(),
               comment='Scheduled debate date (DataAgendamentoDebate) - planned discussion date',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'tipo_autor',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Author type (TipoAutor) - requires TipodeAutor translator for classification',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'autores_gp',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Group authors (AutoresGP) - parliamentary groups authoring the activity',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'outros_subscritores',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Other subscribers (OutrosSubscritores) - additional supporters or co-authors',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'textos_aprovados',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Approved texts (TextosAprovados) - texts that were approved during activity',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'resultado_votacao_pontos',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Voting results by points (ResultadoVotacaoPontos) - detailed voting outcomes',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'observacoes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='General observations (Observacoes) - additional notes and comments',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'id_audiencia',
               existing_type=mysql.INTEGER(),
               comment='Audience identifier (IDAudiencia) - unique audience registry ID',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'numero_audiencia',
               existing_type=mysql.INTEGER(),
               comment='Audience number (NumeroAudiencia) - sequential numbering within session',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'sessao_legislativa',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Legislative session (SessaoLegislativa) - session when audience occurred',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'assunto',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Audience subject (Assunto) - topic or matter being discussed',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'data_audiencia',
               existing_type=sa.DATE(),
               comment='Audience date (Data) - when the audience took place',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'data',
               existing_type=sa.DATE(),
               comment='Alternative date field (Data) - additional date reference',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'comissao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Committee (Comissao) - committee conducting the audience',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'concedida',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Granted status (Concedida) - whether the audience request was approved',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'tipo_audiencia',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Audience type (TipoAudiencia) - classification of audience format',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'entidades',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Participating entities (Entidades) - organizations or individuals presenting',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'observacoes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Observations (Observacoes) - additional notes and remarks',
               existing_nullable=True)
    op.alter_column('circulos_eleitorais', 'designacao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Electoral circle name (XML: cpDes)',
               existing_nullable=False)
    op.alter_column('circulos_eleitorais', 'codigo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='Electoral circle code (XML: cpId)',
               existing_nullable=True)
    op.alter_column('dados_situacao_deputados', 'sio_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Situation description (XML: sioDes)',
               existing_nullable=True)
    op.alter_column('dados_situacao_deputados', 'sio_dt_inicio',
               existing_type=sa.DATE(),
               comment='Situation start date (XML: sioDtInicio)',
               existing_nullable=True)
    op.alter_column('dados_situacao_deputados', 'sio_dt_fim',
               existing_type=sa.DATE(),
               comment='Situation end date (XML: sioDtFim)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente', 'legislatura_id',
               existing_type=mysql.INTEGER(),
               comment='Legislature identifier (Legislatura)',
               existing_nullable=False)
    op.alter_column('delegacao_permanente', 'delegacao_id',
               existing_type=mysql.INTEGER(),
               comment='Delegation record identifier (Id)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente', 'nome',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Permanent delegation name (Nome)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente', 'sessao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Legislative session number (Sessão)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente', 'data_eleicao',
               existing_type=sa.DATE(),
               comment='Delegation election date (DataEleicao)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_comissoes', 'nome',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Commission name (Nome)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_comissoes', 'composicao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Commission composition details (Composição)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_comissoes', 'subcomissoes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Subcommissions data (Subcomissoes)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'membro_id',
               existing_type=mysql.INTEGER(),
               comment='Deputy identifier (Id)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Deputy participant name (Nome)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'cargo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Position held by deputy (Cargo)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'gp',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Parliamentary group (Gp)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'data_inicio',
               existing_type=sa.DATE(),
               comment='Start date of functions (DataInicio)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'data_fim',
               existing_type=sa.DATE(),
               comment='End date of functions (DataFim)',
               existing_nullable=True)
    op.alter_column('deputados', 'id',
               existing_type=mysql.INTEGER(),
               comment='Legislature-specific deputy ID (XML: DepId)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('deputados', 'id_cadastro',
               existing_type=mysql.INTEGER(),
               comment="Person's unique registration ID across all legislatures (XML: DepCadId)",
               existing_nullable=False)
    op.alter_column('deputados', 'nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Parliamentary name - shortened version (XML: DepNomeParlamentar)',
               existing_nullable=False)
    op.alter_column('deputados', 'nome_completo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               comment='Full deputy name (XML: DepNomeCompleto)',
               existing_nullable=True)
    op.drop_index(op.f('idx_deputados_active_lookup'), table_name='deputados')
    op.drop_index(op.f('idx_deputados_biographical'), table_name='deputados')
    op.drop_index(op.f('idx_deputados_legislatura'), table_name='deputados')
    op.alter_column('deputy_gp_situations', 'gp_id',
               existing_type=mysql.INTEGER(),
               comment='Parliamentary group ID (XML: gpId)',
               existing_nullable=True)
    op.alter_column('deputy_gp_situations', 'gp_sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='Parliamentary group acronym (XML: gpSigla)',
               existing_nullable=True)
    op.alter_column('deputy_gp_situations', 'gp_dt_inicio',
               existing_type=sa.DATE(),
               comment='GP membership start date (XML: gpDtInicio)',
               existing_nullable=True)
    op.alter_column('deputy_gp_situations', 'gp_dt_fim',
               existing_type=sa.DATE(),
               comment='GP membership end date (XML: gpDtFim)',
               existing_nullable=True)
    op.alter_column('deslocacoes_parlamentares', 'id_deslocacao',
               existing_type=mysql.INTEGER(),
               comment='Displacement identifier (IDDeslocacao) - unique displacement registry ID',
               existing_nullable=False)
    op.alter_column('deslocacoes_parlamentares', 'data_ini',
               existing_type=sa.DATE(),
               comment='Start date (DataIni) - when displacement begins',
               existing_nullable=True)
    op.alter_column('deslocacoes_parlamentares', 'data_fim',
               existing_type=sa.DATE(),
               comment='End date (DataFim) - when displacement ends',
               existing_nullable=True)
    op.alter_column('deslocacoes_parlamentares', 'designacao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Displacement designation (Designacao) - official purpose or destination description',
               existing_nullable=True)
    op.alter_column('eventos_parlamentares', 'id_evento',
               existing_type=mysql.INTEGER(),
               comment='Event identifier (IDEvento) - unique event registry ID',
               existing_nullable=False)
    op.alter_column('eventos_parlamentares', 'data',
               existing_type=sa.DATE(),
               comment='Event date (Data) - when the event took place',
               existing_nullable=True)
    op.alter_column('eventos_parlamentares', 'designacao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Event designation (Designacao) - official title or name of event',
               existing_nullable=True)
    op.alter_column('eventos_parlamentares', 'local_evento',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='Event location (LocalEvento) - where the event was held',
               existing_nullable=True)
    op.alter_column('eventos_parlamentares', 'sessao_legislativa',
               existing_type=mysql.INTEGER(),
               comment='Legislative session (SessaoLegislativa) - session number when event occurred',
               existing_nullable=True)
    op.alter_column('eventos_parlamentares', 'tipo_evento',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Event type (TipoEvento) - requires TipodeEvento translator for classification',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_id',
               existing_type=mysql.INTEGER(),
               comment='Identificador da Iniciativa (XML: iniId)',
               existing_nullable=False)
    op.alter_column('iniciativas_detalhadas', 'ini_nr',
               existing_type=mysql.INTEGER(),
               comment='Número da Iniciativa (XML: iniNr)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_tipo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Tipo de Iniciativa - código (XML: iniTipo)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_desc_tipo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Descrição do Tipo de Iniciativa (XML: iniDescTipo)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_leg',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Legislatura da iniciativa (XML: iniLeg)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_sel',
               existing_type=mysql.INTEGER(),
               comment='Sessão legislativa da iniciativa (XML: iniSel)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'data_inicio_leg',
               existing_type=sa.DATE(),
               comment='Data de Inicio da Legislatura (XML: dataInicioleg)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'data_fim_leg',
               existing_type=sa.DATE(),
               comment='Data de Fim da Legislatura (XML: dataFimleg)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_titulo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Titulo da Iniciativa (XML: iniTitulo)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_texto_subst',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Indica se tem texto de substituição (XML: iniTextoSubst)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_texto_subst_campo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Observações sobre substituição do ficheiro (XML: iniTextoSubstCampo)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_link_texto',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Link para o texto da iniciativa (XML: iniLinkTexto)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_obs',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Observações associadas (XML: iniObs)',
               existing_nullable=True)
    op.drop_index(op.f('idx_iniciativas_data_periodo'), table_name='iniciativas_detalhadas')
    op.drop_index(op.f('idx_iniciativas_leg_periodo'), table_name='iniciativas_detalhadas', mysql_length={'ini_leg': 20})
    op.drop_index(op.f('idx_iniciativas_legislatura_tipo'), table_name='iniciativas_detalhadas', mysql_length={'ini_tipo': 100})
    op.drop_index(op.f('idx_iniciativas_number_leg'), table_name='iniciativas_detalhadas', mysql_length={'ini_leg': 20, 'ini_tipo': 100})
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_nr',
               existing_type=mysql.INTEGER(),
               comment='Número da Publicação (XML: pubNr)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_tipo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Descrição do Tipo de Publicação (XML: pubTipo)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_tp',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Abreviatura do Tipo de Publicação (XML: pubTp)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_leg',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Legislatura em que ocorreu a Publicação (XML: pubLeg)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_sl',
               existing_type=mysql.INTEGER(),
               comment='Sessão legislativa em que ocorreu a Publicação (XML: pubSL)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_dt',
               existing_type=sa.DATE(),
               comment='Data da Publicação (XML: pubdt)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pag',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Páginas (XML: pag)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'id_pag',
               existing_type=mysql.INTEGER(),
               comment='Identificador da Paginação (XML: idPag)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'id_int',
               existing_type=mysql.INTEGER(),
               comment='Identificador da Intervenção associada à Publicação (XML: idInt)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'url_diario',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Link para o DAR da Publicação (XML: URLDiario)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'legislatura_id',
               existing_type=mysql.INTEGER(),
               comment='Reference to legislature',
               existing_nullable=False)
    op.alter_column('intervencao_parlamentar', 'intervencao_id',
               existing_type=mysql.INTEGER(),
               comment='Intervention identifier (intId)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'legislatura_numero',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Legislature number (pubLg)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'sessao_numero',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Legislative session number (pubSl)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'tipo_intervencao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Intervention type (tinDs) - human readable description',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'data_reuniao_plenaria',
               existing_type=sa.DATE(),
               comment='Plenary meeting date (pubDtreu)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'qualidade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Intervention quality/context',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'fase_sessao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Session phase when intervention occurred',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'sumario',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Intervention summary (intSu)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'resumo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Intervention abstract/resume (intTe)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'atividade_id',
               existing_type=mysql.INTEGER(),
               comment='Related activity identifier',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'id_debate',
               existing_type=mysql.INTEGER(),
               comment='Related debate identifier',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Record creation timestamp',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='Record update timestamp',
               existing_nullable=True)
    op.drop_index(op.f('idx_intervencao_data_tipo'), table_name='intervencao_parlamentar')
    op.drop_index(op.f('idx_intervencao_legislatura_data'), table_name='intervencao_parlamentar')
    op.drop_index(op.f('idx_intervencao_sessao_legislatura'), table_name='intervencao_parlamentar')
    op.alter_column('legislaturas', 'numero',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='Legislature abbreviation (XML: sigla)',
               existing_nullable=False)
    op.alter_column('legislaturas', 'designacao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Full legislature designation',
               existing_nullable=False)
    op.alter_column('legislaturas', 'data_inicio',
               existing_type=sa.DATE(),
               comment='Legislature start date (XML: dtini)',
               existing_nullable=True)
    op.alter_column('legislaturas', 'data_fim',
               existing_type=sa.DATE(),
               comment='Legislature end date (XML: dtfim)',
               existing_nullable=True)
    op.alter_column('legislaturas', 'ativa',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Whether legislature is currently active',
               existing_nullable=True)
    op.drop_index(op.f('idx_meeting_attendances_dep_lookup'), table_name='meeting_attendances')
    op.drop_index(op.f('idx_meeting_attendances_presence_status'), table_name='meeting_attendances')
    op.drop_index(op.f('idx_meeting_attendances_session_performance'), table_name='meeting_attendances')
    op.alter_column('partidos', 'sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='Parliamentary group abbreviation (XML: sigla)',
               existing_nullable=False)
    op.alter_column('partidos', 'nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Full parliamentary group name (XML: nome)',
               existing_nullable=False)
    op.drop_index(op.f('idx_registo_interesses_deputado_lookup'), table_name='registo_interesses')
    op.add_column('registo_interesses_activities_unified', sa.Column('type_classification', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_activities_unified_lookup'), table_name='registo_interesses_activities_unified')
    op.add_column('registo_interesses_benefits_unified', sa.Column('service_location', sa.String(length=500), nullable=True))
    op.drop_index(op.f('idx_benefits_unified_lookup'), table_name='registo_interesses_benefits_unified')
    op.drop_index(op.f('idx_societies_unified_lookup'), table_name='registo_interesses_societies_unified')
    op.alter_column('registo_interesses_unified', 'gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.drop_index(op.f('idx_unified_cad_lookup'), table_name='registo_interesses_unified')
    op.drop_index(op.f('idx_unified_deputy_lookup'), table_name='registo_interesses_unified')
    op.drop_index(op.f('idx_unified_schema_version'), table_name='registo_interesses_unified')
    op.drop_index(op.f('uk_unified_deputy_legislature_record'), table_name='registo_interesses_unified')
    op.drop_index(op.f('idx_registo_interesses_v2_deputado_lookup'), table_name='registo_interesses_v2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_registo_interesses_v2_deputado_lookup'), 'registo_interesses_v2', ['deputado_id', 'cad_id'], unique=False)
    op.create_index(op.f('uk_unified_deputy_legislature_record'), 'registo_interesses_unified', ['deputado_id', 'legislatura_id', 'record_id', 'schema_version'], unique=True)
    op.create_index(op.f('idx_unified_schema_version'), 'registo_interesses_unified', ['schema_version', 'legislatura_id'], unique=False)
    op.create_index(op.f('idx_unified_deputy_lookup'), 'registo_interesses_unified', ['deputado_id', 'legislatura_id'], unique=False)
    op.create_index(op.f('idx_unified_cad_lookup'), 'registo_interesses_unified', ['cad_id', 'schema_version'], unique=False)
    op.alter_column('registo_interesses_unified', 'gender',
               existing_type=sa.String(length=1),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=True)
    op.create_index(op.f('idx_societies_unified_lookup'), 'registo_interesses_societies_unified', ['registo_id'], unique=False)
    op.create_index(op.f('idx_benefits_unified_lookup'), 'registo_interesses_benefits_unified', ['registo_id', 'benefit_type'], unique=False)
    op.drop_column('registo_interesses_benefits_unified', 'service_location')
    op.create_index(op.f('idx_activities_unified_lookup'), 'registo_interesses_activities_unified', ['registo_id', 'activity_type'], unique=False)
    op.drop_column('registo_interesses_activities_unified', 'type_classification')
    op.create_index(op.f('idx_registo_interesses_deputado_lookup'), 'registo_interesses', ['deputado_id', 'cad_id'], unique=False)
    op.alter_column('partidos', 'nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Full parliamentary group name (XML: nome)',
               existing_nullable=False)
    op.alter_column('partidos', 'sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='Parliamentary group abbreviation (XML: sigla)',
               existing_nullable=False)
    op.create_index(op.f('idx_meeting_attendances_session_performance'), 'meeting_attendances', ['dt_reuniao', 'dep_id', 'pres_tipo'], unique=False)
    op.create_index(op.f('idx_meeting_attendances_presence_status'), 'meeting_attendances', ['pres_tipo', 'dt_reuniao'], unique=False)
    op.create_index(op.f('idx_meeting_attendances_dep_lookup'), 'meeting_attendances', ['dep_id', 'dt_reuniao'], unique=False)
    op.alter_column('legislaturas', 'ativa',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Whether legislature is currently active',
               existing_nullable=True)
    op.alter_column('legislaturas', 'data_fim',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Legislature end date (XML: dtfim)',
               existing_nullable=True)
    op.alter_column('legislaturas', 'data_inicio',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Legislature start date (XML: dtini)',
               existing_nullable=True)
    op.alter_column('legislaturas', 'designacao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Full legislature designation',
               existing_nullable=False)
    op.alter_column('legislaturas', 'numero',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='Legislature abbreviation (XML: sigla)',
               existing_nullable=False)
    op.create_index(op.f('idx_intervencao_sessao_legislatura'), 'intervencao_parlamentar', ['sessao_numero', 'legislatura_id'], unique=False)
    op.create_index(op.f('idx_intervencao_legislatura_data'), 'intervencao_parlamentar', ['legislatura_id', 'data_reuniao_plenaria', 'tipo_intervencao'], unique=False)
    op.create_index(op.f('idx_intervencao_data_tipo'), 'intervencao_parlamentar', ['data_reuniao_plenaria', 'tipo_intervencao'], unique=False)
    op.alter_column('intervencao_parlamentar', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Record update timestamp',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'id_debate',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Related debate identifier',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'atividade_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Related activity identifier',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'resumo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Intervention abstract/resume (intTe)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'sumario',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Intervention summary (intSu)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'fase_sessao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Session phase when intervention occurred',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'qualidade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Intervention quality/context',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'data_reuniao_plenaria',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Plenary meeting date (pubDtreu)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'tipo_intervencao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Intervention type (tinDs) - human readable description',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'sessao_numero',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Legislative session number (pubSl)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'legislatura_numero',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Legislature number (pubLg)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'intervencao_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Intervention identifier (intId)',
               existing_nullable=True)
    op.alter_column('intervencao_parlamentar', 'legislatura_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Reference to legislature',
               existing_nullable=False)
    op.alter_column('iniciativas_eventos_publicacoes', 'url_diario',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Link para o DAR da Publicação (XML: URLDiario)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'id_int',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Identificador da Intervenção associada à Publicação (XML: idInt)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'id_pag',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Identificador da Paginação (XML: idPag)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pag',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Páginas (XML: pag)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_dt',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data da Publicação (XML: pubdt)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_sl',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Sessão legislativa em que ocorreu a Publicação (XML: pubSL)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_leg',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Legislatura em que ocorreu a Publicação (XML: pubLeg)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_tp',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Abreviatura do Tipo de Publicação (XML: pubTp)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_tipo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Descrição do Tipo de Publicação (XML: pubTipo)',
               existing_nullable=True)
    op.alter_column('iniciativas_eventos_publicacoes', 'pub_nr',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Número da Publicação (XML: pubNr)',
               existing_nullable=True)
    op.create_index(op.f('idx_iniciativas_number_leg'), 'iniciativas_detalhadas', ['ini_nr', 'ini_leg', 'ini_tipo'], unique=False, mysql_length={'ini_leg': 20, 'ini_tipo': 100})
    op.create_index(op.f('idx_iniciativas_legislatura_tipo'), 'iniciativas_detalhadas', ['legislatura_id', 'ini_tipo'], unique=False, mysql_length={'ini_tipo': 100})
    op.create_index(op.f('idx_iniciativas_leg_periodo'), 'iniciativas_detalhadas', ['ini_leg', 'legislatura_id'], unique=False, mysql_length={'ini_leg': 20})
    op.create_index(op.f('idx_iniciativas_data_periodo'), 'iniciativas_detalhadas', ['data_inicio_leg', 'data_fim_leg'], unique=False)
    op.alter_column('iniciativas_detalhadas', 'ini_obs',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Observações associadas (XML: iniObs)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_link_texto',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Link para o texto da iniciativa (XML: iniLinkTexto)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_texto_subst_campo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Observações sobre substituição do ficheiro (XML: iniTextoSubstCampo)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_texto_subst',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Indica se tem texto de substituição (XML: iniTextoSubst)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_titulo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Titulo da Iniciativa (XML: iniTitulo)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'data_fim_leg',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de Fim da Legislatura (XML: dataFimleg)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'data_inicio_leg',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de Inicio da Legislatura (XML: dataInicioleg)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_sel',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Sessão legislativa da iniciativa (XML: iniSel)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_leg',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Legislatura da iniciativa (XML: iniLeg)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_desc_tipo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Descrição do Tipo de Iniciativa (XML: iniDescTipo)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_tipo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Tipo de Iniciativa - código (XML: iniTipo)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_nr',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Número da Iniciativa (XML: iniNr)',
               existing_nullable=True)
    op.alter_column('iniciativas_detalhadas', 'ini_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Identificador da Iniciativa (XML: iniId)',
               existing_nullable=False)
    op.alter_column('eventos_parlamentares', 'tipo_evento',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Event type (TipoEvento) - requires TipodeEvento translator for classification',
               existing_nullable=True)
    op.alter_column('eventos_parlamentares', 'sessao_legislativa',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Legislative session (SessaoLegislativa) - session number when event occurred',
               existing_nullable=True)
    op.alter_column('eventos_parlamentares', 'local_evento',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='Event location (LocalEvento) - where the event was held',
               existing_nullable=True)
    op.alter_column('eventos_parlamentares', 'designacao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Event designation (Designacao) - official title or name of event',
               existing_nullable=True)
    op.alter_column('eventos_parlamentares', 'data',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Event date (Data) - when the event took place',
               existing_nullable=True)
    op.alter_column('eventos_parlamentares', 'id_evento',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Event identifier (IDEvento) - unique event registry ID',
               existing_nullable=False)
    op.alter_column('deslocacoes_parlamentares', 'designacao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Displacement designation (Designacao) - official purpose or destination description',
               existing_nullable=True)
    op.alter_column('deslocacoes_parlamentares', 'data_fim',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='End date (DataFim) - when displacement ends',
               existing_nullable=True)
    op.alter_column('deslocacoes_parlamentares', 'data_ini',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Start date (DataIni) - when displacement begins',
               existing_nullable=True)
    op.alter_column('deslocacoes_parlamentares', 'id_deslocacao',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Displacement identifier (IDDeslocacao) - unique displacement registry ID',
               existing_nullable=False)
    op.alter_column('deputy_gp_situations', 'gp_dt_fim',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='GP membership end date (XML: gpDtFim)',
               existing_nullable=True)
    op.alter_column('deputy_gp_situations', 'gp_dt_inicio',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='GP membership start date (XML: gpDtInicio)',
               existing_nullable=True)
    op.alter_column('deputy_gp_situations', 'gp_sigla',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='Parliamentary group acronym (XML: gpSigla)',
               existing_nullable=True)
    op.alter_column('deputy_gp_situations', 'gp_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Parliamentary group ID (XML: gpId)',
               existing_nullable=True)
    op.create_index(op.f('idx_deputados_legislatura'), 'deputados', ['legislatura_id'], unique=False)
    op.create_index(op.f('idx_deputados_biographical'), 'deputados', ['data_nascimento', 'naturalidade'], unique=False)
    op.create_index(op.f('idx_deputados_active_lookup'), 'deputados', ['ativo', 'nome'], unique=False)
    op.alter_column('deputados', 'nome_completo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               comment=None,
               existing_comment='Full deputy name (XML: DepNomeCompleto)',
               existing_nullable=True)
    op.alter_column('deputados', 'nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Parliamentary name - shortened version (XML: DepNomeParlamentar)',
               existing_nullable=False)
    op.alter_column('deputados', 'id_cadastro',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment="Person's unique registration ID across all legislatures (XML: DepCadId)",
               existing_nullable=False)
    op.alter_column('deputados', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Legislature-specific deputy ID (XML: DepId)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('delegacao_permanente_membros', 'data_fim',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='End date of functions (DataFim)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'data_inicio',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Start date of functions (DataInicio)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'gp',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Parliamentary group (Gp)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'cargo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Position held by deputy (Cargo)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Deputy participant name (Nome)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_membros', 'membro_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Deputy identifier (Id)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_comissoes', 'subcomissoes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Subcommissions data (Subcomissoes)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_comissoes', 'composicao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Commission composition details (Composição)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente_comissoes', 'nome',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Commission name (Nome)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente', 'data_eleicao',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Delegation election date (DataEleicao)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente', 'sessao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Legislative session number (Sessão)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente', 'nome',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Permanent delegation name (Nome)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente', 'delegacao_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Delegation record identifier (Id)',
               existing_nullable=True)
    op.alter_column('delegacao_permanente', 'legislatura_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Legislature identifier (Legislatura)',
               existing_nullable=False)
    op.alter_column('dados_situacao_deputados', 'sio_dt_fim',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Situation end date (XML: sioDtFim)',
               existing_nullable=True)
    op.alter_column('dados_situacao_deputados', 'sio_dt_inicio',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Situation start date (XML: sioDtInicio)',
               existing_nullable=True)
    op.alter_column('dados_situacao_deputados', 'sio_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Situation description (XML: sioDes)',
               existing_nullable=True)
    op.alter_column('circulos_eleitorais', 'codigo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='Electoral circle code (XML: cpId)',
               existing_nullable=True)
    op.alter_column('circulos_eleitorais', 'designacao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Electoral circle name (XML: cpDes)',
               existing_nullable=False)
    op.alter_column('audiencias_parlamentares', 'observacoes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Observations (Observacoes) - additional notes and remarks',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'entidades',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Participating entities (Entidades) - organizations or individuals presenting',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'tipo_audiencia',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Audience type (TipoAudiencia) - classification of audience format',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'concedida',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Granted status (Concedida) - whether the audience request was approved',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'comissao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Committee (Comissao) - committee conducting the audience',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'data',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Alternative date field (Data) - additional date reference',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'data_audiencia',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Audience date (Data) - when the audience took place',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'assunto',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Audience subject (Assunto) - topic or matter being discussed',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'sessao_legislativa',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Legislative session (SessaoLegislativa) - session when audience occurred',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'numero_audiencia',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Audience number (NumeroAudiencia) - sequential numbering within session',
               existing_nullable=True)
    op.alter_column('audiencias_parlamentares', 'id_audiencia',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Audience identifier (IDAudiencia) - unique audience registry ID',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'observacoes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='General observations (Observacoes) - additional notes and comments',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'resultado_votacao_pontos',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Voting results by points (ResultadoVotacaoPontos) - detailed voting outcomes',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'textos_aprovados',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Approved texts (TextosAprovados) - texts that were approved during activity',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'outros_subscritores',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Other subscribers (OutrosSubscritores) - additional supporters or co-authors',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'autores_gp',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Group authors (AutoresGP) - parliamentary groups authoring the activity',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'tipo_autor',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Author type (TipoAutor) - requires TipodeAutor translator for classification',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'data_agendamento_debate',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Scheduled debate date (DataAgendamentoDebate) - planned discussion date',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'data_entrada',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Entry date (DataEntrada) - when activity was registered in system',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'data_atividade',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Activity date (Data) - when the activity took place',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'numero',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Activity number (Numero) - sequential or reference number',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'assunto',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Activity subject matter (Assunto) - descriptive text of activity topic',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'desc_tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Activity type description (DescTipo) - official classification name',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Activity type code (Tipo) - requires TipodeAtividade translator',
               existing_nullable=True)
    op.alter_column('atividade_parlamentar', 'atividade_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Activity identifier (IDAtividade) - unique registry ID',
               existing_nullable=True)
    op.alter_column('atividade_deputados', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=True)
    op.alter_column('atividade_deputados', 'leg_des',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='Legislature designation (LegDes) - which legislature this activity pertains to',
               existing_nullable=True)
    op.alter_column('atividade_deputados', 'dep_cad_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment="Deputy's cadastral identifier (DepCadId) - unique registry ID",
               existing_nullable=True)
    op.alter_column('atividade_deputados', 'deputado_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Reference to the deputy this activity record belongs to',
               existing_nullable=False)
    op.alter_column('atividade_deputado_lists', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=True)
    op.alter_column('atividade_deputado_lists', 'atividade_deputado_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Reference to parent AtividadeDeputado record',
               existing_nullable=False)
    op.drop_index('idx_agenda_anexo_tipo', table_name='agenda_parlamentar_anexos')
    op.alter_column('agenda_parlamentar_anexos', 'tipo_anexo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment="Attachment type - 'comissao_permanente' or 'plenario' based on parent structure",
               existing_nullable=True)
    op.alter_column('agenda_parlamentar_anexos', 'url_field',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Parliament website document link (uRLField) - URL to access document',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar_anexos', 'titulo_field',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Document title (tituloField) - descriptive name of document',
               existing_nullable=False)
    op.alter_column('agenda_parlamentar_anexos', 'tipo_documento_field',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Document type (tipoDocumentoField) - classification of document',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar_anexos', 'id_field',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Document unique identifier (idField) - external document ID',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'pos_plenario',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='After plenary session indicator (PostPlenary) - occurs after plenary',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'link_externo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Parliament website link (Link) - URL to event page if exists',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'local_evento',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Event location (Local) - where the event takes place',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'descricao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='HTML encoded descriptive text (InternetText) - detailed event information',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'subtitulo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Event subtitle (Subtitle) - additional event description',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'titulo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Event title (Title) - main event name',
               existing_nullable=False)
    op.alter_column('agenda_parlamentar', 'evento_dia_inteiro',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Full day event indicator (AllDayEvent) - true if all day',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'hora_fim',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Event end time (EventEndTime) - local time format',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'hora_inicio',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Event start time (EventStartTime) - local time format',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'data_evento',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Event start date (EventStartDate) - when event occurs',
               existing_nullable=False)
    op.alter_column('agenda_parlamentar', 'grupo_parlamentar',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Parliamentary group ID (ParlamentGroup) - when associated with event',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'tema_nome',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Theme description (Theme) - derived from ThemeType enum',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'tema_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Theme unique identifier (ThemeId) - requires ThemeType translator',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'secao_nome',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Section description (Section) - derived from SectionType enum',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'secao_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Section unique identifier (SectionId) - requires SectionType translator',
               existing_nullable=True)
    op.alter_column('agenda_parlamentar', 'id_externo',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Unique meeting/event identifier (Id) - external system ID',
               existing_nullable=True)
    # op.drop_column('agenda_parlamentar', 'sessao_numero')  # Commented out - column managed by previous migration
    # op.drop_column('agenda_parlamentar', 'reuniao_numero')  # Commented out - column managed by previous migration
    # op.drop_column('agenda_parlamentar', 'orgao_designacao')  # Commented out - column managed by previous migration
    # op.drop_column('agenda_parlamentar', 'legislatura_designacao')  # Commented out - column managed by previous migration
    # op.drop_column('agenda_parlamentar', 'order_value')  # Commented out - column managed by previous migration
    op.alter_column('actividade_audiencias', 'actividade_out_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Reference to general activity record',
               existing_nullable=False)
    op.alter_column('actividade_audicoes', 'actividade_out_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Reference to general activity record',
               existing_nullable=False)
    # op.drop_table('registo_interesses_social_positions_unified')  # Commented out - table managed by previous migration
    op.drop_table('orcamento_estado_votacoes')
    op.drop_table('orcamento_estado_proponentes')
    op.drop_table('orcamento_estado_iniciativas')
    op.drop_table('orcamento_estado_diplomas')
    op.drop_table('orcamento_estado_artigos')
    op.drop_index(op.f('ix_orcamento_estado_propostas_alteracao_proposta_id'), table_name='orcamento_estado_propostas_alteracao')
    op.drop_index('idx_oe_proposta_legislatura', table_name='orcamento_estado_propostas_alteracao')
    op.drop_index('idx_oe_proposta_id', table_name='orcamento_estado_propostas_alteracao')
    op.drop_index('idx_oe_proposta_format', table_name='orcamento_estado_propostas_alteracao')
    op.drop_table('orcamento_estado_propostas_alteracao')
    op.drop_index(op.f('ix_orcamento_estado_items_item_id'), table_name='orcamento_estado_items')
    op.drop_index('idx_oe_item_tipo', table_name='orcamento_estado_items')
    op.drop_index('idx_oe_item_pai', table_name='orcamento_estado_items')
    op.drop_index('idx_oe_item_legislatura', table_name='orcamento_estado_items')
    op.drop_index('idx_oe_item_id', table_name='orcamento_estado_items')
    op.drop_table('orcamento_estado_items')
    # op.drop_index(op.f('ix_grupos_amizade_participantes_participant_id'), table_name='grupos_amizade_participantes')  # Commented out - table managed by previous migration
    # op.drop_table('grupos_amizade_participantes')  # Commented out - table managed by previous migration
    op.drop_table('orcamento_estado')
    # op.drop_index(op.f('ix_grupos_amizade_reunioes_meeting_id'), table_name='grupos_amizade_reunioes')  # Commented out - table managed by previous migration
    # op.drop_table('grupos_amizade_reunioes')  # Commented out - table managed by previous migration
    # op.drop_table('grupos_amizade_membros')  # Commented out - table managed by previous migration
    # op.drop_index(op.f('ix_grupos_amizade_standalone_legislatura'), table_name='grupos_amizade_standalone')  # Commented out - table managed by previous migration
    # op.drop_index(op.f('ix_grupos_amizade_standalone_group_id'), table_name='grupos_amizade_standalone')  # Commented out - table managed by previous migration
    # op.drop_table('grupos_amizade_standalone')  # Commented out - table managed by previous migration
    # ### end Alembic commands ###
