"""Add dep_nome_completo to historical composition models for IX Legislature

Revision ID: 8ab4a1649e90
Revises: 7d401cd0f2da
Create Date: 2025-07-31 12:35:30.443078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab4a1649e90'
down_revision: Union[str, Sequence[str], None] = '7d401cd0f2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ar_board_historical_compositions', sa.Column('dep_nome_completo', sa.String(length=200), nullable=True))
    op.add_column('commission_historical_compositions', sa.Column('dep_nome_completo', sa.String(length=200), nullable=True))
    op.add_column('sub_committee_historical_compositions', sa.Column('dep_nome_completo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_committee_historical_compositions', 'dep_nome_completo')
    op.drop_column('commission_historical_compositions', 'dep_nome_completo')
    op.drop_column('ar_board_historical_compositions', 'dep_nome_completo')
    # ### end Alembic commands ###
