"""Add OrcamentoContasGerencia model for budget and account management data

Revision ID: 8cf3692eefa4
Revises: 971e9a04644c
Create Date: 2025-07-30 20:48:59.822240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf3692eefa4'
down_revision: Union[str, Sequence[str], None] = '971e9a04644c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento_contas_gerencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('tp', sa.String(length=10), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('leg', sa.String(length=20), nullable=False),
    sa.Column('sl', sa.Integer(), nullable=False),
    sa.Column('dt_aprovacao_ca', sa.Date(), nullable=True),
    sa.Column('dt_agendamento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'legislatura_id', name='uq_orcamento_gerencia_entry_leg')
    )
    op.create_index('idx_orcamento_gerencia_ano', 'orcamento_contas_gerencia', ['ano'], unique=False)
    op.create_index('idx_orcamento_gerencia_entry_id', 'orcamento_contas_gerencia', ['entry_id'], unique=False)
    op.create_index('idx_orcamento_gerencia_legislatura', 'orcamento_contas_gerencia', ['legislatura_id'], unique=False)
    op.create_index('idx_orcamento_gerencia_tipo', 'orcamento_contas_gerencia', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orcamento_gerencia_tipo', table_name='orcamento_contas_gerencia')
    op.drop_index('idx_orcamento_gerencia_legislatura', table_name='orcamento_contas_gerencia')
    op.drop_index('idx_orcamento_gerencia_entry_id', table_name='orcamento_contas_gerencia')
    op.drop_index('idx_orcamento_gerencia_ano', table_name='orcamento_contas_gerencia')
    op.drop_table('orcamento_contas_gerencia')
    # ### end Alembic commands ###
