"""Add observacoes field to MeetingAttendance for presence quality tracking

Revision ID: 92d4998e2b20
Revises: b094fb41d643
Create Date: 2025-07-31 17:37:09.888723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d4998e2b20'
down_revision: Union[str, Sequence[str], None] = 'b094fb41d643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_attendances', sa.Column('observacoes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_attendances', 'observacoes')
    # ### end Alembic commands ###
