"""Add I Legislature specific models and fields

Revision ID: 96ff2e82518e
Revises: 2d35af97e8a0
Create Date: 2025-07-31 07:43:01.440743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ff2e82518e'
down_revision: Union[str, Sequence[str], None] = '2d35af97e8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores_pareceres_inc_imu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parlamento_jovens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatores_ini_europeias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autores_pareceres_inc_imu_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autores_pareceres_inc_imu_id', sa.Integer(), nullable=False),
    sa.Column('act_tp_desc', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autores_pareceres_inc_imu_id'], ['autores_pareceres_inc_imu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dados_deputado_parlamento_jovens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parlamento_jovens_id', sa.Integer(), nullable=False),
    sa.Column('tipo_reuniao', sa.String(length=200), nullable=True),
    sa.Column('circulo_eleitoral', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parlamento_jovens_id'], ['parlamento_jovens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatores_ini_europeias_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatores_ini_europeias_id', sa.Integer(), nullable=False),
    sa.Column('ine_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatores_ini_europeias_id'], ['relatores_ini_europeias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('actividades_comissao_outs', sa.Column('evento_id', sa.Integer(), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('act_loc', sa.String(length=500), nullable=True))
    # Note: Foreign key constraint for evento_id will be enforced at application level for SQLite
    op.add_column('delegacoes_eventuais_out', sa.Column('dev_tp', sa.String(length=100), nullable=True))
    op.add_column('subcomissoes_grupos_trabalho_out', sa.Column('cms_situacao', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcomissoes_grupos_trabalho_out', 'cms_situacao')
    op.drop_column('delegacoes_eventuais_out', 'dev_tp')
    op.drop_constraint(None, 'actividades_comissao_outs', type_='foreignkey')
    op.drop_column('actividades_comissao_outs', 'act_loc')
    op.drop_column('actividades_comissao_outs', 'evento_id')
    op.drop_table('relatores_ini_europeias_out')
    op.drop_table('dados_deputado_parlamento_jovens')
    op.drop_table('autores_pareceres_inc_imu_out')
    op.drop_table('relatores_ini_europeias')
    op.drop_table('parlamento_jovens')
    op.drop_table('eventos')
    op.drop_table('autores_pareceres_inc_imu')
    # ### end Alembic commands ###
