"""Add analytics tables

Revision ID: a13dc27193ca
Revises: 3f692c91a138
Create Date: 2025-08-04 17:52:15.249547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13dc27193ca'
down_revision: Union[str, Sequence[str], None] = '3f692c91a138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('complete_records', sa.Integer(), nullable=True),
    sa.Column('incomplete_records', sa.Integer(), nullable=True),
    sa.Column('completeness_percentage', sa.String(length=10), nullable=True),
    sa.Column('consistency_score', sa.Integer(), nullable=True),
    sa.Column('referential_integrity_score', sa.Integer(), nullable=True),
    sa.Column('temporal_consistency_score', sa.Integer(), nullable=True),
    sa.Column('null_critical_fields', sa.Integer(), nullable=True),
    sa.Column('invalid_date_ranges', sa.Integer(), nullable=True),
    sa.Column('duplicate_records', sa.Integer(), nullable=True),
    sa.Column('orphaned_records', sa.Integer(), nullable=True),
    sa.Column('oldest_record_date', sa.Date(), nullable=True),
    sa.Column('newest_record_date', sa.Date(), nullable=True),
    sa.Column('data_span_days', sa.Integer(), nullable=True),
    sa.Column('last_update_lag_hours', sa.Integer(), nullable=True),
    sa.Column('quality_trend', sa.String(length=20), nullable=True),
    sa.Column('issue_categories', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('check_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deputy_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cadastro', sa.Integer(), nullable=False),
    sa.Column('first_election_date', sa.Date(), nullable=True),
    sa.Column('total_legislatures_served', sa.Integer(), nullable=True),
    sa.Column('consecutive_terms', sa.Integer(), nullable=True),
    sa.Column('years_of_service', sa.Integer(), nullable=True),
    sa.Column('current_term_start', sa.Date(), nullable=True),
    sa.Column('is_currently_active', sa.Boolean(), nullable=True),
    sa.Column('key_positions_held', sa.Text(), nullable=True),
    sa.Column('committee_memberships', sa.Text(), nullable=True),
    sa.Column('leadership_roles', sa.Text(), nullable=True),
    sa.Column('significant_initiatives', sa.Text(), nullable=True),
    sa.Column('career_peak_year', sa.Integer(), nullable=True),
    sa.Column('career_peak_score', sa.Integer(), nullable=True),
    sa.Column('current_performance_trend', sa.String(length=20), nullable=True),
    sa.Column('experience_category', sa.String(length=20), nullable=True),
    sa.Column('early_career_focus', sa.String(length=100), nullable=True),
    sa.Column('mid_career_focus', sa.String(length=100), nullable=True),
    sa.Column('current_focus', sa.String(length=100), nullable=True),
    sa.Column('focus_evolution_pattern', sa.String(length=50), nullable=True),
    sa.Column('mentorship_score', sa.Integer(), nullable=True),
    sa.Column('network_centrality', sa.Integer(), nullable=True),
    sa.Column('cross_party_influence', sa.Integer(), nullable=True),
    sa.Column('media_attention_score', sa.Integer(), nullable=True),
    sa.Column('projected_career_trajectory', sa.String(length=50), nullable=True),
    sa.Column('specialization_strength', sa.Integer(), nullable=True),
    sa.Column('institutional_memory_value', sa.Integer(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(), nullable=True),
    sa.Column('calculation_version', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_cadastro')
    )
    op.create_table('attendance_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('sessions_scheduled', sa.Integer(), nullable=True),
    sa.Column('sessions_attended', sa.Integer(), nullable=True),
    sa.Column('sessions_absent', sa.Integer(), nullable=True),
    sa.Column('sessions_justified_absence', sa.Integer(), nullable=True),
    sa.Column('sessions_unjustified_absence', sa.Integer(), nullable=True),
    sa.Column('attendance_rate', sa.String(length=10), nullable=True),
    sa.Column('consecutive_absences', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_absences', sa.Integer(), nullable=True),
    sa.Column('attendance_consistency', sa.Integer(), nullable=True),
    sa.Column('seasonal_pattern', sa.String(length=20), nullable=True),
    sa.Column('plenario_attended', sa.Integer(), nullable=True),
    sa.Column('comissao_attended', sa.Integer(), nullable=True),
    sa.Column('other_sessions_attended', sa.Integer(), nullable=True),
    sa.Column('early_departures', sa.Integer(), nullable=True),
    sa.Column('late_arrivals', sa.Integer(), nullable=True),
    sa.Column('full_session_attendance', sa.Integer(), nullable=True),
    sa.Column('punctuality_score', sa.Integer(), nullable=True),
    sa.Column('rank_in_month', sa.Integer(), nullable=True),
    sa.Column('above_average_attendance', sa.Boolean(), nullable=True),
    sa.Column('improvement_from_prev_month', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deputy_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=True),
    sa.Column('activity_score', sa.Integer(), nullable=True),
    sa.Column('attendance_score', sa.Integer(), nullable=True),
    sa.Column('initiative_score', sa.Integer(), nullable=True),
    sa.Column('intervention_score', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('total_sessions_attended', sa.Integer(), nullable=True),
    sa.Column('total_sessions_eligible', sa.Integer(), nullable=True),
    sa.Column('attendance_percentage', sa.Integer(), nullable=True),
    sa.Column('total_initiatives', sa.Integer(), nullable=True),
    sa.Column('total_interventions', sa.Integer(), nullable=True),
    sa.Column('total_words_spoken', sa.Integer(), nullable=True),
    sa.Column('initiatives_approved', sa.Integer(), nullable=True),
    sa.Column('initiatives_pending', sa.Integer(), nullable=True),
    sa.Column('initiatives_rejected', sa.Integer(), nullable=True),
    sa.Column('approval_rate', sa.Integer(), nullable=True),
    sa.Column('collaboration_count', sa.Integer(), nullable=True),
    sa.Column('leadership_score', sa.Integer(), nullable=True),
    sa.Column('days_active', sa.Integer(), nullable=True),
    sa.Column('avg_monthly_activity', sa.Integer(), nullable=True),
    sa.Column('peak_activity_month', sa.String(length=7), nullable=True),
    sa.Column('activity_trend', sa.String(length=20), nullable=True),
    sa.Column('rank_overall', sa.Integer(), nullable=True),
    sa.Column('rank_in_party', sa.Integer(), nullable=True),
    sa.Column('rank_in_legislature', sa.Integer(), nullable=True),
    sa.Column('percentile_overall', sa.Integer(), nullable=True),
    sa.Column('data_completeness_score', sa.Integer(), nullable=True),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('calculation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('needs_recalculation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deputado_id', 'legislatura_id', name='unique_deputy_legislature_analytics')
    )
    op.create_table('initiative_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=True),
    sa.Column('total_initiatives_authored', sa.Integer(), nullable=True),
    sa.Column('total_initiatives_co_authored', sa.Integer(), nullable=True),
    sa.Column('solo_initiatives', sa.Integer(), nullable=True),
    sa.Column('collaborative_initiatives', sa.Integer(), nullable=True),
    sa.Column('cross_party_initiatives', sa.Integer(), nullable=True),
    sa.Column('projetos_lei', sa.Integer(), nullable=True),
    sa.Column('propostas_lei', sa.Integer(), nullable=True),
    sa.Column('requerimentos', sa.Integer(), nullable=True),
    sa.Column('perguntas', sa.Integer(), nullable=True),
    sa.Column('mocoes', sa.Integer(), nullable=True),
    sa.Column('other_types', sa.Integer(), nullable=True),
    sa.Column('initiatives_approved', sa.Integer(), nullable=True),
    sa.Column('initiatives_in_progress', sa.Integer(), nullable=True),
    sa.Column('initiatives_rejected', sa.Integer(), nullable=True),
    sa.Column('initiatives_withdrawn', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.String(length=10), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('avg_initiatives_per_month', sa.String(length=10), nullable=True),
    sa.Column('most_productive_month', sa.String(length=7), nullable=True),
    sa.Column('productivity_trend', sa.String(length=20), nullable=True),
    sa.Column('first_initiative_date', sa.Date(), nullable=True),
    sa.Column('latest_initiative_date', sa.Date(), nullable=True),
    sa.Column('initiative_span_days', sa.Integer(), nullable=True),
    sa.Column('primary_topic_area', sa.String(length=100), nullable=True),
    sa.Column('topic_diversity_score', sa.Integer(), nullable=True),
    sa.Column('expertise_areas', sa.Text(), nullable=True),
    sa.Column('unique_collaborators', sa.Integer(), nullable=True),
    sa.Column('collaboration_score', sa.Integer(), nullable=True),
    sa.Column('leadership_ratio', sa.String(length=10), nullable=True),
    sa.Column('avg_initiative_complexity', sa.Integer(), nullable=True),
    sa.Column('amendment_rate', sa.String(length=10), nullable=True),
    sa.Column('debate_generation_score', sa.Integer(), nullable=True),
    sa.Column('rank_by_quantity', sa.Integer(), nullable=True),
    sa.Column('rank_by_success_rate', sa.Integer(), nullable=True),
    sa.Column('rank_by_impact', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove analytics tables."""
    op.drop_table('initiative_analytics')
    op.drop_table('deputy_analytics')
    op.drop_table('attendance_analytics')
    op.drop_table('deputy_timeline')
    op.drop_table('data_quality_metrics')
    # ### end Alembic commands ###
