"""Make destinatario_id nullable in pergunta_requerimento_respostas for direct responses

Revision ID: a294b21930ca
Revises: 3e06c9ad4d9a
Create Date: 2025-08-13 11:05:23.856367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a294b21930ca'
down_revision: Union[str, Sequence[str], None] = '3e06c9ad4d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pergunta_requerimento_respostas', 'destinatario_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='Recipient ID (NULL for direct responses like RespostasSPerguntas)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pergunta_requerimento_respostas', 'destinatario_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Recipient ID (NULL for direct responses like RespostasSPerguntas)')
    # ### end Alembic commands ###
