"""Add VIII Legislature FaseDebate field to PeticaoOrador

Revision ID: a776b079fed3
Revises: 90d1b903c3ff
Create Date: 2025-08-04 06:09:21.068438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a776b079fed3'
down_revision: Union[str, Sequence[str], None] = '90d1b903c3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peticoes_oradores', sa.Column('fase_debate', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peticoes_oradores', 'fase_debate')
    # ### end Alembic commands ###
