"""Add final IX Legislature fields: relator_id, id_audiencia, observacoes, sessao_legislativa

Revision ID: ad4bcaff3c92
Revises: e6383811cd03
Create Date: 2025-07-30 19:41:18.390452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4bcaff3c92'
down_revision: Union[str, Sequence[str], None] = 'e6383811cd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audicoes_parlamentares', sa.Column('sessao_legislativa', sa.String(length=100), nullable=True))
    op.add_column('audiencias_parlamentares', sa.Column('id_audiencia', sa.Integer(), nullable=True))
    op.add_column('debate_parlamentar', sa.Column('observacoes', sa.Text(), nullable=True))
    op.add_column('relatorio_parlamentar_relatores', sa.Column('relator_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relatorio_parlamentar_relatores', 'relator_id')
    op.drop_column('debate_parlamentar', 'observacoes')
    op.drop_column('audiencias_parlamentares', 'id_audiencia')
    op.drop_column('audicoes_parlamentares', 'sessao_legislativa')
    # ### end Alembic commands ###
