"""Increase sigla_orgao column length from 20 to 50 characters for all organ tables

Revision ID: b094fb41d643
Revises: aed91e14625f
Create Date: 2025-07-31 16:25:52.048740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b094fb41d643'
down_revision: Union[str, Sequence[str], None] = 'aed91e14625f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrative_councils', 'sigla_orgao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('ar_boards', 'sigla_orgao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('commission_president_conferences', 'sigla_orgao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('commissions', 'sigla_orgao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('leader_conferences', 'sigla_orgao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('permanent_committees', 'sigla_orgao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('plenaries', 'sigla_orgao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('sub_committees', 'sigla_orgao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('work_groups', 'sigla_orgao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_groups', 'sigla_orgao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('sub_committees', 'sigla_orgao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('plenaries', 'sigla_orgao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('permanent_committees', 'sigla_orgao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('leader_conferences', 'sigla_orgao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('commissions', 'sigla_orgao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('commission_president_conferences', 'sigla_orgao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('ar_boards', 'sigla_orgao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('administrative_councils', 'sigla_orgao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
