"""Add XV Legislature voting descricao field

Revision ID: b2db5bcadb51
Revises: b59a5ca9b335
Create Date: 2025-08-04 06:25:04.101632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2db5bcadb51'
down_revision: Union[str, Sequence[str], None] = 'b59a5ca9b335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peticoes_relatorios_finais', sa.Column('votacao_descricao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peticoes_relatorios_finais', 'votacao_descricao')
    # ### end Alembic commands ###
