"""Remove unique constraint on id_cadastro and add composite unique constraint

Revision ID: b3e6e29740ad
Revises: e01d0dfd5efe
Create Date: 2025-08-06 15:59:26.657387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e6e29740ad'
down_revision: Union[str, Sequence[str], None] = 'e01d0dfd5efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('id_cadastro'), table_name='deputados')
    op.create_index('idx_deputy_cadastro', 'deputados', ['id_cadastro'], unique=False)
    op.create_index('idx_deputy_legislature', 'deputados', ['legislatura_id'], unique=False)
    op.create_index('idx_deputy_name', 'deputados', ['nome'], unique=False)
    op.create_unique_constraint('uq_deputy_cadastro_legislature', 'deputados', ['id_cadastro', 'legislatura_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_deputy_cadastro_legislature', 'deputados', type_='unique')
    op.drop_index('idx_deputy_name', table_name='deputados')
    op.drop_index('idx_deputy_legislature', table_name='deputados')
    op.drop_index('idx_deputy_cadastro', table_name='deputados')
    op.create_index(op.f('id_cadastro'), 'deputados', ['id_cadastro'], unique=True)
    # ### end Alembic commands ###
