"""Add remaining performance indexes for transparency queries

Revision ID: b533b361f7cc
Revises: 052ca257f9a6
Create Date: 2025-08-14 09:00:55.023878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b533b361f7cc'
down_revision: Union[str, Sequence[str], None] = '052ca257f9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_eventos_data_fase', 'iniciativas_eventos', ['data_fase'], unique=False)
    op.create_index('idx_eventos_evt_id', 'iniciativas_eventos', ['evt_id'], unique=False)
    op.create_index('idx_eventos_iniciativa_data_composite', 'iniciativas_eventos', ['iniciativa_id', 'data_fase'], unique=False)
    op.create_index('idx_eventos_iniciativa_id', 'iniciativas_eventos', ['iniciativa_id'], unique=False)
    op.create_index('idx_eventos_oev_id', 'iniciativas_eventos', ['oev_id'], unique=False)
    op.create_index('idx_dest_data_prorrogacao', 'pergunta_requerimento_destinatarios', ['data_prorrogacao'], unique=False)
    op.create_index('idx_dest_data_reenvio', 'pergunta_requerimento_destinatarios', ['data_reenvio'], unique=False)
    op.create_index('idx_dest_nome_entidade', 'pergunta_requerimento_destinatarios', ['nome_entidade'], unique=False)
    op.create_index('idx_dest_pergunta_req_id', 'pergunta_requerimento_destinatarios', ['pergunta_requerimento_id'], unique=False)
    op.create_index('idx_dest_prorrogado', 'pergunta_requerimento_destinatarios', ['prorrogado'], unique=False)
    op.create_index('idx_resp_data_resposta', 'pergunta_requerimento_respostas', ['data_resposta'], unique=False)
    op.create_index('idx_resp_destinatario_id', 'pergunta_requerimento_respostas', ['destinatario_id'], unique=False)
    op.create_index('idx_resp_entidade', 'pergunta_requerimento_respostas', ['entidade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_resp_entidade', table_name='pergunta_requerimento_respostas')
    op.drop_index('idx_resp_destinatario_id', table_name='pergunta_requerimento_respostas')
    op.drop_index('idx_resp_data_resposta', table_name='pergunta_requerimento_respostas')
    op.drop_index('idx_dest_prorrogado', table_name='pergunta_requerimento_destinatarios')
    op.drop_index('idx_dest_pergunta_req_id', table_name='pergunta_requerimento_destinatarios')
    op.drop_index('idx_dest_nome_entidade', table_name='pergunta_requerimento_destinatarios')
    op.drop_index('idx_dest_data_reenvio', table_name='pergunta_requerimento_destinatarios')
    op.drop_index('idx_dest_data_prorrogacao', table_name='pergunta_requerimento_destinatarios')
    op.drop_index('idx_eventos_oev_id', table_name='iniciativas_eventos')
    op.drop_index('idx_eventos_iniciativa_id', table_name='iniciativas_eventos')
    op.drop_index('idx_eventos_iniciativa_data_composite', table_name='iniciativas_eventos')
    op.drop_index('idx_eventos_evt_id', table_name='iniciativas_eventos')
    op.drop_index('idx_eventos_data_fase', table_name='iniciativas_eventos')
    # ### end Alembic commands ###
