"""Add XIV Legislature additional voting fields (ausencias, detalhe) and publication obs field

Revision ID: b59a5ca9b335
Revises: 45edfaf28e5c
Create Date: 2025-08-04 06:23:44.628153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59a5ca9b335'
down_revision: Union[str, Sequence[str], None] = '45edfaf28e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peticoes_publicacoes', sa.Column('obs', sa.Text(), nullable=True))
    op.add_column('peticoes_relatorios_finais', sa.Column('votacao_ausencias', sa.Text(), nullable=True))
    op.add_column('peticoes_relatorios_finais', sa.Column('votacao_detalhe', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peticoes_relatorios_finais', 'votacao_detalhe')
    op.drop_column('peticoes_relatorios_finais', 'votacao_ausencias')
    op.drop_column('peticoes_publicacoes', 'obs')
    # ### end Alembic commands ###
