"""Remove ativo field from Coligacao model - use calculated property

Revision ID: b8e4bf94153e
Revises: c1445bfe65a1
Create Date: 2025-08-11 15:48:49.900489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b8e4bf94153e'
down_revision: Union[str, Sequence[str], None] = 'c1445bfe65a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coligacoes', 'ativo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coligacoes', sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Whether coalition is currently active'))
    # ### end Alembic commands ###
