"""Add IniciativaIntervencaoOrador and related models for speakers in iniciativas interventions

Revision ID: ba25e41bfa02
Revises: 90dfa65411b4
Create Date: 2025-07-31 23:14:20.519037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba25e41bfa02'
down_revision: Union[str, Sequence[str], None] = '90dfa65411b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iniciativas_intervencoes_oradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervencao_id', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Text(), nullable=True),
    sa.Column('hora_termo', sa.Text(), nullable=True),
    sa.Column('fase_sessao', sa.Text(), nullable=True),
    sa.Column('sumario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['intervencao_id'], ['iniciativas_intervencoes_debates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_intervencoes_oradores_convidados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orador_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cargo', sa.Text(), nullable=True),
    sa.Column('entidade', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orador_id'], ['iniciativas_intervencoes_oradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_intervencoes_oradores_membros_governo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orador_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cargo', sa.Text(), nullable=True),
    sa.Column('ministerio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orador_id'], ['iniciativas_intervencoes_oradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_intervencoes_oradores_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orador_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.Text(), nullable=True),
    sa.Column('pub_tp', sa.Text(), nullable=True),
    sa.Column('pub_leg', sa.Text(), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orador_id'], ['iniciativas_intervencoes_oradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iniciativas_intervencoes_oradores_publicacoes')
    op.drop_table('iniciativas_intervencoes_oradores_membros_governo')
    op.drop_table('iniciativas_intervencoes_oradores_convidados')
    op.drop_table('iniciativas_intervencoes_oradores')
    # ### end Alembic commands ###
