"""Add final 4 AtividadesIV fields: autores_gp, descricao, ausencias for voting

Revision ID: be032a4b6c61
Revises: 62ad19cdf4d5
Create Date: 2025-07-30 19:30:55.662881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be032a4b6c61'
down_revision: Union[str, Sequence[str], None] = '62ad19cdf4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividade_parlamentar_votacoes', sa.Column('descricao', sa.Text(), nullable=True))
    op.add_column('atividade_parlamentar_votacoes', sa.Column('ausencias', sa.Text(), nullable=True))
    op.add_column('debate_parlamentar', sa.Column('autores_gp', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debate_parlamentar', 'autores_gp')
    op.drop_column('atividade_parlamentar_votacoes', 'ausencias')
    op.drop_column('atividade_parlamentar_votacoes', 'descricao')
    # ### end Alembic commands ###
