"""add_fase_evento_id_to_iniciativas_anexos

Revision ID: c08492a8616f
Revises: de9c20bb935d
Create Date: 2026-01-01 12:42:25.059037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08492a8616f'
down_revision: Union[str, Sequence[str], None] = 'de9c20bb935d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iniciativas_anexos', sa.Column('fase_evento_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'iniciativas_anexos', 'iniciativas_eventos', ['fase_evento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'iniciativas_anexos', type_='foreignkey')
    op.drop_column('iniciativas_anexos', 'fase_evento_id')
    # ### end Alembic commands ###
