"""Add coalition system models and partido tipo_entidade

Revision ID: c1445bfe65a1
Revises: 6447df62ed03
Create Date: 2025-08-11 15:39:26.519236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1445bfe65a1'
down_revision: Union[str, Sequence[str], None] = '6447df62ed03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coligacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=50), nullable=False, comment="Coalition abbreviation/sigla (e.g., 'PPD/PSD.CDS-PP')"),
    sa.Column('nome', sa.String(length=300), nullable=False, comment="Full coalition name (e.g., 'Aliança Democrática')"),
    sa.Column('nome_eleitoral', sa.String(length=300), nullable=True, comment='Electoral designation used in campaigns'),
    sa.Column('data_formacao', sa.Date(), nullable=True, comment='Coalition formation date'),
    sa.Column('data_dissolucao', sa.Date(), nullable=True, comment='Coalition dissolution date (if applicable)'),
    sa.Column('programa_eleitoral', sa.Text(), nullable=True, comment='Joint electoral program summary'),
    sa.Column('lideranca', sa.Text(), nullable=True, comment='Coalition leadership structure'),
    sa.Column('acordo_coligacao', sa.Text(), nullable=True, comment='Coalition agreement details'),
    sa.Column('tipo_coligacao', sa.String(length=50), nullable=True, comment='Coalition type: eleitoral, parlamentar, governo'),
    sa.Column('espectro_politico', sa.String(length=50), nullable=True, comment='Political spectrum: esquerda, centro-esquerda, centro, centro-direita, direita'),
    sa.Column('ativo', sa.Boolean(), nullable=True, comment='Whether coalition is currently active'),
    sa.Column('confianca_detecao', sa.Float(), nullable=True, comment='Confidence score for automatic detection (0.0-1.0)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('coligacao_partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coligacao_id', sa.Integer(), nullable=False),
    sa.Column('partido_sigla', sa.String(length=50), nullable=False, comment='Component party sigla'),
    sa.Column('partido_nome', sa.String(length=200), nullable=True, comment='Component party name'),
    sa.Column('data_adesao', sa.Date(), nullable=True, comment='Date party joined coalition'),
    sa.Column('data_saida', sa.Date(), nullable=True, comment='Date party left coalition (if applicable)'),
    sa.Column('ativo', sa.Boolean(), nullable=True, comment='Whether party is currently in coalition'),
    sa.Column('papel_coligacao', sa.String(length=100), nullable=True, comment='Party role in coalition: lider, principal, secundario, apoiante'),
    sa.Column('percentagem_acordada', sa.Float(), nullable=True, comment='Agreed percentage for seat/resource distribution'),
    sa.Column('confianca_detecao', sa.Float(), nullable=True, comment='Detection confidence for this relationship'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coligacao_id'], ['coligacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ativo_coligacao', 'coligacao_partidos', ['ativo', 'coligacao_id'], unique=False)
    op.create_index('idx_coligacao_partido', 'coligacao_partidos', ['coligacao_id', 'partido_sigla'], unique=False)
    op.create_index('idx_partido_sigla', 'coligacao_partidos', ['partido_sigla'], unique=False)
    op.add_column('deputado_mandatos_legislativos', sa.Column('tipo_entidade_politica', sa.String(length=20), nullable=True, comment="Type of political entity: 'partido' (individual party) or 'coligacao' (coalition)"))
    op.add_column('deputado_mandatos_legislativos', sa.Column('coligacao_id', sa.Integer(), nullable=True, comment='Coalition ID if this mandate was under a coalition'))
    op.add_column('deputado_mandatos_legislativos', sa.Column('eh_coligacao', sa.Boolean(), nullable=True, comment='Whether the par_sigla represents a coalition (auto-detected)'))
    op.add_column('deputado_mandatos_legislativos', sa.Column('confianca_detecao_coligacao', sa.Float(), nullable=True, comment='Confidence score for coalition detection (0.0-1.0)'))
    op.create_foreign_key(None, 'deputado_mandatos_legislativos', 'coligacoes', ['coligacao_id'], ['id'])
    op.add_column('partidos', sa.Column('tipo_entidade', sa.String(length=20), nullable=False, comment="Entity type: 'partido' (individual party) or 'coligacao' (coalition)"))
    op.add_column('partidos', sa.Column('coligacao_pai_id', sa.Integer(), nullable=True, comment='Parent coalition ID if this party is part of a coalition'))
    op.create_foreign_key(None, 'partidos', 'coligacoes', ['coligacao_pai_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partidos', type_='foreignkey')
    op.drop_column('partidos', 'coligacao_pai_id')
    op.drop_column('partidos', 'tipo_entidade')
    op.drop_constraint(None, 'deputado_mandatos_legislativos', type_='foreignkey')
    op.drop_column('deputado_mandatos_legislativos', 'confianca_detecao_coligacao')
    op.drop_column('deputado_mandatos_legislativos', 'eh_coligacao')
    op.drop_column('deputado_mandatos_legislativos', 'coligacao_id')
    op.drop_column('deputado_mandatos_legislativos', 'tipo_entidade_politica')
    op.drop_index('idx_partido_sigla', table_name='coligacao_partidos')
    op.drop_index('idx_coligacao_partido', table_name='coligacao_partidos')
    op.drop_index('idx_ativo_coligacao', table_name='coligacao_partidos')
    op.drop_table('coligacao_partidos')
    op.drop_table('coligacoes')
    # ### end Alembic commands ###
