"""Add structured fields to MeetingAttendance and composition_context to DeputyGPSituation

Revision ID: c4283942464d
Revises: 92d4998e2b20
Create Date: 2025-07-31 17:42:14.653375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4283942464d'
down_revision: Union[str, Sequence[str], None] = '92d4998e2b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deputy_gp_situations', sa.Column('composition_context', sa.String(length=50), nullable=True))
    op.add_column('meeting_attendances', sa.Column('sigla_qualidade_presenca', sa.String(length=100), nullable=True))
    op.add_column('meeting_attendances', sa.Column('sigla_grupo', sa.String(length=50), nullable=True))
    op.add_column('meeting_attendances', sa.Column('sigla_falta', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_attendances', 'sigla_falta')
    op.drop_column('meeting_attendances', 'sigla_grupo')
    op.drop_column('meeting_attendances', 'sigla_qualidade_presenca')
    op.drop_column('deputy_gp_situations', 'composition_context')
    # ### end Alembic commands ###
