"""Add MeetingAttendance model and OrganMeeting III Legislature fields

Revision ID: c68600527816
Revises: 2fce3d981077
Create Date: 2025-07-31 08:47:25.966064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68600527816'
down_revision: Union[str, Sequence[str], None] = '2fce3d981077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('dep_id', sa.Integer(), nullable=True),
    sa.Column('dep_cad_id', sa.Integer(), nullable=True),
    sa.Column('dep_nome_parlamentar', sa.String(length=200), nullable=True),
    sa.Column('pres_tipo', sa.String(length=50), nullable=True),
    sa.Column('pres_justificacao', sa.Text(), nullable=True),
    sa.Column('dt_reuniao', sa.Date(), nullable=True),
    sa.Column('tipo_reuniao', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['organ_meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organ_meetings', sa.Column('reu_id', sa.Integer(), nullable=True))
    op.add_column('organ_meetings', sa.Column('reu_numero', sa.Integer(), nullable=True))
    op.add_column('organ_meetings', sa.Column('reu_data_hora', sa.String(length=50), nullable=True))
    op.add_column('organ_meetings', sa.Column('reu_final_plenario', sa.Boolean(), nullable=True))
    op.add_column('organ_meetings', sa.Column('reu_tir_des', sa.String(length=200), nullable=True))
    op.add_column('organ_meetings', sa.Column('leg_des', sa.String(length=50), nullable=True))
    op.add_column('organ_meetings', sa.Column('sel_numero', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organ_meetings', 'sel_numero')
    op.drop_column('organ_meetings', 'leg_des')
    op.drop_column('organ_meetings', 'reu_tir_des')
    op.drop_column('organ_meetings', 'reu_final_plenario')
    op.drop_column('organ_meetings', 'reu_data_hora')
    op.drop_column('organ_meetings', 'reu_numero')
    op.drop_column('organ_meetings', 'reu_id')
    op.drop_table('meeting_attendances')
    # ### end Alembic commands ###
