"""Add missing fields for Atividades: obs field and RelatorioParlamentarPublicacao model

Revision ID: c7353178b62a
Revises: 2dcb66294669
Create Date: 2025-07-30 18:11:40.901849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7353178b62a'
down_revision: Union[str, Sequence[str], None] = '2dcb66294669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatorio_parlamentar_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.String(length=100), nullable=True),
    sa.Column('pub_tp', sa.String(length=50), nullable=True),
    sa.Column('pub_leg', sa.String(length=50), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('id_deb', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorio_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('atividade_parlamentar_publicacoes', sa.Column('obs', sa.Text(), nullable=True))
    op.add_column('relatorio_parlamentar', sa.Column('data_agendamento_debate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relatorio_parlamentar', 'data_agendamento_debate')
    op.drop_column('atividade_parlamentar_publicacoes', 'obs')
    op.drop_table('relatorio_parlamentar_publicacoes')
    # ### end Alembic commands ###
