"""Remove legacy registo_interesses tables and models

Revision ID: c73ea5912a5b
Revises: b8e4bf94153e
Create Date: 2025-08-12 08:54:33.162323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c73ea5912a5b'
down_revision: Union[str, Sequence[str], None] = 'b8e4bf94153e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first (those with foreign keys)
    op.drop_table('registo_interesses_cargos')
    op.drop_table('registo_interesses_atividades')  
    op.drop_table('registo_interesses_sociedades')
    # Then drop parent tables
    op.drop_table('registo_interesses_v2')
    op.drop_table('registo_interesses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registo_interesses_sociedades',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('registo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rgs_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rgs_entidade', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rgs_area_atividade', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rgs_local_sede', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rgs_parti_social', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rgs_valor', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rgs_observacoes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['registo_id'], ['registo_interesses_v2.id'], name=op.f('registo_interesses_sociedades_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('registo_interesses_atividades',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('registo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rga_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rga_atividade', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rga_data_inicio', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('rga_data_fim', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('rga_remunerada', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('rga_entidade', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rga_valor', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rga_observacoes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['registo_id'], ['registo_interesses_v2.id'], name=op.f('registo_interesses_atividades_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('registo_interesses',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deputado_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('legislatura_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('marital_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('spouse_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('matrimonial_regime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('exclusivity', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('dgf_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('cad_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cad_nome_completo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cad_actividade_profissional', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('cad_estado_civil_cod', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('cad_estado_civil_des', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('cad_fam_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cad_nome_conjuge', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cad_rgi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('schema_version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], name=op.f('registo_interesses_ibfk_1')),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], name=op.f('registo_interesses_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('registo_interesses_cargos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('registo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rgc_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rgc_cargo', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rgc_entidade', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rgc_area_atividade', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rgc_local_sede', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rgc_data_inicio', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('rgc_data_fim', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('rgc_valor', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rgc_observacoes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['registo_id'], ['registo_interesses_v2.id'], name=op.f('registo_interesses_cargos_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('registo_interesses_v2',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deputado_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cad_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cad_estado_civil_cod', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('cad_nome_completo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cad_actividade_profissional', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('cad_estado_civil_des', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], name=op.f('registo_interesses_v2_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
