"""Add additional fields to diploma models for comprehensive field processing

Revision ID: c908dc1f7f15
Revises: 21cc9d653cb6
Create Date: 2025-08-07 18:56:02.097118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c908dc1f7f15'
down_revision: Union[str, Sequence[str], None] = '21cc9d653cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamento_estado_diploma_alineas', sa.Column('estado', sa.String(length=100), nullable=True, comment='Alinea state (DiplomaAlineaEstado)'))
    op.add_column('orcamento_estado_diploma_artigos', sa.Column('diploma_artigo_id_alt', sa.Integer(), nullable=True, comment='Alternative Article ID (DiplomaArtigoID)'))
    op.add_column('orcamento_estado_diploma_artigos', sa.Column('diploma_artigo_titulo_alt', sa.Text(), nullable=True, comment='Alternative Article title (DiplomaArtigoTituto)'))
    op.add_column('orcamento_estado_diploma_artigos', sa.Column('diploma_artigo_estado', sa.String(length=100), nullable=True, comment='Alternative Article state (DiplomaArtigoEstado)'))
    op.add_column('orcamento_estado_diploma_numeros', sa.Column('diploma_numero_id', sa.Integer(), nullable=True, comment='Number ID (DiplomaNumeroID)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamento_estado_diploma_numeros', 'diploma_numero_id')
    op.drop_column('orcamento_estado_diploma_artigos', 'diploma_artigo_estado')
    op.drop_column('orcamento_estado_diploma_artigos', 'diploma_artigo_titulo_alt')
    op.drop_column('orcamento_estado_diploma_artigos', 'diploma_artigo_id_alt')
    op.drop_column('orcamento_estado_diploma_alineas', 'estado')
    # ### end Alembic commands ###
