"""Change type_classification from Integer to String(50) to support string values

Revision ID: cba6cfbfc577
Revises: 29825b710250
Create Date: 2025-08-10 21:58:25.240206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cba6cfbfc577'
down_revision: Union[str, Sequence[str], None] = '29825b710250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registo_interesses_activities_unified', 'type_classification',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('registo_interesses_social_positions_unified', 'type_classification',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registo_interesses_social_positions_unified', 'type_classification',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('registo_interesses_activities_unified', 'type_classification',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
