"""Add fields to cooperation models

Revision ID: cd348bcdc954
Revises: 783a73825133
Create Date: 2025-08-01 08:55:13.955309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd348bcdc954'
down_revision: Union[str, Sequence[str], None] = '783a73825133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cooperacao_atividades', sa.Column('atividade_id', sa.Integer(), nullable=True))
    op.add_column('cooperacao_atividades', sa.Column('nome', sa.String(length=255), nullable=True))
    op.add_column('cooperacao_atividades', sa.Column('local', sa.String(length=255), nullable=True))
    op.add_column('cooperacao_participantes', sa.Column('participante_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cooperacao_participantes', 'participante_id')
    op.drop_column('cooperacao_atividades', 'local')
    op.drop_column('cooperacao_atividades', 'nome')
    op.drop_column('cooperacao_atividades', 'atividade_id')
    # ### end Alembic commands ###
