"""Add RelatoresIniciativas, ReunioesDelegacoesPermanentes models and missing fields

Revision ID: cd8901718c48
Revises: 5b2f56184f57
Create Date: 2025-07-31 07:25:34.625356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8901718c48'
down_revision: Union[str, Sequence[str], None] = '5b2f56184f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatores_iniciativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividade_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividade_out_id'], ['actividade_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatores_iniciativas_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatores_iniciativas_id', sa.Integer(), nullable=False),
    sa.Column('ini_nr', sa.String(length=50), nullable=True),
    sa.Column('acc_dtrel', sa.String(length=50), nullable=True),
    sa.Column('ini_ti', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatores_iniciativas_id'], ['relatores_iniciativas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reunioes_delegacoes_permanentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegacoes_permanentes_out_id', sa.Integer(), nullable=False),
    sa.Column('ren_dt_ini', sa.String(length=50), nullable=True),
    sa.Column('ren_loc', sa.String(length=500), nullable=True),
    sa.Column('ren_dt_fim', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegacoes_permanentes_out_id'], ['delegacoes_permanentes_out.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('delegacoes_eventuais_out', sa.Column('dev_sel_lg', sa.String(length=20), nullable=True))
    op.add_column('subcomissoes_grupos_trabalho_out', sa.Column('scm_com_cd', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcomissoes_grupos_trabalho_out', 'scm_com_cd')
    op.drop_column('delegacoes_eventuais_out', 'dev_sel_lg')
    op.drop_table('reunioes_delegacoes_permanentes')
    op.drop_table('relatores_iniciativas_out')
    op.drop_table('relatores_iniciativas')
    # ### end Alembic commands ###
