"""Add I Legislature biographical data models - qualifications, roles, titles, decorations, publications, mandates, interest registry

Revision ID: d05d51845201
Revises: 97b92e549108
Create Date: 2025-07-31 11:45:28.179613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05d51845201'
down_revision: Union[str, Sequence[str], None] = '97b92e549108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deputado_cargos_funcoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('fun_id', sa.Integer(), nullable=True),
    sa.Column('fun_des', sa.Text(), nullable=True),
    sa.Column('fun_ordem', sa.Integer(), nullable=True),
    sa.Column('fun_antiga', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deputado_condecoracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('cod_id', sa.Integer(), nullable=True),
    sa.Column('cod_des', sa.Text(), nullable=True),
    sa.Column('cod_ordem', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deputado_habilitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('hab_id', sa.Integer(), nullable=True),
    sa.Column('hab_des', sa.String(length=500), nullable=True),
    sa.Column('hab_tipo_id', sa.Integer(), nullable=True),
    sa.Column('hab_estado', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deputado_mandatos_legislativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('dep_nome_parlamentar', sa.String(length=200), nullable=True),
    sa.Column('leg_des', sa.String(length=50), nullable=True),
    sa.Column('ce_des', sa.String(length=100), nullable=True),
    sa.Column('par_sigla', sa.String(length=20), nullable=True),
    sa.Column('par_des', sa.String(length=200), nullable=True),
    sa.Column('gp_sigla', sa.String(length=20), nullable=True),
    sa.Column('gp_des', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deputado_obras_publicadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('pub_id', sa.Integer(), nullable=True),
    sa.Column('pub_des', sa.Text(), nullable=True),
    sa.Column('pub_ordem', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deputado_titulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('tit_id', sa.Integer(), nullable=True),
    sa.Column('tit_des', sa.Text(), nullable=True),
    sa.Column('tit_ordem', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registo_interesses_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('cad_id', sa.Integer(), nullable=True),
    sa.Column('cad_estado_civil_cod', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('deputados', sa.Column('sexo', sa.String(length=1), nullable=True))
    op.add_column('deputados', sa.Column('estado_civil_cod', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deputados', 'estado_civil_cod')
    op.drop_column('deputados', 'sexo')
    op.drop_table('registo_interesses_v2')
    op.drop_table('deputado_titulos')
    op.drop_table('deputado_obras_publicadas')
    op.drop_table('deputado_mandatos_legislativos')
    op.drop_table('deputado_habilitacoes')
    op.drop_table('deputado_condecoracoes')
    op.drop_table('deputado_cargos_funcoes')
    # ### end Alembic commands ###
