"""add_descricao_and_doc_link_fields

Revision ID: d46268eb0d79
Revises: 1a8d029ebd54
Create Date: 2026-01-01 20:12:32.382156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46268eb0d79'
down_revision: Union[str, Sequence[str], None] = '1a8d029ebd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iniciativas_comissoes_audicoes', sa.Column('descricao', sa.Text(), nullable=True))
    op.add_column('iniciativas_comissoes_documentos', sa.Column('doc_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iniciativas_comissoes_documentos', 'doc_link')
    op.drop_column('iniciativas_comissoes_audicoes', 'descricao')
    # ### end Alembic commands ###
