"""Increase DeputyInitiative tipo field length to 200 characters

Revision ID: db2fea81c30c
Revises: 18521b6937e0
Create Date: 2025-07-31 22:00:32.516068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db2fea81c30c'
down_revision: Union[str, Sequence[str], None] = '18521b6937e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deputy_initiatives', 'tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deputy_initiatives', 'tipo',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
