"""Add dep_nome_completo to admin council and leader conference historical compositions

Revision ID: dbd6622bf569
Revises: c4283942464d
Create Date: 2025-07-31 17:58:17.094148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd6622bf569'
down_revision: Union[str, Sequence[str], None] = 'c4283942464d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrative_council_historical_compositions', sa.Column('dep_nome_completo', sa.String(length=200), nullable=True))
    op.add_column('leader_conference_historical_compositions', sa.Column('dep_nome_completo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leader_conference_historical_compositions', 'dep_nome_completo')
    op.drop_column('administrative_council_historical_compositions', 'dep_nome_completo')
    # ### end Alembic commands ###
