"""Increase nome_sigla column length to handle long commission names

Revision ID: dcf2f3ad6b7b
Revises: 6220583b3805
Create Date: 2025-07-31 21:29:10.340826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf2f3ad6b7b'
down_revision: Union[str, Sequence[str], None] = '6220583b3805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrative_councils', 'nome_sigla', type_=sa.String(500))
    op.alter_column('ar_boards', 'nome_sigla', type_=sa.String(500))
    op.alter_column('commissions', 'nome_sigla', type_=sa.String(500))
    op.alter_column('leader_conferences', 'nome_sigla', type_=sa.String(500))
    op.alter_column('permanent_committees', 'nome_sigla', type_=sa.String(500))
    op.alter_column('plenaries', 'nome_sigla', type_=sa.String(500))
    op.alter_column('sub_committees', 'nome_sigla', type_=sa.String(500))
    op.alter_column('work_groups', 'nome_sigla', type_=sa.String(500))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_groups', 'nome_sigla', type_=sa.String(200))
    op.alter_column('sub_committees', 'nome_sigla', type_=sa.String(200))
    op.alter_column('plenaries', 'nome_sigla', type_=sa.String(200))
    op.alter_column('permanent_committees', 'nome_sigla', type_=sa.String(200))
    op.alter_column('leader_conferences', 'nome_sigla', type_=sa.String(200))
    op.alter_column('commissions', 'nome_sigla', type_=sa.String(200))
    op.alter_column('ar_boards', 'nome_sigla', type_=sa.String(200))
    op.alter_column('administrative_councils', 'nome_sigla', type_=sa.String(200))
    # ### end Alembic commands ###
