"""Add missing fields to IniciativaEventoComissao

Revision ID: de9c20bb935d
Revises: 3ec4be30216e
Create Date: 2026-01-01 10:14:48.024247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9c20bb935d'
down_revision: Union[str, Sequence[str], None] = '3ec4be30216e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iniciativas_eventos_comissoes', sa.Column('data_relatorio', sa.Date(), nullable=True))
    op.add_column('iniciativas_eventos_comissoes', sa.Column('data_parecer', sa.Date(), nullable=True))
    op.add_column('iniciativas_eventos_comissoes', sa.Column('obs', sa.Text(), nullable=True))
    op.add_column('iniciativas_eventos_comissoes', sa.Column('link_parecer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iniciativas_eventos_comissoes', 'link_parecer')
    op.drop_column('iniciativas_eventos_comissoes', 'obs')
    op.drop_column('iniciativas_eventos_comissoes', 'data_parecer')
    op.drop_column('iniciativas_eventos_comissoes', 'data_relatorio')
    # ### end Alembic commands ###
