"""Add final missing fields for complete IX Legislature coverage

Revision ID: e0035f6c91d0
Revises: 73b5ea4fe652
Create Date: 2025-07-31 07:32:06.370435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0035f6c91d0'
down_revision: Union[str, Sequence[str], None] = '73b5ea4fe652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividade_intervencoes_out', sa.Column('int_te', sa.Text(), nullable=True))
    op.add_column('comissoes_out', sa.Column('cms_cargo', sa.String(length=200), nullable=True))
    op.add_column('grupos_parlamentares_amizade_out', sa.Column('gpl_sel_lg', sa.String(length=20), nullable=True))
    op.add_column('grupos_parlamentares_amizade_out', sa.Column('cga_dtini', sa.String(length=50), nullable=True))
    op.add_column('relatores_iniciativas_out', sa.Column('ini_sel_lg', sa.String(length=20), nullable=True))
    op.add_column('relatores_iniciativas_out', sa.Column('rel_fase', sa.String(length=200), nullable=True))
    op.add_column('relatores_peticoes_out', sa.Column('pet_id', sa.Integer(), nullable=True))
    op.add_column('relatores_peticoes_out', sa.Column('pet_nr', sa.String(length=50), nullable=True))
    op.add_column('subcomissoes_grupos_trabalho_out', sa.Column('ccm_dscom', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcomissoes_grupos_trabalho_out', 'ccm_dscom')
    op.drop_column('relatores_peticoes_out', 'pet_nr')
    op.drop_column('relatores_peticoes_out', 'pet_id')
    op.drop_column('relatores_iniciativas_out', 'rel_fase')
    op.drop_column('relatores_iniciativas_out', 'ini_sel_lg')
    op.drop_column('grupos_parlamentares_amizade_out', 'cga_dtini')
    op.drop_column('grupos_parlamentares_amizade_out', 'gpl_sel_lg')
    op.drop_column('comissoes_out', 'cms_cargo')
    op.drop_column('actividade_intervencoes_out', 'int_te')
    # ### end Alembic commands ###
