"""Add item_id foreign key to OrcamentoEstadoPropostaAlteracao model

Revision ID: e01d0dfd5efe
Revises: 2e58cc32ab2e
Create Date: 2025-08-06 15:44:03.818879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01d0dfd5efe'
down_revision: Union[str, Sequence[str], None] = '2e58cc32ab2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamento_estado_propostas_alteracao', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orcamento_estado_propostas_alteracao', 'orcamento_estado_items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orcamento_estado_propostas_alteracao', type_='foreignkey')
    op.drop_column('orcamento_estado_propostas_alteracao', 'item_id')
    # ### end Alembic commands ###
