"""Add IX Legislature petition fields and models

Revision ID: e1dd57e6589d
Revises: 28d338e90bab
Create Date: 2025-08-04 05:52:11.653802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1dd57e6589d'
down_revision: Union[str, Sequence[str], None] = '28d338e90bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peticoes_pedidos_reiteracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_informacao_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('data_resposta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_informacao_id'], ['peticoes_pedidos_informacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_relatorios_finais_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_final_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.Text(), nullable=True),
    sa.Column('pub_tp', sa.Text(), nullable=True),
    sa.Column('pub_leg', sa.Text(), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_final_id'], ['peticoes_relatorios_finais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('peticoes_pedidos_informacao', sa.Column('relatorio_intercalar', sa.Text(), nullable=True))
    op.add_column('peticoes_pedidos_informacao', sa.Column('data_resposta', sa.Date(), nullable=True))
    op.add_column('peticoes_publicacoes', sa.Column('supl', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peticoes_publicacoes', 'supl')
    op.drop_column('peticoes_pedidos_informacao', 'data_resposta')
    op.drop_column('peticoes_pedidos_informacao', 'relatorio_intercalar')
    op.drop_table('peticoes_relatorios_finais_publicacoes')
    op.drop_table('peticoes_pedidos_reiteracao')
    # ### end Alembic commands ###
