"""Add IX Legislature support: VotacaoRelatorio, Relatores, Audicoes, Audiencias models

Revision ID: e2fd23e55577
Revises: be032a4b6c61
Create Date: 2025-07-30 19:37:58.194219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2fd23e55577'
down_revision: Union[str, Sequence[str], None] = 'be032a4b6c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audicoes_parlamentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=True),
    sa.Column('id_audicao', sa.Integer(), nullable=True),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('data_audicao', sa.Date(), nullable=True),
    sa.Column('comissao', sa.String(length=200), nullable=True),
    sa.Column('tipo_audicao', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audiencias_parlamentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=True),
    sa.Column('numero_audiencia', sa.Integer(), nullable=True),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('data_audiencia', sa.Date(), nullable=True),
    sa.Column('comissao', sa.String(length=200), nullable=True),
    sa.Column('concedida', sa.Boolean(), nullable=True),
    sa.Column('tipo_audiencia', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_parlamentar_relatores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('gp', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorio_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_parlamentar_votacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('votacao_id', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('reuniao', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorio_parlamentar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_parlamentar_votacao_publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votacao_id', sa.Integer(), nullable=False),
    sa.Column('pub_nr', sa.Integer(), nullable=True),
    sa.Column('pub_tipo', sa.String(length=100), nullable=True),
    sa.Column('pub_tp', sa.String(length=50), nullable=True),
    sa.Column('pub_leg', sa.String(length=50), nullable=True),
    sa.Column('pub_sl', sa.Integer(), nullable=True),
    sa.Column('pub_dt', sa.Date(), nullable=True),
    sa.Column('pag', sa.Text(), nullable=True),
    sa.Column('url_diario', sa.Text(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('id_deb', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['votacao_id'], ['relatorio_parlamentar_votacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('relatorio_parlamentar', sa.Column('observacoes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relatorio_parlamentar', 'observacoes')
    op.drop_table('relatorio_parlamentar_votacao_publicacoes')
    op.drop_table('relatorio_parlamentar_votacoes')
    op.drop_table('relatorio_parlamentar_relatores')
    op.drop_table('audiencias_parlamentares')
    op.drop_table('audicoes_parlamentares')
    # ### end Alembic commands ###
