"""add retry_at field for exponential backoff

Revision ID: e70c0600aa57
Revises: 434bcc563fa6
Create Date: 2025-08-12 15:25:29.745867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70c0600aa57'
down_revision: Union[str, Sequence[str], None] = '434bcc563fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_status', sa.Column('retry_at', sa.DateTime(), nullable=True, comment='Scheduled retry time for failed imports with exponential backoff'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_status', 'retry_at')
    # ### end Alembic commands ###
