"""Add missing fields to Perguntas/Requerimentos models from PDF analysis

Revision ID: e713c0e844e1
Revises: 43f90cd970e1
Create Date: 2025-08-06 13:41:16.557115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e713c0e844e1'
down_revision: Union[str, Sequence[str], None] = '43f90cd970e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pergunta_requerimento_autores', 'id_cadastro',
               existing_type=mysql.INTEGER(),
               comment='Identificador do registo de cadastro do Deputado (XML: idCadastro)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_autores', 'nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Nome do Deputado (XML: nome)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_autores', 'gp',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Grupo Parlamentar do Deputado (XML: GP)',
               existing_nullable=True)
    op.add_column('pergunta_requerimento_destinatarios', sa.Column('data_prorrogacao', sa.Date(), nullable=True, comment='Data do pedido de prorrogação do prazo (XML: dataProrrogacao)'))
    op.add_column('pergunta_requerimento_destinatarios', sa.Column('data_reenvio', sa.Date(), nullable=True, comment='Data de reenvio para outro destinatário (XML: dataReenvio)'))
    op.add_column('pergunta_requerimento_destinatarios', sa.Column('devolvido', sa.Boolean(), nullable=True, comment='Indica se foi devolvido (XML: devolvido)'))
    op.add_column('pergunta_requerimento_destinatarios', sa.Column('prazo_prorrogacao', sa.Integer(), nullable=True, comment='Prazo em dias (XML: prazoProrrogacao)'))
    op.add_column('pergunta_requerimento_destinatarios', sa.Column('prorrogado', sa.Boolean(), nullable=True, comment='Indica se foi prorrogado (XML: prorrogado)'))
    op.add_column('pergunta_requerimento_destinatarios', sa.Column('reenviado', sa.Boolean(), nullable=True, comment='Indica se foi reenviado (XML: reenviado)'))
    op.add_column('pergunta_requerimento_destinatarios', sa.Column('retirado', sa.Boolean(), nullable=True, comment='Indica se foi retirado (XML: retirado)'))
    op.alter_column('pergunta_requerimento_destinatarios', 'nome_entidade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Nome do destinatário (XML: nomeEntidade)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_destinatarios', 'data_envio',
               existing_type=sa.DATE(),
               comment='Data de envio (legacy compatibility)',
               existing_nullable=True)
    op.add_column('pergunta_requerimento_publicacoes', sa.Column('debate_dt_reu', sa.Date(), nullable=True, comment='Data da reunião plenária onde ocorreu o Debate (XML: debateDtReu)'))
    op.add_column('pergunta_requerimento_publicacoes', sa.Column('id_act', sa.Integer(), nullable=True, comment='Identificador da Atividade associada (XML: idAct)'))
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_nr',
               existing_type=mysql.INTEGER(),
               comment='Número da Publicação (XML: pubNr)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Descrição de tipo usando TipodePublicacao (XML: pubTipo)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_tp',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='Tipo de publicação usando TipodePublicacao enum (XML: pubTp)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_leg',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='Legislatura da Publicação (XML: pubLeg)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_sl',
               existing_type=mysql.INTEGER(),
               comment='Sessão legislativa da Publicação (XML: pubSL)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_dt',
               existing_type=sa.DATE(),
               comment='Data da Publicação (XML: pubdt)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'id_pag',
               existing_type=mysql.INTEGER(),
               comment='Identificador da Paginação (XML: idPag)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'url_diario',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Link para o DAR da Publicação (XML: URLDiario)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pag',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Páginas (XML: pag)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'supl',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='Suplemento da Publicação (XML: supl)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'obs',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Observações (XML: obs)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pag_final_diario_supl',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Página final do suplemento (XML: pagFinalDiarioSupl)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_respostas', 'entidade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Entidade que elaborou a resposta (XML: Entidade)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_respostas', 'data_resposta',
               existing_type=sa.DATE(),
               comment='Data da resposta (XML: dataResposta)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_respostas', 'ficheiro',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Link para o ficheiro (XML: Ficheiro)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_respostas', 'doc_remetida',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Documentação remetida com a resposta (XML: docRemetida)',
               existing_nullable=True)
    op.add_column('perguntas_requerimentos', sa.Column('fundamentacao', sa.Text(), nullable=True, comment='Descrição da fundamentação do requerimento (XML: fundamentacao)'))
    op.alter_column('perguntas_requerimentos', 'requerimento_id',
               existing_type=mysql.INTEGER(),
               comment='Código de Identificação do Requerimento (XML: id)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Tipo: Pergunta ou Requerimento (XML: tipo)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'nr',
               existing_type=mysql.INTEGER(),
               comment='Número do Requerimento/Pergunta (XML: nr)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'req_tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Tipo de Registo usando TipodeRequerimento enum (XML: reqTipo)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'sessao',
               existing_type=mysql.INTEGER(),
               comment='Sessão Legislativa (XML: sessao)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'assunto',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Assunto do requerimento ou pergunta (XML: assunto)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'dt_entrada',
               existing_type=sa.DATE(),
               comment='Data da Entrada do Requerimento (XML: dtEntrada)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'data_envio',
               existing_type=sa.DATE(),
               comment='Data de envio para o destinatário (XML: dataEnvio)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'observacoes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Observações (XML: observacoes)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'ficheiro',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Nome do ficheiro que contém o texto (XML: ficheiro)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('perguntas_requerimentos', 'ficheiro',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Nome do ficheiro que contém o texto (XML: ficheiro)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'observacoes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Observações (XML: observacoes)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'data_envio',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de envio para o destinatário (XML: dataEnvio)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'dt_entrada',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data da Entrada do Requerimento (XML: dtEntrada)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'assunto',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Assunto do requerimento ou pergunta (XML: assunto)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'sessao',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Sessão Legislativa (XML: sessao)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'req_tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Tipo de Registo usando TipodeRequerimento enum (XML: reqTipo)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'nr',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Número do Requerimento/Pergunta (XML: nr)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Tipo: Pergunta ou Requerimento (XML: tipo)',
               existing_nullable=True)
    op.alter_column('perguntas_requerimentos', 'requerimento_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Código de Identificação do Requerimento (XML: id)',
               existing_nullable=True)
    op.drop_column('perguntas_requerimentos', 'fundamentacao')
    op.alter_column('pergunta_requerimento_respostas', 'doc_remetida',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Documentação remetida com a resposta (XML: docRemetida)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_respostas', 'ficheiro',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Link para o ficheiro (XML: Ficheiro)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_respostas', 'data_resposta',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data da resposta (XML: dataResposta)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_respostas', 'entidade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Entidade que elaborou a resposta (XML: Entidade)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pag_final_diario_supl',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Página final do suplemento (XML: pagFinalDiarioSupl)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'obs',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Observações (XML: obs)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'supl',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='Suplemento da Publicação (XML: supl)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pag',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Páginas (XML: pag)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'url_diario',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Link para o DAR da Publicação (XML: URLDiario)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'id_pag',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Identificador da Paginação (XML: idPag)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_dt',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data da Publicação (XML: pubdt)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_sl',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Sessão legislativa da Publicação (XML: pubSL)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_leg',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='Legislatura da Publicação (XML: pubLeg)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_tp',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='Tipo de publicação usando TipodePublicacao enum (XML: pubTp)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Descrição de tipo usando TipodePublicacao (XML: pubTipo)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_publicacoes', 'pub_nr',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Número da Publicação (XML: pubNr)',
               existing_nullable=True)
    op.drop_column('pergunta_requerimento_publicacoes', 'id_act')
    op.drop_column('pergunta_requerimento_publicacoes', 'debate_dt_reu')
    op.alter_column('pergunta_requerimento_destinatarios', 'data_envio',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de envio (legacy compatibility)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_destinatarios', 'nome_entidade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Nome do destinatário (XML: nomeEntidade)',
               existing_nullable=True)
    op.drop_column('pergunta_requerimento_destinatarios', 'retirado')
    op.drop_column('pergunta_requerimento_destinatarios', 'reenviado')
    op.drop_column('pergunta_requerimento_destinatarios', 'prorrogado')
    op.drop_column('pergunta_requerimento_destinatarios', 'prazo_prorrogacao')
    op.drop_column('pergunta_requerimento_destinatarios', 'devolvido')
    op.drop_column('pergunta_requerimento_destinatarios', 'data_reenvio')
    op.drop_column('pergunta_requerimento_destinatarios', 'data_prorrogacao')
    op.alter_column('pergunta_requerimento_autores', 'gp',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Grupo Parlamentar do Deputado (XML: GP)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_autores', 'nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Nome do Deputado (XML: nome)',
               existing_nullable=True)
    op.alter_column('pergunta_requerimento_autores', 'id_cadastro',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Identificador do registo de cadastro do Deputado (XML: idCadastro)',
               existing_nullable=True)
    # ### end Alembic commands ###
