"""Add I Legislature third validation fields

Revision ID: e7f41973e033
Revises: c2d75829a423
Create Date: 2025-07-31 07:56:10.742397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f41973e033'
down_revision: Union[str, Sequence[str], None] = 'c2d75829a423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades_comissao_outs', sa.Column('act_dtdes1', sa.String(length=50), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('act_sl', sa.String(length=20), nullable=True))
    op.add_column('actividades_comissao_outs', sa.Column('tev_tp', sa.String(length=100), nullable=True))
    # MySQL supports foreign key constraints
    op.add_column('comissoes_out', sa.Column('cms_situacao', sa.String(length=200), nullable=True))
    op.add_column('dados_deputado_parlamento_jovens', sa.Column('legislatura', sa.String(length=20), nullable=True))
    op.add_column('relatores_ini_europeias_out', sa.Column('ine_data_relatorio', sa.String(length=50), nullable=True))
    op.add_column('relatores_ini_europeias_out', sa.Column('leg', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relatores_ini_europeias_out', 'leg')
    op.drop_column('relatores_ini_europeias_out', 'ine_data_relatorio')
    op.drop_column('dados_deputado_parlamento_jovens', 'legislatura')
    op.drop_column('comissoes_out', 'cms_situacao')
    # MySQL supports foreign key constraints
    op.drop_column('actividades_comissao_outs', 'tev_tp')
    op.drop_column('actividades_comissao_outs', 'act_sl')
    op.drop_column('actividades_comissao_outs', 'act_dtdes1')
    # ### end Alembic commands ###
