"""Add remaining IX Legislature petition fields

Revision ID: ee4b0dc73906
Revises: e1dd57e6589d
Create Date: 2025-08-04 05:56:55.043635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4b0dc73906'
down_revision: Union[str, Sequence[str], None] = 'e1dd57e6589d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peticoes_audiencias', sa.Column('audiencia_id', sa.Integer(), nullable=True))
    op.add_column('peticoes_detalhadas', sa.Column('pet_obs', sa.Text(), nullable=True))
    op.add_column('peticoes_oradores', sa.Column('membro_governo_nome', sa.Text(), nullable=True))
    op.add_column('peticoes_oradores', sa.Column('membro_governo_cargo', sa.Text(), nullable=True))
    op.add_column('peticoes_oradores', sa.Column('deputado_id_cadastro', sa.Integer(), nullable=True))
    op.add_column('peticoes_oradores', sa.Column('deputado_nome', sa.Text(), nullable=True))
    op.add_column('peticoes_pedidos_informacao', sa.Column('data_oficio', sa.Date(), nullable=True))
    op.add_column('peticoes_pedidos_reiteracao', sa.Column('nr_oficio', sa.Text(), nullable=True))
    op.add_column('peticoes_pedidos_reiteracao', sa.Column('oficio_resposta', sa.Text(), nullable=True))
    op.add_column('peticoes_relatorios_finais_publicacoes', sa.Column('pag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peticoes_relatorios_finais_publicacoes', 'pag')
    op.drop_column('peticoes_pedidos_reiteracao', 'oficio_resposta')
    op.drop_column('peticoes_pedidos_reiteracao', 'nr_oficio')
    op.drop_column('peticoes_pedidos_informacao', 'data_oficio')
    op.drop_column('peticoes_oradores', 'deputado_nome')
    op.drop_column('peticoes_oradores', 'deputado_id_cadastro')
    op.drop_column('peticoes_oradores', 'membro_governo_cargo')
    op.drop_column('peticoes_oradores', 'membro_governo_nome')
    op.drop_column('peticoes_detalhadas', 'pet_obs')
    op.drop_column('peticoes_audiencias', 'audiencia_id')
    # ### end Alembic commands ###
