"""Remove unused translation fields

Revision ID: f677c2783306
Revises: 7e4e1f4b08a4
Create Date: 2025-08-09 08:52:28.237934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f677c2783306'
down_revision: Union[str, Sequence[str], None] = '7e4e1f4b08a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamento_estado_artigos', 'estado_desc')
    op.drop_column('orcamento_estado_iniciativas', 'estado_desc')
    op.drop_column('orcamento_estado_propostas_alteracao', 'estado_desc')
    op.drop_column('orcamento_estado_propostas_alteracao', 'tipo_desc')
    op.drop_column('orcamento_estado_propostas_alteracao', 'incide_desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamento_estado_propostas_alteracao', sa.Column('incide_desc', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.add_column('orcamento_estado_propostas_alteracao', sa.Column('tipo_desc', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.add_column('orcamento_estado_propostas_alteracao', sa.Column('estado_desc', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.add_column('orcamento_estado_iniciativas', sa.Column('estado_desc', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.add_column('orcamento_estado_artigos', sa.Column('estado_desc', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    # ### end Alembic commands ###
