"""Add DelegacaoPermanenteComissaoMembro model for XI Legislature nested commission members

Revision ID: f7acd19fc553
Revises: 2513b754a993
Create Date: 2025-08-04 06:48:07.032348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7acd19fc553'
down_revision: Union[str, Sequence[str], None] = '2513b754a993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegacao_permanente_comissao_membros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comissao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('gp', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comissao_id'], ['delegacao_permanente_comissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delegacao_permanente_comissao_membros')
    # ### end Alembic commands ###
