"""Add idInt to speaker/committee publications and update governo field

Revision ID: fb00d80a1596
Revises: 201de678bfdd
Create Date: 2025-08-01 08:35:24.219880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb00d80a1596'
down_revision: Union[str, Sequence[str], None] = '201de678bfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iniciativas_comissoes_publicacoes', sa.Column('id_int', sa.Integer(), nullable=True))
    op.add_column('iniciativas_intervencoes_oradores_membros_governo', sa.Column('governo', sa.Text(), nullable=True))
    op.drop_column('iniciativas_intervencoes_oradores_membros_governo', 'ministerio')
    op.add_column('iniciativas_intervencoes_oradores_publicacoes', sa.Column('id_int', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iniciativas_intervencoes_oradores_publicacoes', 'id_int')
    op.add_column('iniciativas_intervencoes_oradores_membros_governo', sa.Column('ministerio', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_column('iniciativas_intervencoes_oradores_membros_governo', 'governo')
    op.drop_column('iniciativas_comissoes_publicacoes', 'id_int')
    # ### end Alembic commands ###
