"""Add AudicaoParlamentar and AudienciaParlamentar models for atividades mapper

Revision ID: fcd8574010ee
Revises: eda4511b681c
Create Date: 2025-08-07 15:29:54.034166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd8574010ee'
down_revision: Union[str, Sequence[str], None] = 'eda4511b681c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audicao_parlamentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('id_audicao', sa.Integer(), nullable=True, comment='Audition identifier (IDAudicao)'),
    sa.Column('numero_audicao', sa.String(length=100), nullable=True, comment='Audition number (NumeroAudicao)'),
    sa.Column('data', sa.Date(), nullable=True, comment='Audition date (Data)'),
    sa.Column('assunto', sa.Text(), nullable=True, comment='Subject matter (Assunto)'),
    sa.Column('entidades', sa.Text(), nullable=True, comment='Participating entities (Entidades)'),
    sa.Column('sessao_legislativa', sa.Integer(), nullable=True, comment='Legislative session (SessaoLegislativa)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audicao_parlamentar_id_audicao_leg', 'audicao_parlamentar', ['id_audicao', 'legislatura_id'], unique=False)
    op.create_table('audiencia_parlamentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('id_audiencia', sa.Integer(), nullable=True, comment='Audience identifier (IDAudiencia)'),
    sa.Column('numero_audiencia', sa.String(length=100), nullable=True, comment='Audience number (NumeroAudiencia)'),
    sa.Column('data', sa.Date(), nullable=True, comment='Audience date (Data)'),
    sa.Column('assunto', sa.Text(), nullable=True, comment='Subject matter (Assunto)'),
    sa.Column('entidades', sa.Text(), nullable=True, comment='Participating entities (Entidades)'),
    sa.Column('sessao_legislativa', sa.Integer(), nullable=True, comment='Legislative session (SessaoLegislativa)'),
    sa.Column('concedida', sa.String(length=50), nullable=True, comment='Granted status (Concedida)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audiencia_parlamentar_id_audiencia_leg', 'audiencia_parlamentar', ['id_audiencia', 'legislatura_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audiencia_parlamentar_id_audiencia_leg', table_name='audiencia_parlamentar')
    op.drop_table('audiencia_parlamentar')
    op.drop_index('idx_audicao_parlamentar_id_audicao_leg', table_name='audicao_parlamentar')
    op.drop_table('audicao_parlamentar')
    # ### end Alembic commands ###
