"""Add VI Legislature PedidosEsclarecimento model

Revision ID: ff39f7598d4b
Revises: a776b079fed3
Create Date: 2025-08-04 06:12:07.874092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff39f7598d4b'
down_revision: Union[str, Sequence[str], None] = 'a776b079fed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peticoes_pedidos_esclarecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peticao_id', sa.Integer(), nullable=False),
    sa.Column('nr_oficio', sa.Text(), nullable=True),
    sa.Column('data_resposta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['peticao_id'], ['peticoes_detalhadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peticoes_pedidos_esclarecimento')
    # ### end Alembic commands ###
